import type { ContentQuestion } from '../../../types/content'

export const reactivityQuestions: ContentQuestion[] = [
  {
    id: 101,
    moduleId: "reactivity",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "reactivity",
      "state",
      "rendering",
    ],
    question: "Что означает реактивность во Vue?",
    answers: [
      { id: "a", text: "Vue отслеживает чтение и изменение данных, чтобы обновлять зависящий интерфейс" },
      { id: "b", text: "Vue запрещает изменять состояние после первого рендера" },
      { id: "c", text: "Vue обновляет DOM только после ручного вызова document.querySelector" },
      { id: "d", text: "Vue делает реактивными только CSS-классы, но не JavaScript-данные" },
    ],
    correctAnswer: "a",
    explanation: "Реактивность во Vue означает, что фреймворк отслеживает зависимости между данными и эффектами, например рендером компонента или computed. Когда реактивное значение меняется, Vue запускает связанные обновления. Остальные варианты неверны: состояние можно менять, DOM не нужно обновлять вручную, а реактивность относится к JavaScript-данным, а не только к CSS.",
    knowledgeId: "knowledge-reactivity-q101",
  },
  {
    id: 102,
    moduleId: "reactivity",
    type: "CodeOutput",
    difficulty: "Junior",
    tags: [
      "ref",
      "template-unwrapping",
      "value",
    ],
    question: "Что выведет шаблон `{{ count }}`, если в script setup объявлено `const count = ref(2)`?",
    answers: [
      { id: "a", text: "count.value" },
      { id: "b", text: "2" },
      { id: "c", text: "[object Object]" },
      { id: "d", text: "Ничего, потому что ref нельзя вывести в шаблон" },
    ],
    correctAnswer: "b",
    explanation: "В шаблоне Vue автоматически разворачивает ref, поэтому `{{ count }}` покажет `2`. В script setup для чтения и записи нужен `count.value`, но template скрывает эту деталь. `[object Object]` не появится, потому что Vue не выводит оболочку ref напрямую в интерполяции.",
    knowledgeId: "knowledge-reactivity-q102",
  },
  {
    id: 103,
    moduleId: "reactivity",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "ref",
      "primitive",
      "composition-api",
    ],
    question: "Когда чаще всего выбирают ref?",
    answers: [
      { id: "a", text: "Только для регистрации маршрутов Vue Router" },
      { id: "b", text: "Только для CSS-переменных" },
      { id: "c", text: "Для реактивного значения, особенно примитива или отдельной ссылки" },
      { id: "d", text: "Для отключения обновления шаблона" },
    ],
    correctAnswer: "c",
    explanation: "ref создаёт реактивную оболочку вокруг значения и хорошо подходит для чисел, строк, boolean-флагов, выбранных id и DOM-ссылок. Маршруты, CSS-переменные и отключение обновлений не являются задачей ref. Для объектов ref тоже возможен, но для связанной объектной модели иногда удобнее reactive.",
    knowledgeId: "knowledge-reactivity-q103",
  },
  {
    id: 104,
    moduleId: "reactivity",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "reactive",
      "object",
      "proxy",
    ],
    question: "Что возвращает reactive во Vue 3?",
    answers: [
      { id: "a", text: "Обычную строку с сериализованным JSON" },
      { id: "b", text: "Readonly-копию без возможности изменения" },
      { id: "c", text: "Promise, который нужно обязательно await-ить" },
      { id: "d", text: "Proxy-объект, который отслеживает чтение и запись свойств" },
    ],
    correctAnswer: "d",
    explanation: "reactive возвращает Proxy, который перехватывает операции чтения и записи свойств. Это позволяет Vue собирать зависимости и запускать обновления. Readonly-копию создаёт readonly, а не reactive; Promise здесь не используется.",
    knowledgeId: "knowledge-reactivity-q104",
  },
  {
    id: 105,
    moduleId: "reactivity",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "ref",
      "reactive",
      "choice",
    ],
    question: "Что обычно лучше выбрать для одного boolean-флага `isOpen`?",
    answers: [
      { id: "a", text: "ref(false), потому что это отдельное примитивное значение" },
      { id: "b", text: "reactive(false), потому что reactive работает только с boolean" },
      { id: "c", text: "markRaw(false), чтобы ускорить рендер" },
      { id: "d", text: "readonly(false), чтобы флаг можно было переключать" },
    ],
    correctAnswer: "a",
    explanation: "Для отдельного примитива удобнее `ref(false)`. `reactive` ожидает объектную структуру, а не примитив. markRaw нужен для исключения объектов из реактивности, а readonly делает значение защищённым от записи, поэтому он не подходит для переключаемого флага.",
    knowledgeId: "knowledge-reactivity-q105",
  },
  {
    id: 106,
    moduleId: "reactivity",
    type: "FindBug",
    difficulty: "JuniorPlus",
    tags: [
      "reactive",
      "destructuring",
      "lost-reactivity",
    ],
    question: "Что не так с кодом `const { count } = reactiveState`, если count должен оставаться реактивным?",
    answers: [
      { id: "a", text: "reactiveState нельзя читать внутри script setup" },
      { id: "b", text: "Обычная деструктуризация может потерять реактивную связь со свойством" },
      { id: "c", text: "count станет readonly автоматически" },
      { id: "d", text: "Vue запретит любую деструктуризацию на этапе сборки" },
    ],
    correctAnswer: "b",
    explanation: "При обычной деструктуризации свойство извлекается как текущее значение, и связь с Proxy может потеряться. Для сохранения реактивности используют toRef или toRefs. Vue не запрещает деструктуризацию, но разработчик должен понимать последствия.",
    knowledgeId: "knowledge-reactivity-q106",
  },
  {
    id: 107,
    moduleId: "reactivity",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "shallowRef",
      "deep-reactivity",
      "performance",
    ],
    question: "Чем shallowRef отличается от ref?",
    answers: [
      { id: "a", text: "shallowRef работает только в Options API" },
      { id: "b", text: "shallowRef запрещает хранить объекты" },
      { id: "c", text: "shallowRef отслеживает замену .value, но не делает вложенное значение глубоко реактивным" },
      { id: "d", text: "shallowRef всегда глубже reactive" },
    ],
    correctAnswer: "c",
    explanation: "shallowRef реактивен на уровне `.value`: замена значения триггерит обновление, но вложенные свойства объекта не становятся глубоко реактивными. Это полезно для больших структур или внешних инстансов. Остальные варианты неверны: shallowRef доступен в Composition API и может хранить объекты.",
    knowledgeId: "knowledge-reactivity-q107",
  },
  {
    id: 108,
    moduleId: "reactivity",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "shallowReactive",
      "nested-object",
      "reactivity",
    ],
    question: "Что важно заметить при ревью кода с shallowReactive для объекта с вложенными настройками?",
    answers: [
      { id: "a", text: "shallowReactive делает вложенные объекты более реактивными, чем reactive" },
      { id: "b", text: "shallowReactive нельзя использовать с объектами" },
      { id: "c", text: "shallowReactive автоматически вызывает nextTick после каждой записи" },
      { id: "d", text: "Реактивными будут только свойства верхнего уровня, вложенные объекты не станут глубоко реактивными" },
    ],
    correctAnswer: "d",
    explanation: "shallowReactive отслеживает верхний уровень объекта, но не превращает вложенные объекты в reactive Proxy. Это может быть осознанной оптимизацией или источником бага, если код ожидает глубокие обновления. Автоматического nextTick и запрета на объекты здесь нет.",
    knowledgeId: "knowledge-reactivity-q108",
  },
  {
    id: 109,
    moduleId: "reactivity",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "readonly",
      "immutability",
      "api-contract",
    ],
    question: "Для чего используется readonly?",
    answers: [
      { id: "a", text: "Чтобы создать реактивное представление, которое нельзя изменять напрямую" },
      { id: "b", text: "Чтобы сделать объект нерендеримым в template" },
      { id: "c", text: "Чтобы превратить ref в обычную строку" },
      { id: "d", text: "Чтобы отключить dependency tracking во всех компонентах" },
    ],
    correctAnswer: "a",
    explanation: "readonly создаёт защищённую от записи реактивную обёртку. Её используют для публичных API composable или передачи состояния без права мутации. Она не запрещает рендер, не превращает ref в строку и не отключает весь dependency tracking.",
    knowledgeId: "knowledge-reactivity-q109",
  },
  {
    id: 110,
    moduleId: "reactivity",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "computed",
      "cache",
      "derived-state",
    ],
    question: "Когда пересчитается computed, который читает `price.value` и `count.value`?",
    answers: [
      { id: "a", text: "При каждом движении мыши на странице" },
      { id: "b", text: "Когда изменится price или count" },
      { id: "c", text: "Только один раз при сборке проекта" },
      { id: "d", text: "Только после ручного вызова computed.update()" },
    ],
    correctAnswer: "b",
    explanation: "computed отслеживает реактивные зависимости, прочитанные внутри getter. Если меняется `price.value` или `count.value`, computed помечается устаревшим и пересчитывается при следующем чтении. Движение мыши, сборка проекта и несуществующий метод update не управляют computed.",
    knowledgeId: "knowledge-reactivity-q110",
  },
  {
    id: 111,
    moduleId: "reactivity",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "watch",
      "side-effects",
      "api",
    ],
    question: "Какой API лучше выбрать для запроса данных при изменении searchQuery?",
    answers: [
      { id: "a", text: "computed, потому что запрос является чистым вычислением" },
      { id: "b", text: "readonly, потому что он выполняет async-запросы" },
      { id: "c", text: "watch, потому что нужен побочный эффект при изменении значения" },
      { id: "d", text: "markRaw, потому что он подписывается на input" },
    ],
    correctAnswer: "c",
    explanation: "Запрос данных при изменении значения — побочный эффект, поэтому для него подходит watch. computed должен оставаться чистым производным значением и не выполнять запросы. readonly и markRaw решают другие задачи и не запускают async-сценарии.",
    knowledgeId: "knowledge-reactivity-q111",
  },
  {
    id: 112,
    moduleId: "reactivity",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "watchEffect",
      "auto-dependencies",
      "effect",
    ],
    question: "Чем watchEffect отличается от watch?",
    answers: [
      { id: "a", text: "watchEffect требует всегда указывать массив зависимостей" },
      { id: "b", text: "watchEffect работает только с CSS" },
      { id: "c", text: "watchEffect не запускается при создании" },
      { id: "d", text: "watchEffect сам собирает зависимости из выполняемой функции" },
    ],
    correctAnswer: "d",
    explanation: "watchEffect запускает функцию и автоматически отслеживает реактивные значения, которые были прочитаны во время выполнения. watch обычно получает явный источник наблюдения. watchEffect запускается сразу, поэтому вариант про отсутствие начального запуска неверен.",
    knowledgeId: "knowledge-reactivity-q112",
  },
  {
    id: 113,
    moduleId: "reactivity",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "dependency-tracking",
      "track",
      "trigger",
    ],
    question: "Что такое dependency tracking в реактивности Vue?",
    answers: [
      { id: "a", text: "Процесс запоминания, какие эффекты зависят от каких реактивных свойств" },
      { id: "b", text: "Список npm-зависимостей в package.json" },
      { id: "c", text: "Автоматическое удаление всех watchers после клика" },
      { id: "d", text: "Механизм сортировки CSS-классов по алфавиту" },
    ],
    correctAnswer: "a",
    explanation: "Dependency tracking — это сбор связей между реактивными свойствами и эффектами, которые их читают. Когда свойство меняется, Vue знает, какие эффекты нужно повторно выполнить. package.json, удаление watchers и сортировка классов к этому механизму не относятся.",
    knowledgeId: "knowledge-reactivity-q113",
  },
  {
    id: 114,
    moduleId: "reactivity",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "trigger",
      "effects",
      "updates",
    ],
    question: "Что означает trigger в контексте реактивности?",
    answers: [
      { id: "a", text: "Создание нового Vue-приложения" },
      { id: "b", text: "Уведомление зависимых эффектов после изменения реактивного свойства" },
      { id: "c", text: "Удаление Proxy-объекта из памяти" },
      { id: "d", text: "Автоматический импорт компонента" },
    ],
    correctAnswer: "b",
    explanation: "Trigger происходит после записи в реактивное свойство: Vue находит связанные эффекты и планирует их выполнение. Это часть пары track/trigger. Создание приложения, сборка импортов и управление памятью не являются смыслом trigger.",
    knowledgeId: "knowledge-reactivity-q114",
  },
  {
    id: 115,
    moduleId: "reactivity",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "effect",
      "render-effect",
      "reactivity",
    ],
    question: "Что такое effect в реактивной системе Vue?",
    answers: [
      { id: "a", text: "CSS-анимация перехода между страницами" },
      { id: "b", text: "Тип props только для строк" },
      { id: "c", text: "Функция, которая читает реактивные данные и может быть повторно запущена при их изменении" },
      { id: "d", text: "Метод для полного отключения virtual DOM" },
    ],
    correctAnswer: "c",
    explanation: "Effect — выполняемая функция, внутри которой читаются реактивные зависимости. Рендер компонента, computed и watchers опираются на похожую идею эффектов. CSS-анимации, типы props и отключение virtual DOM не описывают этот термин.",
    knowledgeId: "knowledge-reactivity-q115",
  },
  {
    id: 116,
    moduleId: "reactivity",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "proxy",
      "reactive",
      "javascript",
    ],
    question: "Почему Vue 3 использует Proxy для reactive?",
    answers: [
      { id: "a", text: "Proxy компилирует TypeScript быстрее" },
      { id: "b", text: "Proxy заменяет HTML-шаблоны строками" },
      { id: "c", text: "Proxy нужен только для localStorage" },
      { id: "d", text: "Proxy позволяет перехватывать чтение, запись и другие операции объекта" },
    ],
    correctAnswer: "d",
    explanation: "Proxy в JavaScript позволяет перехватывать операции с объектом, включая get и set. Это удобно для отслеживания зависимостей и запуска обновлений. Он не связан напрямую со скоростью TypeScript, заменой шаблонов или localStorage.",
    knowledgeId: "knowledge-reactivity-q116",
  },
  {
    id: 117,
    moduleId: "reactivity",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "reactive",
      "limitations",
      "replace-object",
    ],
    question: "Почему полная замена reactive-объекта может быть проблемой?",
    answers: [
      { id: "a", text: "Переменная может начать ссылаться на новый объект, а старые потребители останутся связаны со старым Proxy" },
      { id: "b", text: "Vue запрещает любые изменения свойств reactive-объекта" },
      { id: "c", text: "reactive работает только до первого клика пользователя" },
      { id: "d", text: "Proxy нельзя читать в template" },
    ],
    correctAnswer: "a",
    explanation: "Если переassign-ить переменную с reactive-объектом, старые ссылки на Proxy не обновятся автоматически. Обычно безопаснее менять свойства существующего объекта или использовать ref для заменяемой объектной ссылки. Vue разрешает изменение свойств reactive, а template может читать reactive-данные.",
    knowledgeId: "knowledge-reactivity-q117",
  },
  {
    id: 118,
    moduleId: "reactivity",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "reactive-array",
      "arrays",
      "mutation",
    ],
    question: "Что корректно сказать о реактивных массивах во Vue 3?",
    answers: [
      { id: "a", text: "Vue 3 не умеет отслеживать изменения массивов" },
      { id: "b", text: "Мутации вроде push и splice отслеживаются, если массив является reactive или лежит в ref" },
      { id: "c", text: "Массивы можно обновлять только через JSON.stringify" },
      { id: "d", text: "push всегда требует ручной вызов trigger() в компоненте" },
    ],
    correctAnswer: "b",
    explanation: "Vue 3 отслеживает операции с реактивными массивами, включая push, splice и изменение элементов. Ручной trigger в обычном компоненте не нужен. JSON.stringify не является способом обновления массива и не решает задачу реактивности.",
    knowledgeId: "knowledge-reactivity-q118",
  },
  {
    id: 119,
    moduleId: "reactivity",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "toRef",
      "props",
      "composables",
    ],
    question: "Что использовать, чтобы передать одно свойство reactive-объекта в composable и сохранить реактивность?",
    answers: [
      { id: "a", text: "JSON.parse(JSON.stringify(state.name))" },
      { id: "b", text: "Math.random() как key" },
      { id: "c", text: "toRef(state, \"name\")" },
      { id: "d", text: "readonly(\"name\") без связи с объектом" },
    ],
    correctAnswer: "c",
    explanation: "toRef создаёт ref, связанный с конкретным свойством reactive-объекта. Это удобно для передачи отдельного поля без потери связи. JSON-копирование связь разрушит, random key не относится к данным, а readonly строки не связывает значение с объектом.",
    knowledgeId: "knowledge-reactivity-q119",
  },
  {
    id: 120,
    moduleId: "reactivity",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "toRefs",
      "destructuring",
      "return-state",
    ],
    question: "Когда полезен toRefs?",
    answers: [
      { id: "a", text: "Когда нужно удалить все watchers" },
      { id: "b", text: "Когда нужно сделать объект нерендеримым" },
      { id: "c", text: "Когда нужно заменить Vue Router" },
      { id: "d", text: "Когда нужно деструктурировать reactive-объект и сохранить реактивность его свойств" },
    ],
    correctAnswer: "d",
    explanation: "toRefs превращает свойства reactive-объекта в связанные ref-значения. Это полезно при возвращении состояния из composable или при безопасной деструктуризации. Он не удаляет watchers, не отключает рендер и не связан с роутером.",
    knowledgeId: "knowledge-reactivity-q120",
  },
  {
    id: 121,
    moduleId: "reactivity",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "markRaw",
      "third-party",
      "performance",
    ],
    question: "Для чего может понадобиться markRaw?",
    answers: [
      { id: "a", text: "Чтобы исключить объект из реактивного преобразования" },
      { id: "b", text: "Чтобы сделать строку обязательным prop" },
      { id: "c", text: "Чтобы создать computed с setter" },
      { id: "d", text: "Чтобы очистить localStorage" },
    ],
    correctAnswer: "a",
    explanation: "markRaw помечает объект так, чтобы Vue не превращал его в реактивный Proxy. Это полезно для внешних инстансов, больших immutable-структур или объектов, где Proxy нежелателен. Props, computed setter и localStorage к markRaw не относятся.",
    knowledgeId: "knowledge-reactivity-q121",
  },
  {
    id: 122,
    moduleId: "reactivity",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "nextTick",
      "dom-update",
      "async-render",
    ],
    question: "Когда nextTick нужен при работе с реактивным состоянием и DOM?",
    answers: [
      { id: "a", text: "Когда нужно создать новый ref" },
      { id: "b", text: "Когда нужно дождаться применения DOM-обновлений после изменения реактивного состояния" },
      { id: "c", text: "Когда нужно запретить computed пересчитываться" },
      { id: "d", text: "Когда нужно сделать объект shallowReactive" },
    ],
    correctAnswer: "b",
    explanation: "Vue группирует обновления DOM асинхронно. nextTick позволяет дождаться, когда изменения состояния уже отразились в DOM. Он не создаёт ref, не управляет computed и не связан с shallowReactive.",
    knowledgeId: "knowledge-reactivity-q122",
  },
  {
    id: 123,
    moduleId: "reactivity",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "flush-timing",
      "watch",
      "scheduler",
    ],
    question: "Что описывает flush timing у watcher?",
    answers: [
      { id: "a", text: "Как быстро браузер скачает JavaScript bundle" },
      { id: "b", text: "Какой CSS transition выбрать для DOM" },
      { id: "c", text: "Когда callback watcher будет выполнен относительно обновления компонента" },
      { id: "d", text: "Какой id будет у следующего ref" },
    ],
    correctAnswer: "c",
    explanation: "flush timing управляет моментом выполнения watcher callback: до обновления DOM, после обновления или синхронно. Это важно, если callback читает DOM или должен выполниться строго в определённый момент. Загрузка bundle, CSS transition и id ref к flush timing не относятся.",
    knowledgeId: "knowledge-reactivity-q123",
  },
  {
    id: 124,
    moduleId: "reactivity",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "deep-watch",
      "nested-object",
      "watch",
    ],
    question: "Когда может понадобиться deep watch?",
    answers: [
      { id: "a", text: "Когда нужно сделать computed синхронным" },
      { id: "b", text: "Когда нужно отключить все события DOM" },
      { id: "c", text: "Когда нужно заменить ref на строку" },
      { id: "d", text: "Когда нужно реагировать на изменения вложенных свойств объекта" },
    ],
    correctAnswer: "d",
    explanation: "deep watch нужен, если watcher должен отслеживать изменения внутри вложенного объекта. Без deep наблюдение за объектной ссылкой может не сработать на изменение глубокого свойства. Но deep watch может быть дорогим, поэтому его не стоит использовать без необходимости.",
    knowledgeId: "knowledge-reactivity-q124",
  },
  {
    id: 125,
    moduleId: "reactivity",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "immediate-watch",
      "initial-load",
      "watch",
    ],
    question: "Для чего используют `immediate: true` в watch?",
    answers: [
      { id: "a", text: "Чтобы callback выполнился сразу при создании watcher, а затем при изменениях" },
      { id: "b", text: "Чтобы watcher перестал реагировать на изменения" },
      { id: "c", text: "Чтобы computed стал writable" },
      { id: "d", text: "Чтобы reactive перестал быть Proxy" },
    ],
    correctAnswer: "a",
    explanation: "`immediate: true` запускает callback watcher сразу, не дожидаясь первого изменения источника. Это удобно для первоначальной загрузки данных по текущему значению. Он не отключает watcher, не влияет на computed setter и не меняет природу reactive.",
    knowledgeId: "knowledge-reactivity-q125",
  },
  {
    id: 126,
    moduleId: "reactivity",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "readonly",
      "mutation",
      "warning",
    ],
    question: "Что произойдёт при попытке изменить readonly-объект?",
    answers: [
      { id: "a", text: "readonly автоматически превратится в reactive" },
      { id: "b", text: "Vue предупредит о недопустимой записи, а данные не должны изменяться через эту обёртку" },
      { id: "c", text: "Компонент удалится из DOM" },
      { id: "d", text: "Изменение станет глубже, чем у reactive" },
    ],
    correctAnswer: "b",
    explanation: "readonly предназначен для защиты от записи через эту обёртку. В dev-режиме Vue предупреждает о попытке мутации. Он не превращается в reactive автоматически и не удаляет компоненты из DOM.",
    knowledgeId: "knowledge-reactivity-q126",
  },
  {
    id: 127,
    moduleId: "reactivity",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "watchEffect",
      "dependencies",
      "cleanup",
    ],
    question: "Почему watchEffect может повторно выполниться после изменения ref, который читается внутри callback?",
    answers: [
      { id: "a", text: "Потому что watchEffect всегда запускается каждые 16 мс" },
      { id: "b", text: "Потому что ref нельзя читать внутри функций" },
      { id: "c", text: "Потому что watchEffect автоматически собрал этот ref как зависимость" },
      { id: "d", text: "Потому что Vue перезагружает страницу при изменении ref" },
    ],
    correctAnswer: "c",
    explanation: "watchEffect отслеживает реактивные значения, прочитанные во время выполнения callback. Если такой ref изменится, effect будет запланирован снова. Он не работает по таймеру, ref можно читать внутри функций, а Vue не перезагружает страницу из-за изменения ref.",
    knowledgeId: "knowledge-reactivity-q127",
  },
  {
    id: 128,
    moduleId: "reactivity",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "markRaw",
      "class-instance",
      "proxy",
    ],
    question: "При ревью кода с большим сторонним class-инстансом в reactive state что стоит проверить?",
    answers: [
      { id: "a", text: "Не нужно ли сделать каждый метод инстанса computed" },
      { id: "b", text: "Не нужно ли заменить class-инстанс строкой" },
      { id: "c", text: "Не нужно ли хранить его только в CSS-переменной" },
      { id: "d", text: "Не нужно ли исключить инстанс из реактивности через markRaw или shallowRef" },
    ],
    correctAnswer: "d",
    explanation: "Сторонние class-инстансы не всегда стоит проксировать: Proxy может быть лишним или конфликтовать с внутренней логикой библиотеки. markRaw или shallowRef помогают держать такой объект под контролем. computed, строка и CSS-переменная не решают проблему интеграции внешнего инстанса.",
    knowledgeId: "knowledge-reactivity-q128",
  },
  {
    id: 129,
    moduleId: "reactivity",
    type: "Interview",
    difficulty: "MiddlePlus",
    tags: [
      "unwrap-ref",
      "nested-ref",
      "template",
    ],
    question: "Что важно помнить про unwrap ref?",
    answers: [
      { id: "a", text: "Ref автоматически разворачивается в template, но в JavaScript-коде обычно нужен .value" },
      { id: "b", text: "Ref никогда не разворачивается во Vue" },
      { id: "c", text: "Unwrap ref означает удаление всех watchers" },
      { id: "d", text: "Unwrap ref работает только для CSS-файлов" },
    ],
    correctAnswer: "a",
    explanation: "В шаблоне Vue автоматически разворачивает ref, поэтому можно писать `{{ count }}`. В script setup при чтении и записи обычно нужен `count.value`. Это важная разница между template-синтаксисом и обычным JavaScript-кодом.",
    knowledgeId: "knowledge-reactivity-q129",
  },
  {
    id: 130,
    moduleId: "reactivity",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "watch",
      "performance",
      "deep-watch",
    ],
    question: "Почему deep watch не стоит включать без необходимости?",
    answers: [
      { id: "a", text: "Он отключает все computed в компоненте" },
      { id: "b", text: "Он может обходить вложенную структуру и быть дорогим для больших объектов" },
      { id: "c", text: "Он запрещает обновлять массивы" },
      { id: "d", text: "Он делает props обязательными" },
    ],
    correctAnswer: "b",
    explanation: "Deep watch отслеживает вложенные изменения и может требовать обхода сложной структуры. Для больших объектов это может быть дорого и приводить к лишним реакциям. Он не отключает computed, не запрещает массивы и не влияет на обязательность props.",
    knowledgeId: "knowledge-reactivity-q130",
  },
]
