import type { ContentQuestion } from '../../../types/content'

export const nuxtCoreQuestions: ContentQuestion[] = [
  {
    id: 901,
    moduleId: "nuxt-core",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "nuxt",
      "core",
      "framework",
    ],
    question: "Что такое Nuxt в контексте Vue-экосистемы?",
    answers: [
      { id: "a", text: "Фреймворк поверх Vue, который добавляет conventions, файловую маршрутизацию, конфигурацию и production-инструменты." },
      { id: "b", text: "Отдельный UI-kit для Vue с готовыми компонентами." },
      { id: "c", text: "Замена TypeScript для Vue-приложений." },
      { id: "d", text: "Библиотека только для управления глобальным состоянием." },
    ],
    correctAnswer: "a",
    explanation: "Nuxt строится поверх Vue и задаёт архитектурные conventions для разработки приложений. UI-kit, TypeScript и state management решают другие задачи: они не дают файловую маршрутизацию, структуру приложения и сборочный сценарий из коробки.",
    knowledgeId: "nuxt-core-901",
  },
  {
    id: 902,
    moduleId: "nuxt-core",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "nuxt",
      "history",
      "motivation",
    ],
    question: "Почему появился Nuxt?",
    answers: [
      { id: "a", text: "Чтобы полностью отказаться от компонентов Vue." },
      { id: "b", text: "Чтобы дать Vue-приложениям готовую архитектуру, маршрутизацию по файлам и единый production-пайплайн." },
      { id: "c", text: "Чтобы писать Vue только без сборщика." },
      { id: "d", text: "Чтобы заменить CSS и HTML собственным синтаксисом." },
    ],
    correctAnswer: "b",
    explanation: "Nuxt появился как способ убрать повторяющуюся инфраструктурную работу вокруг Vue-приложений. Компоненты Vue, HTML и CSS остаются основой интерфейса, а Nuxt добавляет conventions, routing, конфигурацию и команды для разработки и публикации.",
    knowledgeId: "nuxt-core-902",
  },
  {
    id: 903,
    moduleId: "nuxt-core",
    type: "Interview",
    difficulty: "Junior",
    tags: [
      "vue-spa",
      "nuxt",
      "comparison",
    ],
    question: "Как лучше кратко объяснить отличие Vue SPA от Nuxt на интервью?",
    answers: [
      { id: "a", text: "Nuxt не использует Vue-компоненты." },
      { id: "b", text: "Vue SPA всегда быстрее Nuxt при любом сценарии." },
      { id: "c", text: "Vue SPA обычно требует ручной настройки архитектуры, а Nuxt даёт opinionated-структуру и conventions поверх Vue." },
      { id: "d", text: "Nuxt подходит только для статичных HTML-страниц без интерактивности." },
    ],
    correctAnswer: "c",
    explanation: "Корректное отличие находится в уровне абстракции и готовой инфраструктуре. Nuxt не отменяет Vue-компоненты и интерактивность, а добавляет структуру проекта, маршрутизацию, конфигурацию и команды жизненного цикла приложения.",
    knowledgeId: "nuxt-core-903",
  },
  {
    id: 904,
    moduleId: "nuxt-core",
    type: "Architecture",
    difficulty: "Junior",
    tags: [
      "architecture",
      "decision",
      "nuxt",
    ],
    question: "Когда Nuxt обычно является удачным выбором?",
    answers: [
      { id: "a", text: "Когда нужен только один независимый виджет без маршрутов и общей структуры." },
      { id: "b", text: "Когда проект должен полностью отказаться от Vue." },
      { id: "c", text: "Когда достаточно одного HTML-файла без сборки." },
      { id: "d", text: "Когда приложению нужна понятная структура, маршруты по файлам, масштабируемые conventions и production-пайплайн." },
    ],
    correctAnswer: "d",
    explanation: "Nuxt хорошо работает там, где важны структура, маршруты, конфигурация и соглашения для команды. Для маленького изолированного виджета или простой статической страницы Nuxt может быть избыточным.",
    knowledgeId: "nuxt-core-904",
  },
  {
    id: 905,
    moduleId: "nuxt-core",
    type: "Interview",
    difficulty: "Junior",
    tags: [
      "decision",
      "tradeoffs",
      "nuxt",
    ],
    question: "В каком случае Nuxt может быть лишним?",
    answers: [
      { id: "a", text: "Когда нужен маленький встроенный Vue-виджет без маршрутов, layouts, конфигурации и отдельного build-процесса." },
      { id: "b", text: "Когда в проекте есть несколько страниц." },
      { id: "c", text: "Когда нужна единая структура папок." },
      { id: "d", text: "Когда команда хочет стандартизировать маршрутизацию." },
    ],
    correctAnswer: "a",
    explanation: "Nuxt добавляет архитектурный слой и поэтому должен окупаться задачей. Если интерфейс состоит из небольшого встроенного виджета, проще использовать Vue напрямую; наличие страниц и потребность в стандартах наоборот усиливают аргумент в пользу Nuxt.",
    knowledgeId: "nuxt-core-905",
  },
  {
    id: 906,
    moduleId: "nuxt-core",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "app.vue",
      "structure",
      "root",
    ],
    question: "Какую роль обычно выполняет файл app.vue в Nuxt?",
    answers: [
      { id: "a", text: "Он хранит все маршруты вручную в виде массива." },
      { id: "b", text: "Он задаёт корневую оболочку приложения и место, где отображается текущая страница через NuxtPage." },
      { id: "c", text: "Он заменяет nuxt.config.ts." },
      { id: "d", text: "Он нужен только для хранения глобальных CSS-переменных." },
    ],
    correctAnswer: "b",
    explanation: "app.vue находится на верхнем уровне интерфейса и часто содержит NuxtLayout или NuxtPage. Маршруты создаются по папке pages, конфигурация живёт в nuxt.config.ts, а стили лучше организовывать отдельно.",
    knowledgeId: "nuxt-core-906",
  },
  {
    id: 907,
    moduleId: "nuxt-core",
    type: "CodeOutput",
    difficulty: "Junior",
    tags: [
      "pages",
      "routing",
      "file-based-routing",
    ],
    question: "Какой маршрут создаст файл pages/index.vue?",
    answers: [
      { id: "a", text: "/index" },
      { id: "b", text: "/pages/index" },
      { id: "c", text: "/" },
      { id: "d", text: "/home/index" },
    ],
    correctAnswer: "c",
    explanation: "В файловой маршрутизации index.vue соответствует корню текущей папки. Поэтому pages/index.vue создаёт маршрут /, а не /index или путь с технической папкой pages.",
    knowledgeId: "nuxt-core-907",
  },
  {
    id: 908,
    moduleId: "nuxt-core",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "pages",
      "routing",
      "conventions",
    ],
    question: "Нужно добавить страницу /profile/settings. Какая структура pages наиболее естественна для Nuxt?",
    answers: [
      { id: "a", text: "routes/profile/settings.ts" },
      { id: "b", text: "components/ProfileSettings.vue" },
      { id: "c", text: "public/profile/settings.html" },
      { id: "d", text: "pages/profile/settings.vue" },
    ],
    correctAnswer: "d",
    explanation: "Nuxt строит маршруты по файлам внутри pages. Компоненты могут использоваться на странице, но сами по себе не создают route; public хранит статические файлы, а routes не является базовой convention Nuxt.",
    knowledgeId: "nuxt-core-908",
  },
  {
    id: 909,
    moduleId: "nuxt-core",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "layouts",
      "structure",
      "ui",
    ],
    question: "Когда стоит выносить оболочку страницы в layouts/default.vue?",
    answers: [
      { id: "a", text: "Когда несколько страниц должны иметь общий каркас: header, navigation, footer или общий page wrapper." },
      { id: "b", text: "Когда нужно скрыть всю бизнес-логику от TypeScript." },
      { id: "c", text: "Когда компонент используется только один раз внутри одной страницы." },
      { id: "d", text: "Когда нужно заменить папку pages." },
    ],
    correctAnswer: "a",
    explanation: "Layouts предназначены для повторяемой структуры страниц. Они не заменяют pages и не решают типизацию; их задача — убрать дублирование общих shell-элементов и сохранить страницы сфокусированными на содержимом.",
    knowledgeId: "nuxt-core-909",
  },
  {
    id: 910,
    moduleId: "nuxt-core",
    type: "FindBug",
    difficulty: "JuniorPlus",
    tags: [
      "components",
      "auto-imports",
      "bug",
    ],
    question: "Компонент AppHeader.vue лежит в components/, но разработчик вручную регистрирует его глобально в plugin. В чём проблема подхода?",
    answers: [
      { id: "a", text: "Компоненты в Nuxt нельзя хранить в папке components." },
      { id: "b", text: "Это дублирует стандартный auto import Nuxt и усложняет поддержку без необходимости." },
      { id: "c", text: "Компоненты Nuxt должны лежать только в public." },
      { id: "d", text: "AppHeader.vue не может использовать template." },
    ],
    correctAnswer: "b",
    explanation: "Nuxt умеет автоматически импортировать компоненты из components. Ручная глобальная регистрация через plugin может быть нужна в редких случаях, но для обычного компонента она создаёт лишний слой и увеличивает риск рассинхронизации.",
    knowledgeId: "nuxt-core-910",
  },
  {
    id: 911,
    moduleId: "nuxt-core",
    type: "CodeReview",
    difficulty: "JuniorPlus",
    tags: [
      "composables",
      "structure",
      "code-review",
    ],
    question: "На code review обнаружена функция useCartState в components/ProductCard.vue. Что лучше предложить?",
    answers: [
      { id: "a", text: "Переименовать компонент в useCartState.vue." },
      { id: "b", text: "Перенести всю страницу в public." },
      { id: "c", text: "Вынести переиспользуемую Composition API-логику в composables/useCartState.ts." },
      { id: "d", text: "Хранить composable в nuxt.config.ts." },
    ],
    correctAnswer: "c",
    explanation: "Папка composables предназначена для переиспользуемой логики и auto import. Хранение такой функции внутри конкретного компонента привязывает её к UI и мешает повторному использованию.",
    knowledgeId: "nuxt-core-911",
  },
  {
    id: 912,
    moduleId: "nuxt-core",
    type: "CodeReview",
    difficulty: "JuniorPlus",
    tags: [
      "assets",
      "public",
      "structure",
    ],
    question: "Картинка logo.svg должна обрабатываться сборщиком и импортироваться в компонент. Где ей лучше находиться?",
    answers: [
      { id: "a", text: "В public/, потому что все изображения всегда должны быть только там." },
      { id: "b", text: "В middleware/, потому что это ресурс приложения." },
      { id: "c", text: "В pages/, чтобы создать маршрут изображения." },
      { id: "d", text: "В assets/, потому что файл должен пройти через Vite pipeline." },
    ],
    correctAnswer: "d",
    explanation: "assets подходит для файлов, которые импортируются в код и обрабатываются сборщиком. public лучше использовать для статических файлов, доступных по прямому URL без трансформации.",
    knowledgeId: "nuxt-core-912",
  },
  {
    id: 913,
    moduleId: "nuxt-core",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "middleware",
      "navigation",
    ],
    question: "Что описывает файл middleware/auth.ts в базовой структуре Nuxt?",
    answers: [
      { id: "a", text: "Навигационную проверку, которую можно подключить к странице или маршруту." },
      { id: "b", text: "Глобальный CSS-файл для страницы авторизации." },
      { id: "c", text: "Компонент формы логина." },
      { id: "d", text: "Конфигурацию dev-сервера Vite." },
    ],
    correctAnswer: "a",
    explanation: "Route middleware отвечает за проверки при навигации, например доступ к странице. CSS, компоненты и Vite-конфигурация находятся в других частях структуры и не являются задачей middleware.",
    knowledgeId: "nuxt-core-913",
  },
  {
    id: 914,
    moduleId: "nuxt-core",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "plugins",
      "dayjs",
      "structure",
    ],
    question: "Нужно один раз подключить и настроить dayjs для всего Nuxt-приложения. Куда логичнее поместить код?",
    answers: [
      { id: "a", text: "В каждую страницу pages вручную." },
      { id: "b", text: "В plugins/dayjs.ts." },
      { id: "c", text: "В public/dayjs.ts." },
      { id: "d", text: "В layouts только как CSS-класс." },
    ],
    correctAnswer: "b",
    explanation: "Plugins подходят для одноразовой инициализации библиотек и предоставления общих возможностей приложению. Распределение одинаковой настройки по страницам создаёт дублирование и усложняет сопровождение.",
    knowledgeId: "nuxt-core-914",
  },
  {
    id: 915,
    moduleId: "nuxt-core",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "nuxt.config",
      "configuration",
    ],
    question: "Что обычно должно находиться в nuxt.config.ts?",
    answers: [
      { id: "a", text: "Содержимое всех страниц приложения." },
      { id: "b", text: "Результаты API-запросов пользователя." },
      { id: "c", text: "Конфигурация Nuxt: modules, css, runtimeConfig, aliases, настройки app и build-поведения." },
      { id: "d", text: "Только стили отдельных компонентов." },
    ],
    correctAnswer: "c",
    explanation: "nuxt.config.ts — центральная точка конфигурации фреймворка. Страницы, пользовательские данные и scoped styles не должны смешиваться с конфигом, иначе проект теряет предсказуемую структуру.",
    knowledgeId: "nuxt-core-915",
  },
  {
    id: 916,
    moduleId: "nuxt-core",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "runtimeConfig",
      "configuration",
      "security",
    ],
    question: "Какое значение из runtimeConfig безопаснее считать доступным на клиенте?",
    answers: [
      { id: "a", text: "Любое значение runtimeConfig всегда публично." },
      { id: "b", text: "Только значение, записанное в private." },
      { id: "c", text: "Никакое значение runtimeConfig не может быть прочитано в коде." },
      { id: "d", text: "Только значение внутри public." },
    ],
    correctAnswer: "d",
    explanation: "В Nuxt публичная часть runtimeConfig явно помещается в public. Значения вне public предназначены для приватной конфигурации и не должны рассматриваться как клиентские настройки.",
    knowledgeId: "nuxt-core-916",
  },
  {
    id: 917,
    moduleId: "nuxt-core",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "app.config",
      "runtimeConfig",
      "configuration",
    ],
    question: "Чем app.config.ts концептуально отличается от runtimeConfig?",
    answers: [
      { id: "a", text: "app.config.ts подходит для реактивной конфигурации приложения, а runtimeConfig — для значений окружения и runtime-настроек." },
      { id: "b", text: "app.config.ts нужен только для маршрутов, а runtimeConfig только для CSS." },
      { id: "c", text: "Оба файла всегда полностью взаимозаменяемы." },
      { id: "d", text: "runtimeConfig нельзя типизировать и читать из кода." },
    ],
    correctAnswer: "a",
    explanation: "app.config.ts описывает конфигурацию уровня приложения, которую удобно читать в UI. runtimeConfig чаще связан с окружением и публичными/приватными значениями; смешивание этих задач делает настройки менее понятными.",
    knowledgeId: "nuxt-core-917",
  },
  {
    id: 918,
    moduleId: "nuxt-core",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "auto-imports",
      "developer-experience",
    ],
    question: "Что означает auto imports в Nuxt?",
    answers: [
      { id: "a", text: "Nuxt автоматически скачивает любые npm-пакеты при первом использовании." },
      { id: "b", text: "Nuxt может автоматически импортировать компоненты, composables и некоторые utilities из стандартных папок." },
      { id: "c", text: "Nuxt удаляет необходимость понимать зависимости модуля." },
      { id: "d", text: "Nuxt запрещает явные import-выражения." },
    ],
    correctAnswer: "b",
    explanation: "Auto imports сокращают шаблонный код для стандартных сущностей Nuxt. Это не заменяет понимание зависимостей и не означает автоматическую установку пакетов; явные imports всё ещё допустимы там, где они делают код яснее.",
    knowledgeId: "nuxt-core-918",
  },
  {
    id: 919,
    moduleId: "nuxt-core",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "aliases",
      "architecture",
      "imports",
    ],
    question: "Зачем в Nuxt используются aliases вроде ~/ или @/?",
    answers: [
      { id: "a", text: "Чтобы скрыть ошибки TypeScript." },
      { id: "b", text: "Чтобы все файлы автоматически стали глобальными." },
      { id: "c", text: "Чтобы импортировать файлы от корня проекта без хрупких цепочек ../../." },
      { id: "d", text: "Чтобы заменить файловую маршрутизацию." },
    ],
    correctAnswer: "c",
    explanation: "Aliases улучшают читаемость импортов и устойчивость структуры при переносе файлов. Они не отключают типизацию, не делают всё глобальным и не связаны напрямую с генерацией маршрутов.",
    knowledgeId: "nuxt-core-919",
  },
  {
    id: 920,
    moduleId: "nuxt-core",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "file-based-routing",
      "conventions",
      "architecture",
    ],
    question: "Какой главный плюс файловой маршрутизации в Nuxt?",
    answers: [
      { id: "a", text: "Все маршруты становятся недоступными для lazy loading." },
      { id: "b", text: "Каждая страница обязана быть глобальным компонентом." },
      { id: "c", text: "URL перестают зависеть от структуры проекта." },
      { id: "d", text: "Структура URL становится видна по дереву файлов, и команда меньше пишет ручной router-конфигурации." },
    ],
    correctAnswer: "d",
    explanation: "Файловая маршрутизация делает route map очевидной и снижает количество ручной конфигурации. Она не отменяет lazy loading и не превращает страницы в глобальные компоненты.",
    knowledgeId: "nuxt-core-920",
  },
  {
    id: 921,
    moduleId: "nuxt-core",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "cli",
      "commands",
      "workflow",
    ],
    question: "Какой порядок CLI-команд наиболее типичен для проверки production-сборки локально?",
    answers: [
      { id: "a", text: "npm run build, затем npm run preview." },
      { id: "b", text: "npm run preview, затем create-nuxt." },
      { id: "c", text: "npm run generate, затем npm run dev для проверки build-артефакта." },
      { id: "d", text: "npm run dev достаточно для полной проверки production-сборки." },
    ],
    correctAnswer: "a",
    explanation: "build создаёт production-артефакт, а preview позволяет проверить его локально. dev предназначен для разработки, create-nuxt — для создания проекта, а generate решает отдельный сценарий статической генерации.",
    knowledgeId: "nuxt-core-921",
  },
  {
    id: 922,
    moduleId: "nuxt-core",
    type: "Theory",
    difficulty: "MiddlePlus",
    tags: [
      "create-nuxt",
      "cli",
      "project-start",
    ],
    question: "Что делает create-nuxt?",
    answers: [
      { id: "a", text: "Запускает production-сервер уже существующего проекта." },
      { id: "b", text: "Создаёт стартовый Nuxt-проект с базовой структурой и настройками." },
      { id: "c", text: "Автоматически пишет все страницы приложения." },
      { id: "d", text: "Заменяет необходимость в package manager." },
    ],
    correctAnswer: "b",
    explanation: "create-nuxt нужен на этапе старта проекта: он подготавливает шаблон и зависимости. Для разработки, сборки и проверки используются отдельные команды вроде dev, build и preview.",
    knowledgeId: "nuxt-core-922",
  },
  {
    id: 923,
    moduleId: "nuxt-core",
    type: "CodeOutput",
    difficulty: "MiddlePlus",
    tags: [
      "cli",
      "generate",
      "preview",
    ],
    question: "Какая команда обычно проверяет уже собранное Nuxt-приложение локально?",
    answers: [
      { id: "a", text: "npm run dev" },
      { id: "b", text: "npx create-nuxt" },
      { id: "c", text: "npm run preview" },
      { id: "d", text: "npm install" },
    ],
    correctAnswer: "c",
    explanation: "preview запускает локальный просмотр production-сборки после build. dev запускает dev-сервер с hot reload, create-nuxt создаёт проект, а npm install устанавливает зависимости. На собеседовании важно различать режим разработки и проверку production output: preview ближе к тому, что будет отдано после сборки.",
    knowledgeId: "nuxt-core-923",
  },
  {
    id: 924,
    moduleId: "nuxt-core",
    type: "FindBug",
    difficulty: "MiddlePlus",
    tags: [
      "generate",
      "build",
      "deployment",
    ],
    question: "Разработчик считает, что generate всегда является заменой build для любого Nuxt-приложения. Что неверно?",
    answers: [
      { id: "a", text: "build никогда не нужен в Nuxt." },
      { id: "b", text: "generate используется только для установки зависимостей." },
      { id: "c", text: "build создаёт только документацию." },
      { id: "d", text: "generate относится к статической генерации и подходит не для каждого deployment-сценария." },
    ],
    correctAnswer: "d",
    explanation: "generate и build решают разные задачи. Статическая генерация хороша для определённых типов сайтов, но production-сценарий нужно выбирать по архитектуре и требованиям размещения.",
    knowledgeId: "nuxt-core-924",
  },
  {
    id: 925,
    moduleId: "nuxt-core",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "large-projects",
      "structure",
      "code-review",
    ],
    question: "В большом Nuxt-проекте все компоненты, composables и helpers лежат в одной папке shared/. Что стоит отметить на review?",
    answers: [
      { id: "a", text: "Такой слой быстро становится свалкой; лучше разделять код по назначению и доменным модулям." },
      { id: "b", text: "Nuxt запрещает создавать любые папки кроме pages." },
      { id: "c", text: "Все helpers должны быть страницами." },
      { id: "d", text: "Composables нельзя выносить из компонентов." },
    ],
    correctAnswer: "a",
    explanation: "Для большого проекта важна навигация по смыслу: components, composables, utils и feature/domain-модули должны иметь понятные границы. Общая папка без правил снижает discoverability и усложняет сопровождение.",
    knowledgeId: "nuxt-core-925",
  },
  {
    id: 926,
    moduleId: "nuxt-core",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "modules",
      "architecture",
      "organization",
    ],
    question: "Команда добавляет новый доменный раздел и кладёт все файлы только в pages. Что лучше предложить?",
    answers: [
      { id: "a", text: "Удалить pages и описывать все маршруты вручную." },
      { id: "b", text: "Оставить в pages только route-level файлы, а доменную логику разнести по components, composables, utils или feature-папкам." },
      { id: "c", text: "Перенести nuxt.config.ts в pages." },
      { id: "d", text: "Дублировать один и тот же код в каждой странице." },
    ],
    correctAnswer: "b",
    explanation: "pages должны собирать экран и route-level поведение, а не становиться местом для всей логики. Такое разделение снижает размер страниц и упрощает повторное использование кода.",
    knowledgeId: "nuxt-core-926",
  },
  {
    id: 927,
    moduleId: "nuxt-core",
    type: "BestPractice",
    difficulty: "MiddlePlus",
    tags: [
      "conventions",
      "best-practices",
    ],
    question: "Что является хорошей практикой при работе с conventions Nuxt?",
    answers: [
      { id: "a", text: "Переименовывать стандартные папки без причины." },
      { id: "b", text: "Хранить всю конфигурацию в компонентах." },
      { id: "c", text: "Следовать стандартным папкам Nuxt и документировать отклонения, если они действительно нужны." },
      { id: "d", text: "Создавать собственный router-layer для каждого маршрута." },
    ],
    correctAnswer: "c",
    explanation: "Сила Nuxt в предсказуемых соглашениях: они уменьшают количество ручной инфраструктуры и делают проект понятнее для команды. Осознанные отклонения возможны, но они должны решать конкретную проблему и быть задокументированы. Если игнорировать conventions без причины, код становится менее Nuxt-like и сложнее поддерживается.",
    knowledgeId: "nuxt-core-927",
  },
  {
    id: 928,
    moduleId: "nuxt-core",
    type: "FindBug",
    difficulty: "MiddlePlus",
    tags: [
      "anti-patterns",
      "conventions",
      "maintenance",
    ],
    question: "Какой anti-pattern чаще всего ухудшает Nuxt-проект на ранней стадии?",
    answers: [
      { id: "a", text: "Использовать pages для маршрутов." },
      { id: "b", text: "Создавать layouts для повторяемой оболочки." },
      { id: "c", text: "Держать публичные настройки в public runtimeConfig." },
      { id: "d", text: "Бороться с conventions Nuxt и строить параллельную архитектуру без явной причины." },
    ],
    correctAnswer: "d",
    explanation: "Если стандартные conventions заменяются самодельными слоями без необходимости, проект теряет главный выигрыш Nuxt. Остальные варианты являются нормальными практиками при корректном применении.",
    knowledgeId: "nuxt-core-928",
  },
  {
    id: 929,
    moduleId: "nuxt-core",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "architecture-boundaries",
      "nuxt-core",
      "interview",
    ],
    question: "Как на Senior-интервью корректно провести границу между Nuxt Core, SSR, Nitro и Server API?",
    answers: [
      { id: "a", text: "Nuxt Core задаёт структуру и conventions, а SSR, Nitro и Server API являются отдельными слоями, которые изучаются поверх этой базы." },
      { id: "b", text: "Это одно и то же, поэтому граница не нужна." },
      { id: "c", text: "Nuxt Core состоит только из Server API." },
      { id: "d", text: "SSR заменяет pages, layouts и nuxt.config.ts." },
    ],
    correctAnswer: "a",
    explanation: "Базовый Nuxt нужно понимать как framework shell: структура, конфигурация, маршруты, CLI и conventions. SSR, Nitro и Server API важны, но они не отменяют core-слой и должны разбираться как отдельные темы.",
    knowledgeId: "nuxt-core-929",
  },
  {
    id: 930,
    moduleId: "nuxt-core",
    type: "Architecture",
    difficulty: "Senior",
    tags: [
      "scaling",
      "architecture",
      "large-projects",
    ],
    question: "Какой подход лучше масштабирует Nuxt-проект с десятками страниц?",
    answers: [
      { id: "a", text: "Каждая страница копирует одинаковую навигацию, запросы и форматирование." },
      { id: "b", text: "Route-level pages остаются тонкими, общие оболочки живут в layouts, а доменная логика группируется в feature-модулях." },
      { id: "c", text: "Все компоненты объявляются внутри app.vue." },
      { id: "d", text: "Файловая маршрутизация отключается ради ручного массива на тысячу строк." },
    ],
    correctAnswer: "b",
    explanation: "Тонкие pages и понятные domain boundaries помогают проекту расти без хаоса. Дублирование, огромный app.vue и монолитная ручная конфигурация маршрутов ухудшают поддержку.",
    knowledgeId: "nuxt-core-930",
  },
  {
    id: 931,
    moduleId: "nuxt-core",
    type: "BestPractice",
    difficulty: "Senior",
    tags: [
      "runtimeConfig",
      "security",
      "best-practices",
    ],
    question: "Какая практика безопаснее при работе с runtimeConfig?",
    answers: [
      { id: "a", text: "Помещать все переменные окружения в public для удобства." },
      { id: "b", text: "Хранить секреты в app.config.ts, чтобы их было проще читать из UI." },
      { id: "c", text: "Явно отделять public-настройки от приватных значений и не раскрывать секреты клиентскому коду." },
      { id: "d", text: "Дублировать ключи в каждом компоненте." },
    ],
    correctAnswer: "c",
    explanation: "runtimeConfig требует дисциплины: публичное должно быть явно публичным, приватное не должно попадать в клиентский код. Удобство доступа не важнее границы безопасности.",
    knowledgeId: "nuxt-core-931",
  },
  {
    id: 932,
    moduleId: "nuxt-core",
    type: "Scenario",
    difficulty: "Senior",
    tags: [
      "decision-making",
      "architecture",
      "product",
    ],
    question: "Команда делает продуктовый сайт с десятками страниц, общей навигацией, разными layouts и долгим жизненным циклом. Какой аргумент в пользу Nuxt самый сильный?",
    answers: [
      { id: "a", text: "Nuxt гарантирует отсутствие архитектурных решений." },
      { id: "b", text: "Nuxt запрещает использовать Vue-компоненты." },
      { id: "c", text: "Nuxt подходит только для одноразовых прототипов." },
      { id: "d", text: "Nuxt уменьшает инфраструктурные решения за счёт conventions и даёт устойчивую структуру для роста." },
    ],
    correctAnswer: "d",
    explanation: "В долгоживущем продукте ценны предсказуемость и снижение повторной инфраструктурной работы. Nuxt не отменяет архитектурные решения, но задаёт сильную основу для маршрутов, layouts, конфигурации и структуры.",
    knowledgeId: "nuxt-core-932",
  },
  {
    id: 933,
    moduleId: "nuxt-core",
    type: "FindBug",
    difficulty: "Senior",
    tags: [
      "plugins",
      "environment",
      "bug",
    ],
    question: "Плагин обращается к window без проверки среды и падает при сборке. Какой вывод наиболее точный?",
    answers: [
      { id: "a", text: "Код плагина должен учитывать среду выполнения; browser-only логику нужно изолировать." },
      { id: "b", text: "В Nuxt нельзя писать plugins." },
      { id: "c", text: "Любой plugin всегда выполняется только в браузере." },
      { id: "d", text: "Проблема решается переносом файла в public." },
    ],
    correctAnswer: "a",
    explanation: "Nuxt-плагины требуют понимания среды выполнения. Даже без глубокого разбора SSR важно не писать browser API так, будто они доступны везде; browser-only код должен быть явно ограничен.",
    knowledgeId: "nuxt-core-933",
  },
  {
    id: 934,
    moduleId: "nuxt-core",
    type: "Architecture",
    difficulty: "Senior",
    tags: [
      "auto-imports",
      "governance",
      "architecture",
    ],
    question: "Как управлять auto imports в большой команде?",
    answers: [
      { id: "a", text: "Запретить все imports и хранить каждую функцию глобально." },
      { id: "b", text: "Договориться о нейминге, границах папок и случаях, где явный import повышает читаемость." },
      { id: "c", text: "Создавать одинаковые composables с разными именами в каждом разделе." },
      { id: "d", text: "Не документировать источники auto-imported сущностей." },
    ],
    correctAnswer: "b",
    explanation: "Auto imports ускоряют разработку, но в большой кодовой базе требуют дисциплины. Нейминг и границы владения помогают не превратить удобство в скрытую зависимость.",
    knowledgeId: "nuxt-core-934",
  },
  {
    id: 935,
    moduleId: "nuxt-core",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "interview",
      "foundation",
      "nuxt-core",
    ],
    question: "Что важно подчеркнуть, объясняя Nuxt Core как фундамент для следующих тем?",
    answers: [
      { id: "a", text: "Nuxt Core полностью заменяет необходимость изучать Vue." },
      { id: "b", text: "Достаточно выучить одну команду dev." },
      { id: "c", text: "Без понимания структуры, conventions, CLI и конфигурации сложнее осознанно изучать SSR, Nitro и Server API." },
      { id: "d", text: "Файлы проекта не влияют на архитектуру Nuxt." },
    ],
    correctAnswer: "c",
    explanation: "Nuxt Core задаёт язык, на котором дальше обсуждаются более сложные слои. Если не понимать pages, layouts, plugins, runtimeConfig и CLI, следующие темы воспринимаются как набор несвязанных деталей.",
    knowledgeId: "nuxt-core-935",
  },
]
