import type { ContentQuestion } from '../../../types/content'

export const ssrHydrationQuestions: ContentQuestion[] = [
  {
    id: 1101,
    moduleId: "ssr-hydration",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "ssr",
      "rendering",
      "nuxt",
    ],
    question: "Что такое SSR в Nuxt?",
    answers: [
      { id: "a", text: "Рендеринг HTML на сервере перед отправкой страницы браузеру." },
      { id: "b", text: "Рендеринг только после клика пользователя в браузере." },
      { id: "c", text: "Хранение всех данных в localStorage." },
      { id: "d", text: "Замена Vue-компонентов на обычные HTML-файлы без JavaScript." },
    ],
    correctAnswer: "a",
    explanation: "SSR формирует начальный HTML на сервере, поэтому браузер получает уже готовую разметку. CSR строит интерфейс в браузере после загрузки JavaScript, localStorage и отказ от Vue-компонентов к SSR не относятся.",
    knowledgeId: "ssr-hydration-1101",
  },
  {
    id: 1102,
    moduleId: "ssr-hydration",
    type: "Interview",
    difficulty: "Junior",
    tags: [
      "csr",
      "ssr",
      "interview",
    ],
    question: "Как кратко объяснить отличие CSR от SSR на интервью?",
    answers: [
      { id: "a", text: "CSR всегда не использует JavaScript, а SSR всегда не использует сервер." },
      { id: "b", text: "CSR строит HTML в браузере, SSR отдаёт начальный HTML с сервера и затем гидратирует его на клиенте." },
      { id: "c", text: "SSR нужен только для CSS, а CSR только для API." },
      { id: "d", text: "Между CSR и SSR нет архитектурной разницы." },
    ],
    correctAnswer: "b",
    explanation: "Главное отличие — где появляется начальная разметка. SSR улучшает первый HTML-ответ и может помочь SEO/FCP, а CSR переносит рендеринг начального состояния в браузер.",
    knowledgeId: "ssr-hydration-1102",
  },
  {
    id: 1103,
    moduleId: "ssr-hydration",
    type: "Scenario",
    difficulty: "Junior",
    tags: [
      "ssg",
      "architecture",
      "rendering",
    ],
    question: "Сайт содержит редко меняющиеся публичные статьи. Какой rendering strategy часто подходит?",
    answers: [
      { id: "a", text: "Только CSR, потому что статьи нельзя рендерить заранее." },
      { id: "b", text: "Только browser-only rendering через ClientOnly." },
      { id: "c", text: "SSG, потому что страницы можно заранее сгенерировать и быстро отдавать." },
      { id: "d", text: "Хранение всех статей в cookies." },
    ],
    correctAnswer: "c",
    explanation: "SSG хорошо подходит для публичного контента, который редко меняется. CSR и ClientOnly могут ухудшить первичную загрузку и SEO, а cookies не являются стратегией рендеринга.",
    knowledgeId: "ssr-hydration-1103",
  },
  {
    id: 1104,
    moduleId: "ssr-hydration",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "hydration",
      "vue",
      "nuxt",
    ],
    question: "Что такое hydration?",
    answers: [
      { id: "a", text: "Удаление всего серверного HTML перед запуском приложения." },
      { id: "b", text: "Кеширование CSS-файлов в браузере." },
      { id: "c", text: "Автоматическая установка npm-пакетов." },
      { id: "d", text: "Процесс, в котором клиентский Vue подключается к HTML, уже сгенерированному сервером." },
    ],
    correctAnswer: "d",
    explanation: "Hydration делает серверный HTML интерактивным: Vue сопоставляет виртуальное дерево с существующей DOM-разметкой и подключает обработчики. Удаление HTML или кеширование CSS не описывает hydration.",
    knowledgeId: "ssr-hydration-1104",
  },
  {
    id: 1105,
    moduleId: "ssr-hydration",
    type: "FindBug",
    difficulty: "JuniorPlus",
    tags: [
      "window",
      "browser-api",
      "ssr",
    ],
    question: "Компонент обращается к window.innerWidth прямо в setup и падает при SSR. В чём причина?",
    answers: [
      { id: "a", text: "window существует только в браузере, а setup может выполняться на сервере." },
      { id: "b", text: "window запрещён во всех Vue-компонентах." },
      { id: "c", text: "SSR не поддерживает TypeScript." },
      { id: "d", text: "innerWidth можно читать только из CSS." },
    ],
    correctAnswer: "a",
    explanation: "Во время SSR код выполняется в серверной среде, где нет browser APIs. window, document, localStorage и navigator нужно читать только на клиенте или через безопасные composables.",
    knowledgeId: "ssr-hydration-1105",
  },
  {
    id: 1106,
    moduleId: "ssr-hydration",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "client-only",
      "browser-api",
      "best-practice",
    ],
    question: "Что лучше сделать с компонентом, который полностью зависит от browser-only библиотеки?",
    answers: [
      { id: "a", text: "Оставить прямой доступ к document в setup." },
      { id: "b", text: "Изолировать его через ClientOnly или client-only загрузку, если серверный HTML невозможен." },
      { id: "c", text: "Перенести библиотеку в runtimeConfig.public." },
      { id: "d", text: "Отключить TypeScript." },
    ],
    correctAnswer: "b",
    explanation: "Если библиотека принципиально требует DOM, её нужно ограничить клиентской средой. Прямой document в SSR-коде вызывает ошибки, а runtimeConfig и TypeScript не решают проблему среды выполнения.",
    knowledgeId: "ssr-hydration-1106",
  },
  {
    id: 1107,
    moduleId: "ssr-hydration",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "import.meta.server",
      "server-client",
    ],
    question: "Какое значение вернёт import.meta.server во время серверного рендера?",
    answers: [
      { id: "a", text: "false" },
      { id: "b", text: "undefined всегда" },
      { id: "c", text: "true" },
      { id: "d", text: "Строку \"server\"" },
    ],
    correctAnswer: "c",
    explanation: "В Nuxt import.meta.server равен true в серверной среде. На клиенте true будет import.meta.client, поэтому такие флаги используют для безопасного разделения кода по средам.",
    knowledgeId: "ssr-hydration-1107",
  },
  {
    id: 1108,
    moduleId: "ssr-hydration",
    type: "Interview",
    difficulty: "JuniorPlus",
    tags: [
      "seo",
      "ssr",
      "benefits",
    ],
    question: "Почему SSR может помочь SEO?",
    answers: [
      { id: "a", text: "SSR автоматически покупает внешние ссылки." },
      { id: "b", text: "SSR удаляет необходимость в title и meta." },
      { id: "c", text: "SEO зависит только от цвета интерфейса." },
      { id: "d", text: "Поисковый бот получает содержательный HTML уже в первом ответе." },
    ],
    correctAnswer: "d",
    explanation: "SSR может дать crawler-у готовый HTML с контентом. Это не заменяет метаданные, контентную стратегию и качество страницы, но улучшает доступность начального содержимого.",
    knowledgeId: "ssr-hydration-1108",
  },
  {
    id: 1109,
    moduleId: "ssr-hydration",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "spa",
      "architecture",
      "rendering-choice",
    ],
    question: "Внутренний admin tool доступен только после логина и почти не нуждается в SEO. Что может быть разумным выбором?",
    answers: [
      { id: "a", text: "SPA/CSR или ограниченный SSR, если преимущества SSR не окупают сложность." },
      { id: "b", text: "SSR обязателен для любой страницы без исключений." },
      { id: "c", text: "SSG обязателен для приватных dashboards." },
      { id: "d", text: "Hydration нужно полностью отключить." },
    ],
    correctAnswer: "a",
    explanation: "Приватные инструменты часто не требуют SEO и могут выигрывать от простоты CSR. SSR имеет стоимость: серверная нагрузка, hydration, browser API-ограничения и потенциальные mismatch.",
    knowledgeId: "ssr-hydration-1109",
  },
  {
    id: 1110,
    moduleId: "ssr-hydration",
    type: "CodeReview",
    difficulty: "JuniorPlus",
    tags: [
      "localStorage",
      "code-review",
      "ssr",
    ],
    question: "На review в setup найден код const theme = localStorage.getItem(\"theme\"). Что нужно исправить?",
    answers: [
      { id: "a", text: "Оставить как есть, localStorage есть на сервере." },
      { id: "b", text: "Читать localStorage только на клиенте, например в onMounted или под import.meta.client." },
      { id: "c", text: "Перенести localStorage в nuxt.config.ts." },
      { id: "d", text: "Заменить localStorage на Math.random()." },
    ],
    correctAnswer: "b",
    explanation: "localStorage — browser API. При SSR setup может выполняться на сервере, поэтому прямой доступ приведёт к ошибке. Клиентское чтение нужно изолировать.",
    knowledgeId: "ssr-hydration-1110",
  },
  {
    id: 1111,
    moduleId: "ssr-hydration",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "universal-rendering",
      "nuxt",
      "ssr",
    ],
    question: "Что означает Universal Rendering в Nuxt?",
    answers: [
      { id: "a", text: "Код выполняется только в браузере." },
      { id: "b", text: "Код выполняется только в базе данных." },
      { id: "c", text: "Один Vue-код участвует в серверном рендере начального HTML и затем продолжает работать на клиенте." },
      { id: "d", text: "Каждый компонент обязан быть ClientOnly." },
    ],
    correctAnswer: "c",
    explanation: "Universal Rendering означает, что часть кода должна быть безопасной для серверной и клиентской среды. Поэтому важно не обращаться к browser APIs без проверки среды.",
    knowledgeId: "ssr-hydration-1111",
  },
  {
    id: 1112,
    moduleId: "ssr-hydration",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "hydration-mismatch",
      "Math.random",
      "bug",
    ],
    question: "В template выводится {{ Math.random() }}. Почему это опасно для SSR?",
    answers: [
      { id: "a", text: "Math.random недоступен в браузере." },
      { id: "b", text: "Vue запрещает интерполяции." },
      { id: "c", text: "SSR всегда отключает JavaScript." },
      { id: "d", text: "Сервер и клиент могут получить разные значения, что приведёт к hydration mismatch." },
    ],
    correctAnswer: "d",
    explanation: "Hydration ожидает, что серверная и клиентская разметка совпадут. Случайное значение может отличаться при серверном рендере и клиентской hydration, поэтому появляется mismatch.",
    knowledgeId: "ssr-hydration-1112",
  },
  {
    id: 1113,
    moduleId: "ssr-hydration",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "Date.now",
      "hydration-mismatch",
    ],
    question: "Что вероятнее всего случится, если в SSR-разметке напрямую вывести Date.now()?",
    answers: [
      { id: "a", text: "Серверное и клиентское значение могут отличиться, вызвав hydration mismatch." },
      { id: "b", text: "Дата всегда будет одинаковой на сервере и клиенте." },
      { id: "c", text: "Nuxt автоматически заменит дату на timezone пользователя без риска." },
      { id: "d", text: "Компонент станет статическим SSG-файлом." },
    ],
    correctAnswer: "a",
    explanation: "Date.now() зависит от момента выполнения. Сервер формирует HTML раньше, клиент гидратирует позже, поэтому значения часто расходятся и ломают совпадение DOM.",
    knowledgeId: "ssr-hydration-1113",
  },
  {
    id: 1114,
    moduleId: "ssr-hydration",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "ttfb",
      "performance",
      "ssr",
    ],
    question: "Как SSR может повлиять на TTFB?",
    answers: [
      { id: "a", text: "TTFB всегда становится нулевым." },
      { id: "b", text: "TTFB может вырасти, потому что сервер должен подготовить HTML перед отправкой ответа." },
      { id: "c", text: "TTFB не связан с серверным временем ответа." },
      { id: "d", text: "SSR измеряется только через размер CSS." },
    ],
    correctAnswer: "b",
    explanation: "SSR требует серверной работы до ответа, поэтому TTFB может увеличиться. При этом FCP/LCP могут улучшиться за счёт готового HTML; важен баланс всей цепочки.",
    knowledgeId: "ssr-hydration-1114",
  },
  {
    id: 1115,
    moduleId: "ssr-hydration",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "fcp",
      "lcp",
      "performance",
    ],
    question: "Почему SSR может улучшить FCP или LCP?",
    answers: [
      { id: "a", text: "SSR уменьшает все изображения до 0 байт." },
      { id: "b", text: "SSR запрещает загрузку JavaScript." },
      { id: "c", text: "Браузер получает содержательный HTML раньше, не ожидая полного клиентского рендера." },
      { id: "d", text: "FCP и LCP не зависят от начального HTML." },
    ],
    correctAnswer: "c",
    explanation: "Готовый HTML может быстрее показать контент пользователю. Но результат зависит от данных, сервера, кеша, размера JS и hydration cost; SSR не является автоматической победой.",
    knowledgeId: "ssr-hydration-1115",
  },
  {
    id: 1116,
    moduleId: "ssr-hydration",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "useAsyncData",
      "data-fetching",
      "nuxt",
    ],
    question: "Зачем в Nuxt использовать useAsyncData для данных, нужных при SSR?",
    answers: [
      { id: "a", text: "Чтобы читать window на сервере." },
      { id: "b", text: "Чтобы отключить hydration." },
      { id: "c", text: "Чтобы заменить все API endpoints." },
      { id: "d", text: "Чтобы получить данные во время серверного рендера и передать результат клиенту через payload." },
    ],
    correctAnswer: "d",
    explanation: "useAsyncData интегрирован с Nuxt SSR и payload. Он позволяет серверу получить данные для HTML, а клиенту не повторять тот же запрос без необходимости.",
    knowledgeId: "ssr-hydration-1116",
  },
  {
    id: 1117,
    moduleId: "ssr-hydration",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "useFetch",
      "data-fetching",
      "nuxt",
    ],
    question: "Страница должна загрузить публичный список товаров и показать его уже в HTML. Что лучше выбрать?",
    answers: [
      { id: "a", text: "useFetch или useAsyncData с SSR-friendly загрузкой данных." },
      { id: "b", text: "onMounted, чтобы данные появились только после hydration." },
      { id: "c", text: "localStorage как источник истины." },
      { id: "d", text: "Math.random для генерации товаров." },
    ],
    correctAnswer: "a",
    explanation: "Если данные нужны в HTML, их нужно загрузить в SSR-подходящем механизме. onMounted выполняется только на клиенте, поэтому первый HTML будет пустым или неполным.",
    knowledgeId: "ssr-hydration-1117",
  },
  {
    id: 1118,
    moduleId: "ssr-hydration",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "useFetch",
      "onMounted",
      "seo",
    ],
    question: "На review страница каталога загружает товары только в onMounted. Что важно обсудить?",
    answers: [
      { id: "a", text: "onMounted всегда лучше для SEO." },
      { id: "b", text: "Если товары важны для первого HTML и SEO, лучше использовать SSR-friendly data fetching." },
      { id: "c", text: "useFetch нельзя использовать на страницах." },
      { id: "d", text: "Каталог нужно хранить в cookies." },
    ],
    correctAnswer: "b",
    explanation: "onMounted не участвует в серверном HTML, потому что выполняется только в браузере после монтирования. Для публичного каталога это может ухудшить SEO и FCP/LCP: пользователь и поисковый робот сначала получают пустой или неполный экран. Для таких данных стоит рассмотреть useFetch или useAsyncData.",
    knowledgeId: "ssr-hydration-1118",
  },
  {
    id: 1119,
    moduleId: "ssr-hydration",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "payload",
      "nuxt",
      "hydration",
    ],
    question: "Что такое Nuxt payload в контексте SSR?",
    answers: [
      { id: "a", text: "CSS-файл для всех страниц." },
      { id: "b", text: "Только список npm-зависимостей." },
      { id: "c", text: "Сериализованные данные серверного рендера, которые клиент использует при hydration." },
      { id: "d", text: "Секретный ключ runtimeConfig." },
    ],
    correctAnswer: "c",
    explanation: "Payload переносит данные, полученные при серверном рендере, на клиент. Это помогает избежать повторных запросов и сохранить согласованность HTML и клиентского состояния.",
    knowledgeId: "ssr-hydration-1119",
  },
  {
    id: 1120,
    moduleId: "ssr-hydration",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "timezone",
      "hydration-mismatch",
      "date",
    ],
    question: "Сервер форматирует дату в UTC, а клиент сразу форматирует её в локальной timezone пользователя. Какой риск?",
    answers: [
      { id: "a", text: "Timezone не влияет на отображение даты." },
      { id: "b", text: "Hydration автоматически исправит любой текст без предупреждений." },
      { id: "c", text: "Nuxt запретит форматирование дат." },
      { id: "d", text: "Текст даты может отличиться между сервером и клиентом, вызвав hydration mismatch." },
    ],
    correctAnswer: "d",
    explanation: "Разные timezone и locale могут дать разные строки на сервере и клиенте. Если такая строка участвует в SSR-разметке, клиентская hydration может увидеть несовпадение и заменить часть DOM. Для стабильного SSR форматирование дат лучше делать детерминированным или переносить browser-specific вывод в клиентскую часть.",
    knowledgeId: "ssr-hydration-1120",
  },
  {
    id: 1121,
    moduleId: "ssr-hydration",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "navigator",
      "browser-api",
      "code-review",
    ],
    question: "В setup используется navigator.language для начального текста. Что лучше предложить?",
    answers: [
      { id: "a", text: "Получать locale SSR-safe способом или читать navigator только на клиенте с fallback." },
      { id: "b", text: "Оставить navigator в setup, сервер поддерживает его всегда." },
      { id: "c", text: "Заменить navigator на document.cookie без проверки." },
      { id: "d", text: "Отключить hydration для всей страницы." },
    ],
    correctAnswer: "a",
    explanation: "navigator существует в браузере, но не на сервере. Для SSR лучше использовать headers/cookies/config или безопасный fallback, а browser API читать после client boundary.",
    knowledgeId: "ssr-hydration-1121",
  },
  {
    id: 1122,
    moduleId: "ssr-hydration",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "isr",
      "ssg",
      "rendering",
    ],
    question: "Что концептуально даёт ISR по сравнению с обычным SSG?",
    answers: [
      { id: "a", text: "Полный отказ от HTML." },
      { id: "b", text: "Возможность обновлять статически сгенерированные страницы по правилам revalidation." },
      { id: "c", text: "Запуск каждого компонента только в localStorage." },
      { id: "d", text: "Автоматическое исправление всех hydration mismatch." },
    ],
    correctAnswer: "b",
    explanation: "ISR пытается совместить скорость статической отдачи и возможность периодического обновления. Это не связано с отказом от HTML или автоматическим исправлением mismatch.",
    knowledgeId: "ssr-hydration-1122",
  },
  {
    id: 1123,
    moduleId: "ssr-hydration",
    type: "Scenario",
    difficulty: "MiddlePlus",
    tags: [
      "client-only",
      "map",
      "browser-api",
    ],
    question: "Интерактивная карта зависит от DOM, размеров контейнера и browser-only SDK. Какой подход безопаснее?",
    answers: [
      { id: "a", text: "Вызывать SDK на сервере в setup." },
      { id: "b", text: "Сгенерировать Math.random ключ для root-элемента." },
      { id: "c", text: "Изолировать карту в ClientOnly и дать SSR-friendly fallback." },
      { id: "d", text: "Загрузить SDK через runtimeConfig.public как секрет." },
    ],
    correctAnswer: "c",
    explanation: "DOM-зависимый SDK должен запускаться на клиенте, потому что на сервере нет window, document и реального DOM. ClientOnly защищает SSR от browser-only кода, а fallback сохраняет UX и структуру страницы. Это особенно важно для карт, графиков, виджетов оплаты и аналитических SDK.",
    knowledgeId: "ssr-hydration-1123",
  },
  {
    id: 1124,
    moduleId: "ssr-hydration",
    type: "Interview",
    difficulty: "MiddlePlus",
    tags: [
      "hydration-mismatch",
      "interview",
    ],
    question: "Как лучше объяснить hydration mismatch?",
    answers: [
      { id: "a", text: "Это отсутствие CSS-файла." },
      { id: "b", text: "Это ошибка установки Nuxt." },
      { id: "c", text: "Это любое отличие между dev и production scripts." },
      { id: "d", text: "Это ситуация, когда HTML от сервера не совпадает с тем, что клиентский Vue ожидает при hydration." },
    ],
    correctAnswer: "d",
    explanation: "Hydration mismatch возникает из-за различий между серверной DOM-разметкой и клиентским виртуальным деревом. Частые причины: случайные значения, даты, browser APIs, разные условия рендера.",
    knowledgeId: "ssr-hydration-1124",
  },
  {
    id: 1125,
    moduleId: "ssr-hydration",
    type: "CodeOutput",
    difficulty: "MiddlePlus",
    tags: [
      "import.meta.client",
      "browser-api",
    ],
    question: "Что делает условие if (import.meta.client) в Nuxt?",
    answers: [
      { id: "a", text: "Ограничивает выполнение блока клиентской средой." },
      { id: "b", text: "Гарантирует выполнение блока только на сервере." },
      { id: "c", text: "Отключает TypeScript внутри блока." },
      { id: "d", text: "Делает код статическим HTML." },
    ],
    correctAnswer: "a",
    explanation: "import.meta.client используется для кода, который должен выполняться в браузере. Для серверной ветки используют import.meta.server, чтобы явно разделить окружения. Такой подход помогает избежать ошибок вроде window is not defined и делает универсальный код Nuxt понятнее.",
    knowledgeId: "ssr-hydration-1125",
  },
  {
    id: 1126,
    moduleId: "ssr-hydration",
    type: "BestPractice",
    difficulty: "MiddlePlus",
    tags: [
      "lazy-hydration",
      "performance",
    ],
    question: "Зачем может понадобиться lazy hydration?",
    answers: [
      { id: "a", text: "Чтобы удалить HTML из ответа сервера." },
      { id: "b", text: "Чтобы отложить интерактивность неважных компонентов и снизить начальную стоимость hydration." },
      { id: "c", text: "Чтобы любые данные стали секретными." },
      { id: "d", text: "Чтобы запретить SEO-индексацию страницы." },
    ],
    correctAnswer: "b",
    explanation: "Hydration стоит CPU и JavaScript-времени, потому что браузеру нужно связать уже отрендеренный HTML с клиентским Vue-приложением. Lazy hydration помогает отложить оживление второстепенных интерактивных блоков, если они не нужны сразу. Это полезно для heavy widgets ниже первого экрана.",
    knowledgeId: "ssr-hydration-1126",
  },
  {
    id: 1127,
    moduleId: "ssr-hydration",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "useAsyncData",
      "key",
      "payload",
    ],
    question: "На review два useAsyncData используют один и тот же key для разных данных. Что может пойти не так?",
    answers: [
      { id: "a", text: "Ключи useAsyncData вообще не влияют на Nuxt." },
      { id: "b", text: "Одинаковые ключи всегда ускоряют страницу без риска." },
      { id: "c", text: "Payload/cache могут связать разные данные с одним ключом и привести к неправильному состоянию." },
      { id: "d", text: "Это влияет только на CSS-классы." },
    ],
    correctAnswer: "c",
    explanation: "Ключ useAsyncData идентифицирует результат в payload/cache. Если разные запросы используют один ключ, можно получить конфликт данных и неверный результат при hydration. Хороший ключ должен отражать сущность запроса и важные параметры, влияющие на ответ.",
    knowledgeId: "ssr-hydration-1127",
  },
  {
    id: 1128,
    moduleId: "ssr-hydration",
    type: "Scenario",
    difficulty: "MiddlePlus",
    tags: [
      "ssr-cost",
      "architecture",
    ],
    question: "Страница делает медленный персональный запрос на каждый SSR request. Какой риск самый прямой?",
    answers: [
      { id: "a", text: "Hydration станет ненужной." },
      { id: "b", text: "SEO автоматически станет идеальным." },
      { id: "c", text: "Client bundle исчезнет." },
      { id: "d", text: "TTFB и нагрузка на сервер могут заметно вырасти." },
    ],
    correctAnswer: "d",
    explanation: "SSR выполняет работу до отправки HTML. Если персональные данные медленные и не кешируются, серверный ответ задерживается, а инфраструктурная нагрузка растёт.",
    knowledgeId: "ssr-hydration-1128",
  },
  {
    id: 1129,
    moduleId: "ssr-hydration",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "ssr-tradeoffs",
      "senior",
    ],
    question: "Какой зрелый ответ на вопрос \"SSR всегда быстрее?\"",
    answers: [
      { id: "a", text: "Нет, SSR может улучшить первый контент, но увеличить TTFB, server cost и hydration cost." },
      { id: "b", text: "Да, SSR всегда быстрее по всем метрикам." },
      { id: "c", text: "Нет, SSR всегда медленнее CSR." },
      { id: "d", text: "SSR влияет только на цветовую тему." },
    ],
    correctAnswer: "a",
    explanation: "SSR — trade-off. Он может улучшить FCP/LCP и SEO, но добавляет серверную работу и hydration. Решение нужно принимать по метрикам и сценарию.",
    knowledgeId: "ssr-hydration-1129",
  },
  {
    id: 1130,
    moduleId: "ssr-hydration",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "hydration-mismatch",
      "random",
      "review",
    ],
    question: "Компонент генерирует id через Math.random() в template для aria-labelledby. Что лучше сделать?",
    answers: [
      { id: "a", text: "Оставить Math.random, mismatch не влияет на доступность." },
      { id: "b", text: "Использовать стабильный id, переданный из данных, useId или другой SSR-safe подход." },
      { id: "c", text: "Генерировать id в CSS." },
      { id: "d", text: "Отключить все aria-атрибуты." },
    ],
    correctAnswer: "b",
    explanation: "Случайный id может отличаться на сервере и клиенте, что создаёт mismatch и ломает связи доступности. ID должен быть стабильным между SSR и hydration.",
    knowledgeId: "ssr-hydration-1130",
  },
  {
    id: 1131,
    moduleId: "ssr-hydration",
    type: "Architecture",
    difficulty: "Senior",
    tags: [
      "rendering-choice",
      "architecture",
    ],
    question: "Когда SSR может ухудшить приложение?",
    answers: [
      { id: "a", text: "Когда странице нужен HTML." },
      { id: "b", text: "Когда есть хотя бы один компонент Vue." },
      { id: "c", text: "Когда данные персональные, медленные, не кешируются, SEO не важно, а hydration cost высок." },
      { id: "d", text: "Когда проект использует TypeScript." },
    ],
    correctAnswer: "c",
    explanation: "SSR имеет стоимость. Если страница приватная, данные медленные и SEO не важно, CSR или гибридная стратегия может быть проще и быстрее для пользователя.",
    knowledgeId: "ssr-hydration-1131",
  },
  {
    id: 1132,
    moduleId: "ssr-hydration",
    type: "Scenario",
    difficulty: "Senior",
    tags: [
      "ssg",
      "ssr",
      "architecture",
    ],
    question: "Маркетинговые страницы обновляются раз в день и должны быстро открываться глобально. Что стоит рассмотреть?",
    answers: [
      { id: "a", text: "SSR на каждый request без кеша обязательно лучше." },
      { id: "b", text: "Только ClientOnly для всего контента." },
      { id: "c", text: "Хранение HTML в localStorage пользователя." },
      { id: "d", text: "SSG/ISR или cache-first стратегию вместо SSR на каждый запрос." },
    ],
    correctAnswer: "d",
    explanation: "Редко меняющийся публичный контент хорошо подходит для генерации или агрессивного кеширования. SSR на каждый запрос может быть лишней серверной работой.",
    knowledgeId: "ssr-hydration-1132",
  },
  {
    id: 1133,
    moduleId: "ssr-hydration",
    type: "FindBug",
    difficulty: "Senior",
    tags: [
      "document",
      "ssr",
      "bug",
    ],
    question: "Plugin импортирует библиотеку, которая обращается к document на верхнем уровне модуля. Что может случиться?",
    answers: [
      { id: "a", text: "Серверный рендер может упасть ещё до выполнения client-only проверки." },
      { id: "b", text: "document автоматически появится в Node runtime." },
      { id: "c", text: "Hydration станет быстрее." },
      { id: "d", text: "Nuxt превратит document в ref." },
    ],
    correctAnswer: "a",
    explanation: "Если browser API используется на верхнем уровне импортируемого модуля, проверка внутри функции может не помочь. Библиотеку нужно импортировать динамически на клиенте или использовать client-only plugin.",
    knowledgeId: "ssr-hydration-1133",
  },
  {
    id: 1134,
    moduleId: "ssr-hydration",
    type: "CodeOutput",
    difficulty: "Senior",
    tags: [
      "process.client",
      "history",
      "nuxt",
    ],
    question: "Какой подход считается более современным в Nuxt 3 для проверки среды?",
    answers: [
      { id: "a", text: "process.client и process.server как основной новый API." },
      { id: "b", text: "import.meta.client и import.meta.server." },
      { id: "c", text: "window.server и window.client." },
      { id: "d", text: "document.nuxtEnvironment." },
    ],
    correctAnswer: "b",
    explanation: "В Nuxt 3 предпочтительнее import.meta.client и import.meta.server. process.client/server встречались исторически, но современный код лучше писать через import.meta-флаги. Это лучше соответствует Vite-экосистеме и делает условия выполнения более явными для сборщика.",
    knowledgeId: "ssr-hydration-1134",
  },
  {
    id: 1135,
    moduleId: "ssr-hydration",
    type: "BestPractice",
    difficulty: "Senior",
    tags: [
      "payload",
      "security",
      "performance",
    ],
    question: "Что важно учитывать при данных, попадающих в Nuxt payload?",
    answers: [
      { id: "a", text: "Payload всегда приватен и недоступен браузеру." },
      { id: "b", text: "Payload хранит только CSS." },
      { id: "c", text: "Payload сериализуется для клиента, поэтому не должен содержать секреты и лишние тяжёлые данные." },
      { id: "d", text: "Payload автоматически удаляет любые персональные поля." },
    ],
    correctAnswer: "c",
    explanation: "Payload передаётся клиенту для hydration, поэтому всё, что туда попало, нужно считать доступным браузеру. Туда нельзя класть секреты, private tokens и лишние внутренние поля. Кроме безопасности, важен размер: раздутый payload ухудшает загрузку, parsing и интерактивность.",
    knowledgeId: "ssr-hydration-1135",
  },
  {
    id: 1136,
    moduleId: "ssr-hydration",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "payload",
      "secrets",
      "review",
    ],
    question: "useAsyncData возвращает объект пользователя вместе с internalToken. Что нужно исправить?",
    answers: [
      { id: "a", text: "Оставить token, payload недоступен клиенту." },
      { id: "b", text: "Переименовать поле в secretToken." },
      { id: "c", text: "Сохранить token в title страницы." },
      { id: "d", text: "Не передавать internalToken в payload; вернуть только безопасные поля." },
    ],
    correctAnswer: "d",
    explanation: "Данные useAsyncData могут попасть в payload и стать доступны клиенту. Секреты и internal fields нужно фильтровать на сервере до возврата.",
    knowledgeId: "ssr-hydration-1136",
  },
  {
    id: 1137,
    moduleId: "ssr-hydration",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "hydration-process",
      "senior",
    ],
    question: "Что происходит во время hydration process?",
    answers: [
      { id: "a", text: "Vue сопоставляет клиентское виртуальное дерево с серверной DOM и подключает интерактивность." },
      { id: "b", text: "Браузер заново скачивает HTML с сервера для каждого компонента." },
      { id: "c", text: "Сервер удаляет JavaScript bundle." },
      { id: "d", text: "Nuxt заменяет все refs на строки." },
    ],
    correctAnswer: "a",
    explanation: "Hydration не должна заново строить весь DOM с нуля. Она использует существующую серверную разметку и подключает клиентскую реактивность, события и состояние.",
    knowledgeId: "ssr-hydration-1137",
  },
  {
    id: 1138,
    moduleId: "ssr-hydration",
    type: "Scenario",
    difficulty: "Senior",
    tags: [
      "lazy-hydration",
      "performance",
      "architecture",
    ],
    question: "На странице много интерактивных виджетов ниже первого экрана. Что может снизить initial hydration cost?",
    answers: [
      { id: "a", text: "Генерация новых random keys на клиенте." },
      { id: "b", text: "Отложенная или островная hydration для второстепенных блоков, если UX это допускает." },
      { id: "c", text: "Перенос всех виджетов в cookies." },
      { id: "d", text: "SSR каждого виджета по таймеру Date.now()." },
    ],
    correctAnswer: "b",
    explanation: "Если интерактивность ниже первого экрана не нужна сразу, её можно отложить. Это снижает начальную JS/CPU стоимость, но требует аккуратного UX и fallback.",
    knowledgeId: "ssr-hydration-1138",
  },
  {
    id: 1139,
    moduleId: "ssr-hydration",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "ssr",
      "architecture",
      "metrics",
    ],
    question: "Команда включает SSR для всех страниц без измерений. Что стоит сказать на review?",
    answers: [
      { id: "a", text: "SSR всегда оптимален, измерения не нужны." },
      { id: "b", text: "SPA всегда лучше SSR." },
      { id: "c", text: "Rendering strategy нужно выбирать по метрикам, SEO, типу данных, кешируемости и стоимости hydration." },
      { id: "d", text: "Rendering strategy зависит только от названия маршрута." },
    ],
    correctAnswer: "c",
    explanation: "SSR — не религия, а trade-off. Для разных страниц могут подходить SSR, CSR, SSG, ISR или гибридная стратегия; выбор нужно подтверждать требованиями и метриками.",
    knowledgeId: "ssr-hydration-1139",
  },
  {
    id: 1140,
    moduleId: "ssr-hydration",
    type: "Architecture",
    difficulty: "Senior",
    tags: [
      "strategy",
      "ssr",
      "senior",
    ],
    question: "Какой принцип лучше всего описывает зрелую SSR-архитектуру?",
    answers: [
      { id: "a", text: "SSR включают везде, даже если данные приватные и медленные." },
      { id: "b", text: "Все browser APIs вызывают в setup без проверок." },
      { id: "c", text: "Hydration mismatch игнорируют, если страница выглядит похожей." },
      { id: "d", text: "SSR применяют точечно там, где он улучшает пользовательские и продуктовые метрики, а не как универсальный default." },
    ],
    correctAnswer: "d",
    explanation: "Зрелая стратегия учитывает SEO, FCP/LCP, TTFB, кеш, приватность данных, серверную стоимость и hydration. SSR полезен, когда решает конкретную задачу лучше альтернатив.",
    knowledgeId: "ssr-hydration-1140",
  },
]
