import type { ContentQuestion } from '../../../types/content'

export const compositionApiQuestions: ContentQuestion[] = [
  {
    id: 201,
    moduleId: "composition-api",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "composition-api",
      "setup",
      "vue-3",
    ],
    question: "Что такое Composition API во Vue?",
    answers: [
      { id: "a", text: "Набор API для организации логики компонента через функции и реактивные примитивы" },
      { id: "b", text: "CSS-методология для именования классов в компонентах" },
      { id: "c", text: "Отдельный сборщик, который заменяет Vite" },
      { id: "d", text: "Формат JSON для описания props" },
    ],
    correctAnswer: "a",
    explanation: "Composition API — это набор API Vue 3 для описания состояния, вычислений, эффектов и lifecycle-логики через функции. Он не относится к CSS, сборке или JSON-формату. Главная идея — группировать код по смыслу и переиспользовать логику через composables.",
    knowledgeId: "knowledge-composition-api-q201",
  },
  {
    id: 202,
    moduleId: "composition-api",
    type: "Interview",
    difficulty: "JuniorPlus",
    tags: [
      "composition-api",
      "motivation",
      "options-api",
    ],
    question: "Зачем появился Composition API?",
    answers: [
      { id: "a", text: "Чтобы полностью запретить шаблоны Vue" },
      { id: "b", text: "Чтобы лучше организовывать связанную логику и переиспользовать её между компонентами" },
      { id: "c", text: "Чтобы заменить TypeScript собственным языком" },
      { id: "d", text: "Чтобы компоненты можно было писать только без state" },
    ],
    correctAnswer: "b",
    explanation: "Composition API появился как ответ на сложности больших компонентов: логика одной функции могла быть разбросана между data, computed, methods и watchers. Новый подход позволяет группировать связанную логику рядом и выносить её в composables. Он не запрещает шаблоны, не заменяет TypeScript и не убирает состояние.",
    knowledgeId: "knowledge-composition-api-q202",
  },
  {
    id: 203,
    moduleId: "composition-api",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "options-api",
      "composition-api",
      "tradeoffs",
    ],
    question: "Какое отличие Composition API от Options API наиболее точное?",
    answers: [
      { id: "a", text: "Composition API не поддерживает реактивность" },
      { id: "b", text: "Options API работает только без шаблонов" },
      { id: "c", text: "Composition API группирует логику через функции, Options API группирует код по опциям компонента" },
      { id: "d", text: "Composition API нельзя использовать с TypeScript" },
    ],
    correctAnswer: "c",
    explanation: "Options API структурирует код по секциям вроде data, methods и computed. Composition API позволяет группировать состояние, computed, watchers и функции одной фичи рядом. Реактивность и TypeScript поддерживаются, а шаблоны доступны в обоих подходах.",
    knowledgeId: "knowledge-composition-api-q203",
  },
  {
    id: 204,
    moduleId: "composition-api",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "script-setup",
      "sfc",
      "compile-time",
    ],
    question: "Что даёт `<script setup>` в Single File Component?",
    answers: [
      { id: "a", text: "Автоматическую замену всех ref на reactive" },
      { id: "b", text: "Запрет на импорт composables" },
      { id: "c", text: "Выполнение кода только один раз на всё приложение" },
      { id: "d", text: "Более короткий синтаксис setup, где объявления доступны шаблону автоматически" },
    ],
    correctAnswer: "d",
    explanation: "`<script setup>` — компиляторный синтаксис, который делает код setup короче. Импорты, переменные и функции верхнего уровня доступны шаблону. Он не заменяет ref на reactive, не запрещает composables и выполняется для экземпляра компонента, а не один раз на всё приложение.",
    knowledgeId: "knowledge-composition-api-q204",
  },
  {
    id: 205,
    moduleId: "composition-api",
    type: "CodeReview",
    difficulty: "JuniorPlus",
    tags: [
      "setup-function",
      "return",
      "template",
    ],
    question: "Что важно помнить при использовании обычной функции `setup()` вместо `<script setup>`?",
    answers: [
      { id: "a", text: "Значения, нужные в шаблоне, нужно вернуть из setup()" },
      { id: "b", text: "setup() не может использовать ref" },
      { id: "c", text: "setup() вызывается только после unmounted" },
      { id: "d", text: "setup() работает только в CSS-блоке" },
    ],
    correctAnswer: "a",
    explanation: "В обычной setup-функции шаблон видит только то, что возвращено из setup. ref и другие Composition API функции использовать можно. setup вызывается до монтирования компонента, а не после unmounted, и не имеет отношения к CSS-блоку.",
    knowledgeId: "knowledge-composition-api-q205",
  },
  {
    id: 206,
    moduleId: "composition-api",
    type: "CodeOutput",
    difficulty: "Junior",
    tags: [
      "ref",
      "script-setup",
      "value",
    ],
    question: "Что произойдёт в script setup после `const count = ref(0); count.value += 1`?",
    answers: [
      { id: "a", text: "count станет строкой \"1\"" },
      { id: "b", text: "Значение count станет 1 и зависимый UI сможет обновиться" },
      { id: "c", text: "Vue удалит компонент из DOM" },
      { id: "d", text: "Нужно обязательно вызвать count.update()" },
    ],
    correctAnswer: "b",
    explanation: "ref хранит значение в `.value`, поэтому `count.value += 1` корректно увеличит число. Если шаблон или computed зависят от count, Vue сможет обновить их. Метода `update()` у ref нет, а удаление компонента с этим не связано.",
    knowledgeId: "knowledge-composition-api-q206",
  },
  {
    id: 207,
    moduleId: "composition-api",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "reactive",
      "object-state",
      "composition-api",
    ],
    question: "Когда в Composition API уместно использовать reactive?",
    answers: [
      { id: "a", text: "Когда нужно сделать примитив readonly без объекта" },
      { id: "b", text: "Когда нужно объявить событие компонента" },
      { id: "c", text: "Когда нужно описать связанное объектное состояние с несколькими полями" },
      { id: "d", text: "Когда нужно подключить CSS-файл" },
    ],
    correctAnswer: "c",
    explanation: "reactive хорошо подходит для объектного состояния: формы, фильтров, настроек. Для примитивов чаще удобен ref. События объявляют через defineEmits, а CSS подключают другими механизмами.",
    knowledgeId: "knowledge-composition-api-q207",
  },
  {
    id: 208,
    moduleId: "composition-api",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "computed",
      "derived-state",
      "purity",
    ],
    question: "Какое правило лучше всего описывает computed в Composition API?",
    answers: [
      { id: "a", text: "computed нужен для любых HTTP-запросов" },
      { id: "b", text: "computed должен менять DOM напрямую" },
      { id: "c", text: "computed работает только внутри Options API" },
      { id: "d", text: "computed должен описывать чистое производное значение" },
    ],
    correctAnswer: "d",
    explanation: "computed предназначен для производных значений по реактивным зависимостям и должен оставаться чистым. HTTP-запросы и DOM-мутации являются side effects, для них лучше watch, методы или отдельные слои. Composition API полностью поддерживает computed.",
    knowledgeId: "knowledge-composition-api-q208",
  },
  {
    id: 209,
    moduleId: "composition-api",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "watch",
      "side-effects",
      "search",
    ],
    question: "Что выбрать для сохранения фильтра в URL при изменении ref `filter`?",
    answers: [
      { id: "a", text: "watch, потому что нужна реакция с побочным эффектом" },
      { id: "b", text: "computed, потому что запись в URL является чистым вычислением" },
      { id: "c", text: "defineProps, потому что он следит за URL" },
      { id: "d", text: "useSlots, потому что URL хранится в slot" },
    ],
    correctAnswer: "a",
    explanation: "Синхронизация с URL — побочный эффект при изменении значения, поэтому подходит watch. computed лучше оставить для чистых производных значений. defineProps и useSlots решают другие задачи.",
    knowledgeId: "knowledge-composition-api-q209",
  },
  {
    id: 210,
    moduleId: "composition-api",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "watchEffect",
      "auto-dependencies",
      "effect",
    ],
    question: "Когда watchEffect может быть удобнее watch?",
    answers: [
      { id: "a", text: "Когда нужно получить oldValue каждого источника" },
      { id: "b", text: "Когда зависимости очевидны из тела эффекта и их удобно собрать автоматически" },
      { id: "c", text: "Когда нужно объявить props" },
      { id: "d", text: "Когда нужно запретить повторный запуск эффекта" },
    ],
    correctAnswer: "b",
    explanation: "watchEffect сам собирает реактивные зависимости, прочитанные внутри callback. Если нужен oldValue или строгий список источников, лучше watch. Props объявляют через defineProps, а запрет повторного запуска не является задачей watchEffect.",
    knowledgeId: "knowledge-composition-api-q210",
  },
  {
    id: 211,
    moduleId: "composition-api",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "lifecycle",
      "onMounted",
      "composition-api",
    ],
    question: "Как в Composition API зарегистрировать код после монтирования компонента?",
    answers: [
      { id: "a", text: "Объявить mounted как метод внутри возвращаемого объекта setup" },
      { id: "b", text: "Вызвать onUpdated и ожидать, что он сработает до первого mount" },
      { id: "c", text: "Вызвать onMounted внутри setup или script setup" },
      { id: "d", text: "Вызвать onMounted асинхронно после завершения setup-контекста" },
    ],
    correctAnswer: "c",
    explanation: "Composition API использует lifecycle hooks как функции: onMounted, onUnmounted, onUpdated и другие. Их вызывают синхронно внутри setup-контекста. Options-style mounted в возвращаемом объекте setup не сработает, onUpdated относится к обновлениям, а асинхронная регистрация hook после setup-контекста нарушает правила lifecycle API.",
    knowledgeId: "knowledge-composition-api-q211",
  },
  {
    id: 212,
    moduleId: "composition-api",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "composables",
      "reuse",
      "architecture",
    ],
    question: "Что такое composable в Vue?",
    answers: [
      { id: "a", text: "Специальный CSS-файл для scoped styles" },
      { id: "b", text: "HTML-тег, который Vue создаёт автоматически" },
      { id: "c", text: "Любой JSON с массивом вопросов" },
      { id: "d", text: "Функция, которая инкапсулирует переиспользуемую Composition API логику" },
    ],
    correctAnswer: "d",
    explanation: "Composable — функция, обычно начинающаяся с `use`, которая содержит реактивное состояние, computed, watchers или lifecycle-логику. Она помогает переиспользовать поведение между компонентами. CSS, HTML-теги и JSON-данные не описывают composable.",
    knowledgeId: "knowledge-composition-api-q212",
  },
  {
    id: 213,
    moduleId: "composition-api",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "composables",
      "reuse",
      "state-boundary",
    ],
    question: "Какой признак говорит, что логику стоит вынести в composable?",
    answers: [
      { id: "a", text: "Одинаковый реактивный сценарий повторяется в нескольких компонентах" },
      { id: "b", text: "В компоненте есть один короткий ref" },
      { id: "c", text: "Нужно изменить цвет одной кнопки" },
      { id: "d", text: "Шаблон содержит обычный заголовок h1" },
    ],
    correctAnswer: "a",
    explanation: "Composable полезен, когда повторяется поведение: подписки, загрузка данных, синхронизация, таймеры, работа с localStorage. Один короткий ref или простая разметка не требуют нового composable. Важно выносить реальную логику, а не создавать лишние абстракции.",
    knowledgeId: "knowledge-composition-api-q213",
  },
  {
    id: 214,
    moduleId: "composition-api",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "organization",
      "large-component",
      "readability",
    ],
    question: "Что стоит предложить на code review, если setup содержит несколько несвязанных больших логических блоков?",
    answers: [
      { id: "a", text: "Перемешать ref, watch и функции в случайном порядке" },
      { id: "b", text: "Разделить логику по смыслу и вынести повторяемые сценарии в composables" },
      { id: "c", text: "Перенести всю логику в template" },
      { id: "d", text: "Удалить типизацию props" },
    ],
    correctAnswer: "b",
    explanation: "Composition API даёт свободу организации, поэтому важно поддерживать структуру. Связанную логику стоит держать рядом, а повторяемые сценарии — выносить в composables. Перенос логики в template или удаление типов ухудшит поддержку.",
    knowledgeId: "knowledge-composition-api-q214",
  },
  {
    id: 215,
    moduleId: "composition-api",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "provide",
      "inject",
      "dependency",
    ],
    question: "Когда provide/inject может быть уместнее props drilling?",
    answers: [
      { id: "a", text: "Когда нужно заменить все события компонента" },
      { id: "b", text: "Когда нужно сделать каждый prop обязательным" },
      { id: "c", text: "Когда данные нужны глубоко вложенным потомкам, а промежуточные компоненты их не используют" },
      { id: "d", text: "Когда нужно отрендерить список через v-for" },
    ],
    correctAnswer: "c",
    explanation: "provide/inject помогает передать зависимость глубоко вниз без прокидывания через каждый промежуточный компонент. Это не замена всем событиям и не связано с обязательностью props или v-for. Такой подход нужно использовать осознанно, чтобы зависимости оставались понятными.",
    knowledgeId: "knowledge-composition-api-q215",
  },
  {
    id: 216,
    moduleId: "composition-api",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "template-refs",
      "dom",
      "onMounted",
    ],
    question: "Когда template ref на DOM-элемент обычно становится доступен?",
    answers: [
      { id: "a", text: "До создания setup" },
      { id: "b", text: "Только после сборки проекта" },
      { id: "c", text: "Он никогда не доступен в Composition API" },
      { id: "d", text: "После монтирования компонента, например внутри onMounted" },
    ],
    correctAnswer: "d",
    explanation: "DOM-элемент появляется после рендера и монтирования, поэтому template ref обычно читают в onMounted или позже. До setup DOM ещё не создан. Composition API поддерживает template refs через ref(null) и атрибут ref в шаблоне.",
    knowledgeId: "knowledge-composition-api-q216",
  },
  {
    id: 217,
    moduleId: "composition-api",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "defineProps",
      "props",
      "script-setup",
    ],
    question: "Какую задачу решает defineProps в `<script setup>`?",
    answers: [
      { id: "a", text: "Чтобы объявить props компонента" },
      { id: "b", text: "Чтобы отправить событие родителю" },
      { id: "c", text: "Чтобы создать новый route" },
      { id: "d", text: "Чтобы дождаться обновления DOM" },
    ],
    correctAnswer: "a",
    explanation: "defineProps — компиляторный макрос для объявления props в script setup. События объявляют через defineEmits, маршруты — через router, а DOM-обновления ждут через nextTick. Макрос не нужно импортировать.",
    knowledgeId: "knowledge-composition-api-q217",
  },
  {
    id: 218,
    moduleId: "composition-api",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "defineEmits",
      "events",
      "script-setup",
    ],
    question: "Для чего используется defineEmits?",
    answers: [
      { id: "a", text: "Чтобы принять props от родителя" },
      { id: "b", text: "Чтобы объявить события, которые компонент может отправлять наружу" },
      { id: "c", text: "Чтобы сделать объект readonly" },
      { id: "d", text: "Чтобы зарегистрировать onMounted" },
    ],
    correctAnswer: "b",
    explanation: "defineEmits объявляет события компонента и возвращает функцию emit. Props объявляют через defineProps, readonly создаёт защитную обёртку, а lifecycle hooks регистрируются отдельными функциями.",
    knowledgeId: "knowledge-composition-api-q218",
  },
  {
    id: 219,
    moduleId: "composition-api",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "defineExpose",
      "template-ref",
      "public-api",
    ],
    question: "Зачем нужен defineExpose в `<script setup>`?",
    answers: [
      { id: "a", text: "Чтобы автоматически открыть все локальные переменные глобально" },
      { id: "b", text: "Чтобы объявить props" },
      { id: "c", text: "Чтобы явно открыть часть API компонента для родителя через template ref" },
      { id: "d", text: "Чтобы включить scoped styles" },
    ],
    correctAnswer: "c",
    explanation: "Компоненты на script setup по умолчанию закрыты для родительского доступа через template ref. defineExpose позволяет явно указать, какие методы или значения доступны наружу. Это не делает всё глобальным и не заменяет defineProps.",
    knowledgeId: "knowledge-composition-api-q219",
  },
  {
    id: 220,
    moduleId: "composition-api",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "defineModel",
      "v-model",
      "two-way-binding",
    ],
    question: "Что упрощает defineModel во Vue?",
    answers: [
      { id: "a", text: "Регистрацию lifecycle hooks" },
      { id: "b", text: "Глубокое клонирование reactive-объектов" },
      { id: "c", text: "Автоматическую маршрутизацию" },
      { id: "d", text: "Создание v-model API в компоненте" },
    ],
    correctAnswer: "d",
    explanation: "defineModel упрощает описание prop и update-события для v-model в компоненте. Он не относится к lifecycle, клонированию или роутингу. Тема важна для компонентов форм и дизайн-систем.",
    knowledgeId: "knowledge-composition-api-q220",
  },
  {
    id: 221,
    moduleId: "composition-api",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "useSlots",
      "slots",
      "composition-api",
    ],
    question: "В каком сценарии Composition API может понадобиться useSlots?",
    answers: [
      { id: "a", text: "Когда в script setup нужно проверить или передать slots программно" },
      { id: "b", text: "Когда нужно объявить props" },
      { id: "c", text: "Когда нужно создать ref для числа" },
      { id: "d", text: "Когда нужно отключить scoped styles" },
    ],
    correctAnswer: "a",
    explanation: "useSlots возвращает объект slots внутри setup-контекста. Он нужен, если логика script должна знать, передан ли slot, или передать slot дальше. Props, ref и стили решаются другими API.",
    knowledgeId: "knowledge-composition-api-q221",
  },
  {
    id: 222,
    moduleId: "composition-api",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "useAttrs",
      "attrs",
      "fallthrough",
    ],
    question: "Для чего используют useAttrs?",
    answers: [
      { id: "a", text: "Чтобы создать computed из props" },
      { id: "b", text: "Чтобы получить fallthrough attributes внутри setup" },
      { id: "c", text: "Чтобы подписаться на watchEffect" },
      { id: "d", text: "Чтобы сделать provide глобальным" },
    ],
    correctAnswer: "b",
    explanation: "useAttrs даёт доступ к атрибутам, которые не объявлены как props, например class, id или aria-атрибуты. Это полезно для wrapper-компонентов. Он не создаёт computed, не подписывает watcher и не меняет provide/inject.",
    knowledgeId: "knowledge-composition-api-q222",
  },
  {
    id: 223,
    moduleId: "composition-api",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "props-typing",
      "typescript",
      "defineProps",
    ],
    question: "Какой вариант лучше для типизации props в script setup?",
    answers: [
      { id: "a", text: "Использовать неявный any для всех props" },
      { id: "b", text: "Хранить тип props в CSS-классе" },
      { id: "c", text: "Описать интерфейс props и передать его в defineProps<Props>()" },
      { id: "d", text: "Передавать props только через localStorage" },
    ],
    correctAnswer: "c",
    explanation: "Интерфейс и `defineProps<Props>()` дают понятный контракт компонента и проверку TypeScript. Неявный any ухудшает безопасность и автодополнение. CSS и localStorage не являются способом типизации props.",
    knowledgeId: "knowledge-composition-api-q223",
  },
  {
    id: 224,
    moduleId: "composition-api",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "emits-typing",
      "typescript",
      "defineEmits",
    ],
    question: "Зачем типизировать defineEmits в Composition API?",
    answers: [
      { id: "a", text: "Автоматическую отправку всех props родителю" },
      { id: "b", text: "Отключение TypeScript в компоненте" },
      { id: "c", text: "Глубокое клонирование event object" },
      { id: "d", text: "Проверку имён событий и payload при вызове emit" },
    ],
    correctAnswer: "d",
    explanation: "Типизированный defineEmits помогает не ошибиться в имени события и форме payload. Он не отправляет props автоматически и не отключает TypeScript. Это полезно для поддержки компонентных API.",
    knowledgeId: "knowledge-composition-api-q224",
  },
  {
    id: 225,
    moduleId: "composition-api",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "props-destructuring",
      "reactivity",
      "defineProps",
    ],
    question: "В чём риск обычной деструктуризации props в Composition API?",
    answers: [
      { id: "a", text: "Можно потерять реактивное обновление значения props" },
      { id: "b", text: "Props станут глобальными переменными" },
      { id: "c", text: "Компонент перестанет принимать slots" },
      { id: "d", text: "Vue запретит сборку любого SFC" },
    ],
    correctAnswer: "a",
    explanation: "Обычная деструктуризация props может превратить prop в локальное значение и потерять реактивную связь. Для сохранения связи используют props.property, toRef/toRefs или возможности компилятора в актуальных версиях Vue с пониманием ограничений. Остальные варианты не описывают реальный риск.",
    knowledgeId: "knowledge-composition-api-q225",
  },
  {
    id: 226,
    moduleId: "composition-api",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "pros-cons",
      "composition-api",
      "tradeoffs",
    ],
    question: "Какой минус Composition API стоит честно назвать на интервью?",
    answers: [
      { id: "a", text: "Он полностью запрещает переиспользование логики" },
      { id: "b", text: "Он даёт свободу организации, поэтому без дисциплины код может стать хаотичным" },
      { id: "c", text: "Он не работает с TypeScript" },
      { id: "d", text: "Он не поддерживает lifecycle hooks" },
    ],
    correctAnswer: "b",
    explanation: "Composition API даёт гибкость, но требует дисциплины: группировки по смыслу, понятных composables и читаемого порядка кода. Он как раз улучшает переиспользование, хорошо работает с TypeScript и поддерживает lifecycle hooks.",
    knowledgeId: "knowledge-composition-api-q226",
  },
  {
    id: 227,
    moduleId: "composition-api",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "simplicity",
      "overengineering",
      "component-design",
    ],
    question: "Когда не стоит усложнять компонент Composition API абстракциями?",
    answers: [
      { id: "a", text: "Когда в компоненте есть любой ref" },
      { id: "b", text: "Когда шаблон содержит больше одного div" },
      { id: "c", text: "Когда логика короткая, локальная и не повторяется" },
      { id: "d", text: "Когда используется TypeScript" },
    ],
    correctAnswer: "c",
    explanation: "Если логика короткая, понятная и не переиспользуется, новый composable может быть лишней абстракцией. Ref, количество div и TypeScript сами по себе не требуют усложнения. Хорошая архитектура выбирает простое решение до появления реальной сложности.",
    knowledgeId: "knowledge-composition-api-q227",
  },
  {
    id: 228,
    moduleId: "composition-api",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "composables",
      "state",
      "architecture",
    ],
    question: "Что лучше НЕ делать внутри универсального composable?",
    answers: [
      { id: "a", text: "Возвращать typed state и функции" },
      { id: "b", text: "Принимать параметры для настройки поведения" },
      { id: "c", text: "Очищать подписки при необходимости" },
      { id: "d", text: "Жёстко привязывать его к конкретной странице и скрытым DOM-элементам без параметров" },
    ],
    correctAnswer: "d",
    explanation: "Универсальный composable должен иметь явный API и минимальные скрытые зависимости. Жёсткая привязка к конкретной странице делает его непереиспользуемым и сложным для тестирования. Typed state, параметры и cleanup являются хорошими практиками.",
    knowledgeId: "knowledge-composition-api-q228",
  },
  {
    id: 229,
    moduleId: "composition-api",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "provide-inject",
      "readonly",
      "api-contract",
    ],
    question: "Зачем при provide часто передают readonly-состояние и функции изменения отдельно?",
    answers: [
      { id: "a", text: "Чтобы потомки читали состояние, но изменяли его только через явный API" },
      { id: "b", text: "Чтобы inject перестал работать в дочерних компонентах" },
      { id: "c", text: "Чтобы все props стали необязательными" },
      { id: "d", text: "Чтобы computed пересчитывался каждую миллисекунду" },
    ],
    correctAnswer: "a",
    explanation: "Readonly-состояние плюс явные функции изменения формируют контролируемый контракт. Потомки не мутируют данные напрямую, а вызывают понятные команды. Это не ломает inject и не связано с обязательностью props или таймерами computed.",
    knowledgeId: "knowledge-composition-api-q229",
  },
  {
    id: 230,
    moduleId: "composition-api",
    type: "Scenario",
    difficulty: "MiddlePlus",
    tags: [
      "cleanup",
      "lifecycle",
      "composables",
    ],
    question: "Что важно сделать в composable, который добавляет window event listener?",
    answers: [
      { id: "a", text: "Добавить listener заново при каждом рендере без удаления" },
      { id: "b", text: "Удалить listener в onUnmounted или через cleanup, чтобы не оставить утечку" },
      { id: "c", text: "Сохранить listener в CSS-переменную" },
      { id: "d", text: "Заменить addEventListener на defineProps" },
    ],
    correctAnswer: "b",
    explanation: "Если composable добавляет внешний listener, он должен убрать его при размонтировании или смене условий. Иначе обработчики могут накапливаться и обращаться к уже неактуальному состоянию. CSS-переменные и defineProps не решают cleanup внешних ресурсов.",
    knowledgeId: "knowledge-composition-api-q230",
  },
]
