import type { ContentQuestion } from '../../../types/content'

export const piniaQuestions: ContentQuestion[] = [
  {
    id: 1301,
    moduleId: "pinia",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "pinia",
      "state-management",
      "vue",
    ],
    question: "Зачем обычно используют Pinia во Vue-приложении?",
    answers: [
      { id: "a", text: "Для централизованного разделяемого состояния, actions и производных данных." },
      { id: "b", text: "Для замены шаблонов Vue на JSX." },
      { id: "c", text: "Для автоматической генерации CSS-классов." },
      { id: "d", text: "Для компиляции TypeScript без Vite." },
    ],
    correctAnswer: "a",
    explanation: "Pinia решает задачу управляемого shared state: данные живут в store, меняются через понятные actions и могут иметь getters. JSX, CSS и компиляция TypeScript не являются задачами Pinia. На интервью важно объяснить критерий: store нужен, когда состояние разделяется несколькими частями UI или должно переживать навигацию.",
    knowledgeId: "pinia-1301",
  },
  {
    id: 1302,
    moduleId: "pinia",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "pinia",
      "vuex",
      "migration",
    ],
    question: "Какое отличие Pinia от Vuex 3/4 чаще всего называют на собеседовании?",
    answers: [
      { id: "a", text: "Pinia запрещает actions." },
      { id: "b", text: "Pinia проще типизируется, не требует mutations и лучше подходит для Composition API." },
      { id: "c", text: "Pinia работает только в Options API." },
      { id: "d", text: "Pinia хранит state только в localStorage." },
    ],
    correctAnswer: "b",
    explanation: "Pinia убрала обязательные mutations, дала более простой API defineStore и хорошую TypeScript-инференцию. Actions в Pinia есть, Composition API поддерживается, а persistence не включена автоматически. Правильное сравнение должно говорить о DX, типизации и более лёгкой модели обновления состояния.",
    knowledgeId: "pinia-1302",
  },
  {
    id: 1303,
    moduleId: "pinia",
    type: "CodeOutput",
    difficulty: "Junior",
    tags: [
      "createPinia",
      "main.ts",
      "plugin",
    ],
    question: "Что делает createPinia() в старте Vue-приложения?",
    answers: [
      { id: "a", text: "Создаёт роуты по файловой структуре." },
      { id: "b", text: "Создаёт новый компонент store." },
      { id: "c", text: "Создаёт экземпляр Pinia, который подключается в app.use()." },
      { id: "d", text: "Сбрасывает все stores при каждом render." },
    ],
    correctAnswer: "c",
    explanation: "createPinia создаёт Pinia instance, который регистрируется как Vue plugin через app.use(pinia). Он не создаёт routes, компоненты или автоматический reset. Без подключения экземпляра stores не смогут корректно использоваться в приложении.",
    knowledgeId: "pinia-1303",
  },
  {
    id: 1304,
    moduleId: "pinia",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "defineStore",
      "store-id",
    ],
    question: "Что означает первый аргумент defineStore?",
    answers: [
      { id: "a", text: "Имя CSS-модуля для store." },
      { id: "b", text: "Путь к файлу компонента." },
      { id: "c", text: "Название route guard." },
      { id: "d", text: "Уникальный id store для devtools, hydration и plugins." },
    ],
    correctAnswer: "d",
    explanation: "Первый аргумент defineStore — уникальный id store. Он нужен Pinia для регистрации, devtools, SSR/hydration и plugin-контекста. Это не CSS, не путь файла и не guard. В больших приложениях стабильные id помогают поддерживать предсказуемую структуру состояния.",
    knowledgeId: "pinia-1304",
  },
  {
    id: 1305,
    moduleId: "pinia",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "option-store",
      "state",
      "getters",
    ],
    question: "Что характерно для option store в Pinia?",
    answers: [
      { id: "a", text: "Он описывается объектом с state, getters и actions." },
      { id: "b", text: "Он не может иметь getters." },
      { id: "c", text: "Он создаётся только внутри template." },
      { id: "d", text: "Он всегда является SSR-only." },
    ],
    correctAnswer: "a",
    explanation: "Option store похож на привычную объектную конфигурацию: state возвращается функцией, getters описывают производные данные, actions меняют состояние и выполняют сценарии. Getters поддерживаются, template не создаёт stores, а SSR не является обязательным режимом.",
    knowledgeId: "pinia-1305",
  },
  {
    id: 1306,
    moduleId: "pinia",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "setup-store",
      "composition-api",
    ],
    question: "Что отличает setup store от option store?",
    answers: [
      { id: "a", text: "Setup store не поддерживает actions." },
      { id: "b", text: "Setup store возвращает refs, computed и функции из setup-подобной функции." },
      { id: "c", text: "Setup store может использоваться только в Nuxt." },
      { id: "d", text: "Setup store не работает с TypeScript." },
    ],
    correctAnswer: "b",
    explanation: "Setup store описывается функцией, похожей на composable: внутри можно использовать ref, computed и функции, а наружу вернуть публичный API. Actions в таком store обычно являются возвращаемыми функциями. Nuxt и TypeScript не ограничивают setup stores.",
    knowledgeId: "pinia-1306",
  },
  {
    id: 1307,
    moduleId: "pinia",
    type: "FindBug",
    difficulty: "JuniorPlus",
    tags: [
      "state",
      "factory",
      "ssr",
    ],
    question: "Почему state в option store должен быть функцией?",
    answers: [
      { id: "a", text: "Чтобы getters работали только один раз." },
      { id: "b", text: "Чтобы actions были async по умолчанию." },
      { id: "c", text: "Чтобы каждый экземпляр приложения получал независимое начальное состояние." },
      { id: "d", text: "Чтобы запретить вложенные объекты." },
    ],
    correctAnswer: "c",
    explanation: "state как функция возвращает свежий объект состояния. Это особенно важно для SSR, тестов и повторного создания приложения: разные запросы или тесты не должны делить один объект. Getters, async actions и вложенные объекты не являются причиной этого правила.",
    knowledgeId: "pinia-1307",
  },
  {
    id: 1308,
    moduleId: "pinia",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "getters",
      "computed",
      "derived-state",
    ],
    question: "Что лучше хранить в getter Pinia store?",
    answers: [
      { id: "a", text: "Случайное значение Math.random() для каждого render." },
      { id: "b", text: "DOM-элемент из document.querySelector." },
      { id: "c", text: "Mutation-функцию вместо action." },
      { id: "d", text: "Производное значение на основе state, например filteredItems или totalPrice." },
    ],
    correctAnswer: "d",
    explanation: "Getter должен описывать производные данные на основе state и других getters. Случайные значения, DOM-ссылки и mutation-функции нарушают идею предсказуемого derived state. Если значение меняет состояние или выполняет side effect, это action, а не getter.",
    knowledgeId: "pinia-1308",
  },
  {
    id: 1309,
    moduleId: "pinia",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "actions",
      "async",
      "api",
    ],
    question: "Какой код корректно описывает async action в Pinia?",
    answers: [
      { id: "a", text: "actions: { async load() { this.items = await fetchItems() } }" },
      { id: "b", text: "getters: { async load() { this.items = [] } }" },
      { id: "c", text: "state: async () => ({ items: await fetchItems() })" },
      { id: "d", text: "template: { async load() {} }" },
    ],
    correctAnswer: "a",
    explanation: "Async side effects и изменение state должны жить в actions. Getter не должен мутировать state, state-фабрика не должна выполнять await, а template не описывает store API. Такой ответ показывает понимание разделения ответственности внутри store.",
    knowledgeId: "pinia-1309",
  },
  {
    id: 1310,
    moduleId: "pinia",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "usage",
      "storeToRefs",
      "destructuring",
    ],
    question: "Как безопаснее деструктурировать state/getters из Pinia store в компоненте?",
    answers: [
      { id: "a", text: "Через JSON.parse(JSON.stringify(store))." },
      { id: "b", text: "Через storeToRefs(store), если нужно сохранить реактивность state/getters." },
      { id: "c", text: "Через обычное const { count } = store для любых значений." },
      { id: "d", text: "Через window.store, чтобы избежать Composition API." },
    ],
    correctAnswer: "b",
    explanation: "Обычная деструктуризация может потерять реактивную связь для state/getters. storeToRefs создаёт refs для реактивных свойств store, при этом actions можно брать напрямую. JSON-копия и window-глобали ломают реактивность и архитектуру.",
    knowledgeId: "pinia-1310",
  },
  {
    id: 1311,
    moduleId: "pinia",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "store-composition",
      "architecture",
    ],
    question: "Что важно учитывать при композиции нескольких Pinia stores?",
    answers: [
      { id: "a", text: "Каждый store обязан импортировать все остальные stores." },
      { id: "b", text: "Stores нельзя использовать друг внутри друга ни при каких условиях." },
      { id: "c", text: "Stores можно связывать, но нужно избегать скрытых циклических зависимостей." },
      { id: "d", text: "Композиция store автоматически нормализует данные." },
    ],
    correctAnswer: "c",
    explanation: "Pinia позволяет использовать один store внутри другого, но архитектурно важно контролировать направление зависимостей. Если stores импортируют друг друга и вызывают actions в момент инициализации, легко получить циклы. Нормализация данных и границы ответственности остаются задачей разработчика.",
    knowledgeId: "pinia-1311",
  },
  {
    id: 1312,
    moduleId: "pinia",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "$reset",
      "logout",
      "state",
    ],
    question: "Когда обычно нужен $reset() в option store?",
    answers: [
      { id: "a", text: "Чтобы удалить компонент из DOM." },
      { id: "b", text: "Чтобы отключить Vue Router." },
      { id: "c", text: "Чтобы пересобрать production bundle." },
      { id: "d", text: "Чтобы сбросить store к начальному state, например при logout." },
    ],
    correctAnswer: "d",
    explanation: "$reset возвращает option store к начальному состоянию, которое создаёт state-функция. Это полезно при logout, смене аккаунта или очистке transient state. DOM, router и build-процесс не связаны с $reset.",
    knowledgeId: "pinia-1312",
  },
  {
    id: 1313,
    moduleId: "pinia",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "$patch",
      "batching",
      "mutation",
    ],
    question: "На review виден код store.count++; store.name = \"Ada\";. Когда $patch может быть лучше?",
    answers: [
      { id: "a", text: "Когда нужно сгруппировать несколько изменений state в одну понятную операцию." },
      { id: "b", text: "Когда нужно запретить TypeScript." },
      { id: "c", text: "Когда нужно выполнить DOM query." },
      { id: "d", text: "Когда нужно создать route." },
    ],
    correctAnswer: "a",
    explanation: "$patch удобен для группировки нескольких изменений, особенно когда mutation должна быть видна как одна операция в devtools или подписке. Он не связан с TypeScript-запретом, DOM или routing. При простом одиночном изменении прямое присваивание state тоже нормально.",
    knowledgeId: "pinia-1313",
  },
  {
    id: 1314,
    moduleId: "pinia",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "$subscribe",
      "persistence",
    ],
    question: "Для чего чаще всего используют store.$subscribe()?",
    answers: [
      { id: "a", text: "Для регистрации компонента в router-view." },
      { id: "b", text: "Для реакции на изменения store, например сохранения части state в storage." },
      { id: "c", text: "Для объявления props компонента." },
      { id: "d", text: "Для компиляции SCSS." },
    ],
    correctAnswer: "b",
    explanation: "$subscribe позволяет подписаться на изменения state store. Частый production-сценарий — persistence, аналитика изменений или отладочные интеграции. Props, router-view и SCSS не относятся к механике подписки store.",
    knowledgeId: "pinia-1314",
  },
  {
    id: 1315,
    moduleId: "pinia",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "$onAction",
      "analytics",
      "logging",
    ],
    question: "Нужно логировать начало и ошибку выполнения actions. Какой API Pinia подходит лучше всего?",
    answers: [
      { id: "a", text: "store.$reset()" },
      { id: "b", text: "store.$patch()" },
      { id: "c", text: "store.$onAction()" },
      { id: "d", text: "storeToRefs()" },
    ],
    correctAnswer: "c",
    explanation: "$onAction подписывается на вызовы actions и позволяет обработать after/onError. Это подходит для логирования, аналитики и instrumentation. $patch меняет state, $reset сбрасывает state, а storeToRefs нужен для реактивной деструктуризации.",
    knowledgeId: "pinia-1315",
  },
  {
    id: 1316,
    moduleId: "pinia",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "plugins",
      "cross-cutting",
    ],
    question: "Когда уместен Pinia plugin?",
    answers: [
      { id: "a", text: "Когда один компоненту нужен один локальный ref." },
      { id: "b", text: "Когда нужно заменить все actions на getters." },
      { id: "c", text: "Когда нужно отключить reactivity." },
      { id: "d", text: "Когда нужно централизованно добавить поведение ко многим stores, например persistence или instrumentation." },
    ],
    correctAnswer: "d",
    explanation: "Plugin Pinia подходит для сквозных возможностей, которые применяются к нескольким stores: persistence, logging, metrics, injection сервисов. Для одного локального ref plugin избыточен. Он не заменяет actions на getters и не отключает реактивность.",
    knowledgeId: "pinia-1316",
  },
  {
    id: 1317,
    moduleId: "pinia",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "persistence",
      "localStorage",
      "security",
    ],
    question: "Что нельзя бездумно сохранять в localStorage через Pinia persistence?",
    answers: [
      { id: "a", text: "Секретные токены и чувствительные персональные данные." },
      { id: "b", text: "Тему интерфейса." },
      { id: "c", text: "Флаг выбранной вкладки." },
      { id: "d", text: "Некритичные пользовательские настройки." },
    ],
    correctAnswer: "a",
    explanation: "localStorage доступен JavaScript-коду в браузере и не подходит для секретов. Тема, вкладка и некритичные настройки часто допустимы, если это соответствует требованиям продукта. Для sensitive данных нужны более строгие security-подходы и серверные механизмы.",
    knowledgeId: "pinia-1317",
  },
  {
    id: 1318,
    moduleId: "pinia",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "sessionStorage",
      "storage",
    ],
    question: "Когда sessionStorage может быть уместнее localStorage для store persistence?",
    answers: [
      { id: "a", text: "Когда данные должны синхронизироваться между всеми устройствами." },
      { id: "b", text: "Когда данные должны жить только в рамках вкладки/сессии браузера." },
      { id: "c", text: "Когда нужно хранить секреты без риска XSS." },
      { id: "d", text: "Когда нужно заменить server state." },
    ],
    correctAnswer: "b",
    explanation: "sessionStorage живёт в рамках конкретной вкладки и очищается после завершения сессии. Это подходит для временных UI-состояний, но не для синхронизации устройств и не для секретов. Storage в браузере не заменяет серверное состояние.",
    knowledgeId: "pinia-1318",
  },
  {
    id: 1319,
    moduleId: "pinia",
    type: "FindBug",
    difficulty: "MiddlePlus",
    tags: [
      "ssr",
      "window",
      "localStorage",
    ],
    question: "В store на верхнем уровне читается localStorage. Почему это опасно для SSR?",
    answers: [
      { id: "a", text: "Потому что Pinia запрещает хранить строки." },
      { id: "b", text: "Потому что getters перестают кешироваться." },
      { id: "c", text: "Потому что localStorage доступен только в браузере, а серверный render не имеет window." },
      { id: "d", text: "Потому что actions становятся readonly." },
    ],
    correctAnswer: "c",
    explanation: "SSR выполняется на сервере, где нет window и localStorage. Чтение browser API на верхнем уровне store может сломать серверный render. Такие операции нужно выполнять в client-only ветке, plugin с проверкой окружения или после hydration.",
    knowledgeId: "pinia-1319",
  },
  {
    id: 1320,
    moduleId: "pinia",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "hydration",
      "ssr",
      "initial-state",
    ],
    question: "Что важно для hydration состояния Pinia при SSR?",
    answers: [
      { id: "a", text: "State нужно всегда генерировать через Math.random()." },
      { id: "b", text: "Hydration требует удалить все getters." },
      { id: "c", text: "Store должен хранить DOM-элементы." },
      { id: "d", text: "Сервер и клиент должны согласованно передать начальное состояние без утечки приватных данных." },
    ],
    correctAnswer: "d",
    explanation: "При SSR начальное состояние сериализуется и используется клиентом при hydration. Оно должно быть детерминированным, безопасным и не содержать секретов. Случайные значения, DOM-элементы и удаление getters не решают задачу hydration.",
    knowledgeId: "pinia-1320",
  },
  {
    id: 1321,
    moduleId: "pinia",
    type: "Scenario",
    difficulty: "MiddlePlus",
    tags: [
      "nuxt",
      "runtimeConfig",
      "server",
    ],
    question: "Почему runtimeConfig не стоит напрямую хранить целиком в клиентском Pinia store?",
    answers: [
      { id: "a", text: "Потому что private runtimeConfig может содержать server-only секреты." },
      { id: "b", text: "Потому что Pinia не работает с объектами." },
      { id: "c", text: "Потому что getters перестают быть computed." },
      { id: "d", text: "Потому что actions нельзя вызывать после hydration." },
    ],
    correctAnswer: "a",
    explanation: "Private runtimeConfig предназначен для серверного кода и может содержать секреты. Клиентский Pinia store сериализуется или доступен браузеру, поэтому туда нельзя переносить private config. В store допустимо хранить только безопасные public значения, нужные UI.",
    knowledgeId: "pinia-1321",
  },
  {
    id: 1322,
    moduleId: "pinia",
    type: "Interview",
    difficulty: "MiddlePlus",
    tags: [
      "store-vs-composable",
      "decision",
    ],
    question: "Когда composable лучше Pinia store?",
    answers: [
      { id: "a", text: "Когда нужно хранить state между всеми страницами." },
      { id: "b", text: "Когда логика локальная, переиспользуемая и не требует централизованного глобального состояния." },
      { id: "c", text: "Когда нужны devtools для доменного состояния." },
      { id: "d", text: "Когда данные должны переживать logout." },
    ],
    correctAnswer: "b",
    explanation: "Composable хорошо подходит для локальной reusable logic: browser API, формы, таймеры, query helpers. Store нужен для управляемого shared state, devtools-контракта и состояния, важного многим экранам. На интервью ценится баланс, а не правило использовать store всегда.",
    knowledgeId: "pinia-1322",
  },
  {
    id: 1323,
    moduleId: "pinia",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "responsibility",
      "domain-boundaries",
    ],
    question: "Какой признак говорит, что store стал слишком большим?",
    answers: [
      { id: "a", text: "В store есть один getter." },
      { id: "b", text: "Store импортируется в двух компонентах." },
      { id: "c", text: "Store содержит несколько несвязанных доменов, UI-флаги, API-адаптеры и сложные сценарии сразу." },
      { id: "d", text: "Store имеет TypeScript-типы." },
    ],
    correctAnswer: "c",
    explanation: "Большой store опасен, когда смешивает разные домены и ответственности. Один getter, использование в нескольких компонентах и типы сами по себе нормальны. Хорошая архитектура разделяет stores по бизнес-областям и оставляет UI-локальность вне глобального состояния.",
    knowledgeId: "pinia-1323",
  },
  {
    id: 1324,
    moduleId: "pinia",
    type: "Architecture",
    difficulty: "Senior",
    tags: [
      "normalization",
      "entities",
      "performance",
    ],
    question: "Зачем нормализовать состояние в Pinia store?",
    answers: [
      { id: "a", text: "Чтобы заменить TypeScript на JSON." },
      { id: "b", text: "Чтобы запретить getters." },
      { id: "c", text: "Чтобы каждый компонент имел отдельную копию backend-ответа." },
      { id: "d", text: "Чтобы хранить сущности по id, уменьшать дублирование и проще обновлять связанные данные." },
    ],
    correctAnswer: "d",
    explanation: "Нормализация помогает хранить entities в структурах вроде byId/allIds, не дублировать один объект в нескольких списках и точечно обновлять данные. Это особенно важно для больших списков, optimistic updates и кеширования. JSON, запрет getters и копии backend-ответов не решают проблему консистентности.",
    knowledgeId: "pinia-1324",
  },
  {
    id: 1325,
    moduleId: "pinia",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "derived-state",
      "duplication",
      "getters",
    ],
    question: "На review в state хранят totalPrice и items. Что проверить?",
    answers: [
      { id: "a", text: "Не является ли totalPrice производным значением, которое лучше сделать getter." },
      { id: "b", text: "Нужно ли перенести items в CSS." },
      { id: "c", text: "Почему totalPrice не хранится в route meta." },
      { id: "d", text: "Можно ли заменить actions на watchers." },
    ],
    correctAnswer: "a",
    explanation: "Если totalPrice полностью вычисляется из items, хранение его в state создаёт риск рассинхронизации. Getter делает производное значение единым и предсказуемым. CSS, route meta и замена actions на watchers не относятся к корректному моделированию derived state.",
    knowledgeId: "pinia-1325",
  },
  {
    id: 1326,
    moduleId: "pinia",
    type: "Scenario",
    difficulty: "Senior",
    tags: [
      "optimistic-updates",
      "rollback",
      "api",
    ],
    question: "Какой подход нужен для optimistic update в Pinia?",
    answers: [
      { id: "a", text: "Всегда игнорировать ответ сервера." },
      { id: "b", text: "Сразу изменить UI-state, сохранить возможность rollback и обработать ошибку API." },
      { id: "c", text: "Запретить пользователю любые действия после клика навсегда." },
      { id: "d", text: "Хранить pending state только в DOM dataset." },
    ],
    correctAnswer: "b",
    explanation: "Optimistic update ускоряет ощущение UI, но требует стратегии rollback, pending state и согласования с серверным ответом. Игнорировать сервер опасно, вечная блокировка ломает UX, а DOM dataset не является источником состояния. Store должен явно моделировать optimistic-сценарий.",
    knowledgeId: "pinia-1326",
  },
  {
    id: 1327,
    moduleId: "pinia",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "typescript",
      "state",
      "actions",
    ],
    question: "Что важно для хорошей типизации Pinia store?",
    answers: [
      { id: "a", text: "Использовать unknown для всех полей." },
      { id: "b", text: "Отключить strict mode TypeScript." },
      { id: "c", text: "Типизировать state-модель, payload actions и возвращаемые значения, не теряя inference." },
      { id: "d", text: "Хранить все данные как string." },
    ],
    correctAnswer: "c",
    explanation: "Pinia хорошо выводит типы, но доменные модели, payload actions и внешние API-ответы должны иметь явные контракты. unknown для всего, отключение strict mode и string-only state снижают качество. На senior-уровне важно показать баланс между inference и явными типами.",
    knowledgeId: "pinia-1327",
  },
  {
    id: 1328,
    moduleId: "pinia",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "large-store",
      "modularization",
    ],
    question: "Store содержит 1200 строк, auth, cart, filters и notifications. Какой review-комментарий наиболее полезен?",
    answers: [
      { id: "a", text: "Оставить всё в одном store, потому что Pinia быстрее." },
      { id: "b", text: "Перенести все данные в localStorage." },
      { id: "c", text: "Заменить state на CSS variables." },
      { id: "d", text: "Разделить store по доменным границам и явно описать связи между ними." },
    ],
    correctAnswer: "d",
    explanation: "Огромный store с несвязанными доменами трудно тестировать и поддерживать. Разделение по границам auth/cart/filters/notifications делает ответственность яснее. Производительность Pinia не является аргументом для монолита, а localStorage и CSS variables не решают архитектурную проблему.",
    knowledgeId: "pinia-1328",
  },
  {
    id: 1329,
    moduleId: "pinia",
    type: "Scenario",
    difficulty: "Senior",
    tags: [
      "lazy-loading",
      "code-splitting",
    ],
    question: "Когда lazy loading store может быть оправдан?",
    answers: [
      { id: "a", text: "Когда store относится к редко открываемому тяжёлому feature-модулю." },
      { id: "b", text: "Когда store нужен на каждом первом экране." },
      { id: "c", text: "Когда нужно скрыть ошибку типизации." },
      { id: "d", text: "Когда требуется отключить devtools." },
    ],
    correctAnswer: "a",
    explanation: "Pinia stores обычно регистрируются при импорте, поэтому route-level code splitting может отложить загрузку feature store. Это оправдано для редких тяжёлых модулей. Core store первого экрана лучше не прятать за лишней асинхронной границей.",
    knowledgeId: "pinia-1329",
  },
  {
    id: 1330,
    moduleId: "pinia",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "cyclic-dependencies",
      "stores",
    ],
    question: "Два stores импортируют друг друга и вызывают actions при инициализации. Какой риск главный?",
    answers: [
      { id: "a", text: "CSS перестанет применяться." },
      { id: "b", text: "Может возникнуть циклическая зависимость и неочевидный порядок инициализации." },
      { id: "c", text: "Pinia автоматически удалит оба store." },
      { id: "d", text: "TypeScript перестанет поддерживать union types." },
    ],
    correctAnswer: "b",
    explanation: "Циклические зависимости между stores особенно опасны, если actions вызываются во время создания store. Это может дать undefined, частично инициализированные модули или неожиданные side effects. Лучше вынести общий сценарий в service/composable или сделать направление зависимости явным.",
    knowledgeId: "pinia-1330",
  },
  {
    id: 1331,
    moduleId: "pinia",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "common-mistakes",
      "watchers",
      "actions",
    ],
    question: "Какая частая ошибка при работе с Pinia actions?",
    answers: [
      { id: "a", text: "Держать бизнес-сценарий в action и вызывать его из компонента." },
      { id: "b", text: "Типизировать payload action." },
      { id: "c", text: "Разбрасывать изменение store по watchers в компонентах вместо явного action." },
      { id: "d", text: "Возвращать Promise из async action." },
    ],
    correctAnswer: "c",
    explanation: "Если состояние меняется через watchers в разных компонентах, сценарий становится трудно отследить. Action делает намерение явным и централизует изменение state. Типизация payload, async actions и вызов action из компонента являются нормальными практиками.",
    knowledgeId: "pinia-1331",
  },
  {
    id: 1332,
    moduleId: "pinia",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "mutation",
      "props",
      "store-boundaries",
    ],
    question: "Компонент напрямую меняет userStore.user.profile.name из глубокой формы. Что стоит обсудить на review?",
    answers: [
      { id: "a", text: "Нужно ли заменить форму на route alias." },
      { id: "b", text: "Почему state не хранится в CSS." },
      { id: "c", text: "Можно ли удалить TypeScript." },
      { id: "d", text: "Нужен ли явный action/updateProfile, чтобы сохранить контроль над валидацией и side effects." },
    ],
    correctAnswer: "d",
    explanation: "Pinia допускает прямую мутацию state, но в сложных доменных сценариях явный action лучше фиксирует правила изменения. Форма профиля может требовать validation, optimistic update, audit или API sync. CSS, route alias и удаление TypeScript не решают контроль состояния.",
    knowledgeId: "pinia-1332",
  },
  {
    id: 1333,
    moduleId: "pinia",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "testing",
      "actions",
      "mocking",
    ],
    question: "Что важно при тестировании Pinia store?",
    answers: [
      { id: "a", text: "Проверять state transitions и actions изолированно от DOM, мокая внешние API." },
      { id: "b", text: "Тестировать только CSS-классы store." },
      { id: "c", text: "Вызывать реальные production API в каждом unit test." },
      { id: "d", text: "Отключать TypeScript перед тестами." },
    ],
    correctAnswer: "a",
    explanation: "Store-тесты должны проверять переходы состояния, getters и actions без зависимости от DOM. Внешние API лучше мокать, чтобы тест был быстрым и детерминированным. Реальные API, CSS-классы и отключение TypeScript не дают надёжной проверки store-логики.",
    knowledgeId: "pinia-1333",
  },
  {
    id: 1334,
    moduleId: "pinia",
    type: "Scenario",
    difficulty: "Senior",
    tags: [
      "cache",
      "invalidation",
      "server-state",
    ],
    question: "Store кеширует список товаров. Что обязательно продумать?",
    answers: [
      { id: "a", text: "Только цвет кнопки загрузки." },
      { id: "b", text: "TTL, invalidation, reload strategy и реакцию на ошибки обновления." },
      { id: "c", text: "Запрет всех getters." },
      { id: "d", text: "Перенос кеша в template refs." },
    ],
    correctAnswer: "b",
    explanation: "Кеш в store является архитектурным решением, а не просто массивом данных. Нужно определить срок актуальности, условия сброса, стратегию повторной загрузки и поведение при ошибках. Иначе UI будет показывать устаревшие или противоречивые данные.",
    knowledgeId: "pinia-1334",
  },
  {
    id: 1335,
    moduleId: "pinia",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "senior",
      "tradeoffs",
      "architecture",
    ],
    question: "Какой senior-ответ лучше всего описывает выбор Pinia?",
    answers: [
      { id: "a", text: "Pinia нужно использовать для каждого ref." },
      { id: "b", text: "Pinia никогда не нужна, composables всегда достаточно." },
      { id: "c", text: "Pinia выбирают для разделяемого состояния с явным контрактом, но локальное состояние оставляют локальным." },
      { id: "d", text: "Pinia нужна только ради localStorage." },
    ],
    correctAnswer: "c",
    explanation: "Зрелый ответ описывает trade-off: Pinia полезна для shared/domain state, devtools, actions и предсказуемого контракта. Но локальное состояние компонента, простой composable или server cache могут быть лучше в своём контексте. Использовать store для каждого ref так же плохо, как отрицать store полностью.",
    knowledgeId: "pinia-1335",
  },
]
