<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { useGameStore } from '../../stores/game'
import type { CodeExampleLanguage } from '../../types/knowledge'
import { highlightCode } from '../../utils/shikiHighlighter'

interface Props {
  language: CodeExampleLanguage
  filename?: string
  code: string
}

const props = defineProps<Props>()
const gameStore = useGameStore()

const copied = ref(false)
const highlightedHtml = ref('')
let copiedTimer: ReturnType<typeof window.setTimeout> | undefined
let highlightRequestId = 0

const languageLabel = computed(() => props.language.toUpperCase())
const hasHighlightedCode = computed(() => highlightedHtml.value.length > 0)

const loadHighlightedCode = async (): Promise<void> => {
  const requestId = (highlightRequestId += 1)
  highlightedHtml.value = ''

  try {
    const html = await highlightCode(props.code, props.language)

    if (requestId === highlightRequestId) {
      highlightedHtml.value = html
    }
  } catch {
    if (requestId === highlightRequestId) {
      highlightedHtml.value = ''
    }
  }
}

const copyCode = async (): Promise<void> => {
  if (!navigator.clipboard?.writeText) {
    return
  }

  try {
    await navigator.clipboard.writeText(props.code)
    copied.value = true
    gameStore.checkAchievements({
      type: 'codeExampleCopied',
    })

    if (copiedTimer) {
      window.clearTimeout(copiedTimer)
    }

    copiedTimer = window.setTimeout(() => {
      copied.value = false
    }, 1600)
  } catch {
    copied.value = false
  }
}

watch(() => [props.code, props.language] as const, loadHighlightedCode, { immediate: true })

onBeforeUnmount(() => {
  if (copiedTimer) {
    window.clearTimeout(copiedTimer)
  }
})
</script>

<template>
  <figure class="code-panel min-w-0 overflow-hidden">
    <div class="flex flex-wrap items-center justify-between gap-3 border-b border-[rgba(0,255,177,0.24)] bg-black px-4 py-3">
      <figcaption class="min-w-0 font-mono text-xs font-bold uppercase tracking-[0.12em] text-[var(--color-neon-green)]">
        <span>{{ languageLabel }}</span>
        <span v-if="filename" class="ml-3 text-[var(--color-muted)]">{{ filename }}</span>
      </figcaption>

      <button
        type="button"
        class="arcade-button-base cursor-pointer border border-[rgba(0,255,177,0.42)] bg-[rgba(0,255,177,0.08)] px-3 py-1.5 text-xs text-[var(--color-neon-green)] hover:border-[var(--color-neon-green)] hover:bg-[rgba(0,255,177,0.14)]"
        @click="copyCode"
      >
        {{ copied ? 'Скопировано' : 'Копировать' }}
      </button>
    </div>

    <!-- v-html is limited to HTML generated by Shiki from static educational code examples. -->
    <div
      v-if="hasHighlightedCode"
      class="shiki-code-area"
      v-html="highlightedHtml"
    ></div>

    <pre v-else class="m-0 overflow-x-auto p-4 text-sm leading-7 text-slate-100"><code>{{ code }}</code></pre>
  </figure>
</template>

<style scoped>
.shiki-code-area {
  overflow-x: auto;
  min-width: 0;
}

.shiki-code-area :deep(.shiki) {
  margin: 0;
  overflow-x: auto;
  border-radius: 0;
  background: transparent !important;
  padding: 1rem;
  font-size: 0.875rem;
  line-height: 1.75;
}

.shiki-code-area :deep(code) {
  display: block;
  min-width: max-content;
}
</style>
