import type { ContentQuestion } from '../../../types/content'

export const vueBasicsQuestions: ContentQuestion[] = [
  {
    id: 1,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "template",
      "directive",
      "conditional-rendering",
    ],
    question: "Что делает директива v-if?",
    answers: [
      { id: "a", text: "Условно рендерит элемент в DOM" },
      { id: "b", text: "Добавляет CSS-класс к элементу" },
      { id: "c", text: "Повторяет элемент по списку" },
      { id: "d", text: "Создает двустороннюю привязку" },
    ],
    correctAnswer: "a",
    explanation: "v-if действительно добавляет или удаляет элемент из DOM в зависимости от условия. Это важно отличать от простого скрытия: когда условие false, компонента или элемента физически нет в дереве. На собеседовании часто спрашивают разницу между v-if и v-show: v-if дороже при частом переключении, но не держит лишний DOM. Пример: `<section v-if=\"isReady\">Готово</section>` появится только тогда, когда isReady станет true.",
    knowledgeId: "knowledge-vue-basics-q1",
  },
  {
    id: 2,
    moduleId: "vue-basics",
    type: "BestPractice",
    difficulty: "Junior",
    tags: [
      "script-setup",
      "typescript",
      "composition-api",
    ],
    question: "Какой синтаксис чаще всего используют для компонентов Vue 3 с TypeScript?",
    answers: [
      { id: "a", text: "Options API с объектом methods" },
      { id: "b", text: "<script setup lang=\"ts\">" },
      { id: "c", text: "Только обычный JavaScript без TypeScript" },
      { id: "d", text: "Класс-компоненты Vue" },
    ],
    correctAnswer: "b",
    explanation: "`<script setup lang=\"ts\">` — современный синтаксис Vue 3 для компонентов на Composition API и TypeScript. Такой формат короче обычного `setup()` и хорошо типизируется без лишнего boilerplate. Он делает props, emits, imports и локальные функции сразу доступными в шаблоне. На собеседовании важно объяснить, что это компиляторный синтаксис поверх Composition API, а не отдельная модель компонентов.",
    knowledgeId: "knowledge-vue-basics-q2",
  },
  {
    id: 3,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "reactivity",
      "ref",
      "composition-api",
    ],
    question: "Для чего используется ref во Vue?",
    answers: [
      { id: "a", text: "Для регистрации маршрутов" },
      { id: "b", text: "Для установки зависимостей" },
      { id: "c", text: "Для создания реактивного значения" },
      { id: "d", text: "Для удаления компонента" },
    ],
    correctAnswer: "c",
    explanation: "ref создает реактивную обертку вокруг значения, чтобы Vue мог отслеживать изменения и обновлять интерфейс. В `<script setup>` значение читается и меняется через `.value`, например: `const count = ref(0); count.value += 1`. В шаблоне `.value` писать не нужно, Vue разворачивает ref автоматически. Это базовая тема для собеседований, потому что без понимания ref сложно объяснить реактивность Composition API.",
    knowledgeId: "knowledge-vue-basics-q3",
  },
  {
    id: 4,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "template",
      "directive",
      "lists",
      "key",
    ],
    question: "Что делает v-for?",
    answers: [
      { id: "a", text: "Показывает элемент только один раз" },
      { id: "b", text: "Создает переход между страницами" },
      { id: "c", text: "Останавливает реактивность" },
      { id: "d", text: "Рендерит список элементов на основе коллекции" },
    ],
    correctAnswer: "d",
    explanation: "v-for нужен для рендера списка по массиву или другой коллекции. Важно помнить про `key`: он помогает Vue правильно сопоставлять элементы при обновлениях и не ломать состояние дочерних компонентов. Типичный пример: `<li v-for=\"item in items\" :key=\"item.id\">{{ item.title }}</li>`. На интервью хороший ответ обычно включает не только \"рендерит список\", но и объяснение зачем нужен стабильный ключ.",
    knowledgeId: "knowledge-vue-basics-q4",
  },
  {
    id: 5,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "components",
      "props",
      "data-flow",
    ],
    question: "Как передать данные из родительского компонента в дочерний?",
    answers: [
      { id: "a", text: "Через props" },
      { id: "b", text: "Через localStorage напрямую" },
      { id: "c", text: "Через npm script" },
      { id: "d", text: "Через vite.config.ts" },
    ],
    correctAnswer: "a",
    explanation: "Props — основной способ передать данные сверху вниз: от родителя к дочернему компоненту. Это делает компонент предсказуемым, потому что источник данных явно виден в месте использования. Например: `<UserCard :name=\"player.name\" />`, а внутри дочернего компонента можно описать `defineProps<{ name: string }>()`. На собеседовании важно добавить, что props не стоит мутировать напрямую в дочернем компоненте.",
    knowledgeId: "knowledge-vue-basics-q5",
  },
  {
    id: 6,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "reactivity",
      "computed",
      "derived-state",
    ],
    question: "Что такое computed?",
    answers: [
      { id: "a", text: "Функция для установки роутера" },
      { id: "b", text: "Производное реактивное значение с кешированием" },
      { id: "c", text: "Способ импортировать CSS" },
      { id: "d", text: "Команда для сборки приложения" },
    ],
    correctAnswer: "b",
    explanation: "computed — это производное значение, которое зависит от реактивных источников и кешируется до их изменения. Это удобно, когда значение можно вычислить из уже существующего состояния, например: `const fullName = computed(() => firstName.value + \" \" + lastName.value)`. В отличие от обычной функции, computed не пересчитывается без необходимости. На интервью это часто проверяет понимание разницы между состоянием, производным состоянием и методами.",
    knowledgeId: "knowledge-vue-basics-q6",
  },
  {
    id: 7,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "events",
      "template",
      "v-on",
    ],
    question: "Как во Vue обозначить обработчик клика в шаблоне?",
    answers: [
      { id: "a", text: "#click" },
      { id: "b", text: "$click" },
      { id: "c", text: "@click" },
      { id: "d", text: "click()" },
    ],
    correctAnswer: "c",
    explanation: "@click — это короткая запись для `v-on:click`, то есть подписка на событие клика. Например: `<button @click=\"save\">Сохранить</button>`. Такой синтаксис используется не только для click, но и для других событий: `@input`, `@submit`, `@keydown`. Хороший практический нюанс: для форм часто нужен модификатор `@submit.prevent`, чтобы не перезагружать страницу.",
    knowledgeId: "knowledge-vue-basics-q7",
  },
  {
    id: 8,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "forms",
      "v-model",
      "two-way-binding",
    ],
    question: "Что делает v-model?",
    answers: [
      { id: "a", text: "Сортирует массив автоматически" },
      { id: "b", text: "Создает новый маршрут" },
      { id: "c", text: "Отключает компонент" },
      { id: "d", text: "Создает двустороннюю привязку данных" },
    ],
    correctAnswer: "d",
    explanation: "v-model связывает значение поля формы с реактивным состоянием и обновляет его при вводе пользователя. Например: `<input v-model=\"playerName\" />` синхронизирует input и переменную playerName. Это не магия, а удобная форма для value + update-события. На собеседовании полезно сказать, что для кастомных компонентов v-model тоже работает, если компонент поддерживает соответствующий prop и emit.",
    knowledgeId: "knowledge-vue-basics-q8",
  },
  {
    id: 9,
    moduleId: "vue-basics",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "architecture",
      "separation-of-concerns",
      "state",
    ],
    question: "Где не стоит хранить сложную игровую или бизнес-логику?",
    answers: [
      { id: "a", text: "Прямо внутри Vue-компонентов" },
      { id: "b", text: "В отдельных utils или stores" },
      { id: "c", text: "В типизированных data-файлах" },
      { id: "d", text: "В Pinia store" },
    ],
    correctAnswer: "a",
    explanation: "Сложную игровую или бизнес-логику не стоит хранить прямо внутри Vue-компонентов, потому что компоненты должны отвечать прежде всего за отображение и пользовательские действия. Если расчеты, правила доступа и проверка прогресса размазаны по компонентам, код быстро становится трудно тестировать и расширять. Правильнее держать глобальное состояние в store, данные в отдельных data-файлах, а чистые расчеты в utils или feature-модулях. Это зрелый архитектурный подход: UI можно менять, не переписывая правила поведения.",
    knowledgeId: "knowledge-vue-basics-q9",
  },
  {
    id: 10,
    moduleId: "vue-basics",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "pinia",
      "state-management",
      "global-state",
    ],
    question: "Что лучше использовать для глобального состояния игрока?",
    answers: [
      { id: "a", text: "Случайную глобальную переменную" },
      { id: "b", text: "Pinia" },
      { id: "c", text: "CSS-переменную" },
      { id: "d", text: "HTML data-атрибут" },
    ],
    correctAnswer: "b",
    explanation: "Для глобального состояния во Vue-приложении часто используют Pinia. Она дает понятную структуру store, реактивность, actions и удобную интеграцию с Vue Devtools. Случайная глобальная переменная может работать в маленьком демо, но плохо масштабируется и легко ломает синхронизацию интерфейса. Store подходит для данных, которые нужны нескольким экранам или компонентам, а сохранение в localStorage может сделать состояние устойчивым после перезагрузки.",
    knowledgeId: "knowledge-vue-basics-q10",
  },
  {
    id: 11,
    moduleId: "vue-basics",
    type: "CodeReview",
    difficulty: "Junior",
    tags: [
      "vue",
      "framework",
      "declarative-ui",
    ],
    question: "Какое описание Vue наиболее точное для собеседования?",
    answers: [
      { id: "a", text: "Библиотека только для HTTP-запросов" },
      { id: "b", text: "CSS-препроцессор для компонентных стилей" },
      { id: "c", text: "Прогрессивный JavaScript-фреймворк для декларативных интерфейсов" },
      { id: "d", text: "Сборщик проекта, который заменяет Vite" },
    ],
    correctAnswer: "c",
    explanation: "Vue корректнее описывать как прогрессивный JavaScript-фреймворк для создания интерфейсов. Он не ограничивается HTTP-запросами, не является CSS-инструментом и не заменяет сборщик. Слово \"прогрессивный\" означает, что Vue можно применять постепенно: от небольшого интерактивного блока до полноценного SPA. На интервью важно упомянуть декларативный рендеринг, реактивность и компонентную модель.",
    knowledgeId: "knowledge-vue-basics-q11",
  },
  {
    id: 12,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "declarative-rendering",
      "template",
      "state",
    ],
    question: "Что означает декларативный рендеринг во Vue?",
    answers: [
      { id: "a", text: "Разработчик вручную вызывает document.createElement для каждого изменения" },
      { id: "b", text: "Vue запрещает использовать JavaScript в компонентах" },
      { id: "c", text: "Компонент рендерится только один раз и больше не обновляется" },
      { id: "d", text: "Шаблон описывает, как UI должен выглядеть для текущего состояния" },
    ],
    correctAnswer: "d",
    explanation: "Декларативный рендеринг означает, что шаблон описывает результат, а Vue сам синхронизирует DOM с состоянием. Ручное создание DOM-узлов — это императивный подход, а не декларативный. JavaScript в компонентах разрешён, но он управляет данными и поведением, а не каждым DOM-шагом вручную. Компоненты обновляются при изменении реактивных зависимостей, поэтому ответ про одноразовый рендер неверен.",
    knowledgeId: "knowledge-vue-basics-q12",
  },
  {
    id: 13,
    moduleId: "vue-basics",
    type: "CodeOutput",
    difficulty: "Junior",
    tags: [
      "interpolation",
      "template-syntax",
      "ref",
    ],
    question: "Что отобразит шаблон `{{ message }}`, если `const message = ref(\"Привет\")`?",
    answers: [
      { id: "a", text: "Привет" },
      { id: "b", text: "[object Object]" },
      { id: "c", text: "message" },
      { id: "d", text: "Ничего, потому что в шаблоне нужно писать message.value" },
    ],
    correctAnswer: "a",
    explanation: "В шаблоне Vue автоматически разворачивает ref, поэтому `{{ message }}` выведет строку \"Привет\". В script setup для чтения ref нужен `.value`, но шаблон делает unwrapping сам. `[object Object]` не появится, потому что Vue не выводит объект ref напрямую в этом случае. Вариант с буквальным `message` неверен: интерполяция выполняет выражение, а не печатает его имя.",
    knowledgeId: "knowledge-vue-basics-q13",
  },
  {
    id: 14,
    moduleId: "vue-basics",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "template-syntax",
      "methods",
      "readability",
    ],
    question: "Как лучше поступить со сложным выражением внутри шаблона Vue?",
    answers: [
      { id: "a", text: "Оставить большую цепочку условий прямо в template" },
      { id: "b", text: "Вынести вычисление в computed или метод с понятным именем" },
      { id: "c", text: "Переписать компонент на обычный HTML без реактивности" },
      { id: "d", text: "Сохранить результат в глобальной переменной браузера" },
    ],
    correctAnswer: "b",
    explanation: "Сложные выражения лучше выносить в computed или метод, чтобы шаблон оставался читаемым. Большие условия прямо в template мешают ревью и повышают риск ошибки. Переписывать компонент на статический HTML не решает задачу, если значение зависит от состояния. Глобальная переменная ухудшает предсказуемость и не связана с реактивностью Vue.",
    knowledgeId: "knowledge-vue-basics-q14",
  },
  {
    id: 15,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "directives",
      "template",
      "v-prefix",
    ],
    question: "Что такое директивы Vue?",
    answers: [
      { id: "a", text: "Файлы конфигурации TypeScript" },
      { id: "b", text: "Только CSS-классы для стилизации компонентов" },
      { id: "c", text: "Специальные атрибуты шаблона, которые начинаются с v- и добавляют реактивное поведение" },
      { id: "d", text: "Методы жизненного цикла, которые вызываются один раз" },
    ],
    correctAnswer: "c",
    explanation: "Директивы Vue — это специальные атрибуты шаблона вроде `v-if`, `v-for`, `v-bind` и `v-on`. Они связывают DOM-поведение с реактивными данными или событиями. TypeScript-конфигурация и CSS-классы не являются директивами, хотя могут использоваться рядом с ними. Lifecycle hooks — отдельный механизм Composition API, а не атрибуты шаблона.",
    knowledgeId: "knowledge-vue-basics-q15",
  },
  {
    id: 16,
    moduleId: "vue-basics",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "v-if",
      "v-show",
      "performance",
    ],
    question: "Какую директиву выбрать для панели, которая переключается много раз в секунду?",
    answers: [
      { id: "a", text: "v-if, потому что он всегда быстрее при частом переключении" },
      { id: "b", text: "v-for, потому что переключение — это разновидность списка" },
      { id: "c", text: "v-model, потому что он управляет видимостью элементов" },
      { id: "d", text: "v-show, потому что элемент остаётся в DOM и меняется только видимость" },
    ],
    correctAnswer: "d",
    explanation: "Для частого переключения видимости обычно лучше подходит `v-show`, потому что элемент остаётся в DOM, а меняется CSS display. `v-if` создаёт и удаляет ветку, что может быть дороже при постоянных переключениях. `v-for` отвечает за списки, а не за видимость одного блока. `v-model` связывает значения формы и состояния, поэтому он не решает задачу переключения панели.",
    knowledgeId: "knowledge-vue-basics-q16",
  },
  {
    id: 17,
    moduleId: "vue-basics",
    type: "FindBug",
    difficulty: "JuniorPlus",
    tags: [
      "v-for",
      "key",
      "lists",
    ],
    question: "В чём проблема кода `<li v-for=\"todo in todos\">{{ todo.title }}</li>` для динамического списка?",
    answers: [
      { id: "a", text: "Не указан стабильный :key для элементов списка" },
      { id: "b", text: "v-for нельзя использовать с массивами объектов" },
      { id: "c", text: "Интерполяция {{ todo.title }} запрещена внутри li" },
      { id: "d", text: "Нужно заменить li на div, иначе Vue не обновит DOM" },
    ],
    correctAnswer: "a",
    explanation: "Для динамического списка нужно указывать стабильный `:key`, например `:key=\"todo.id\"`. Vue может рендерить массивы объектов через `v-for`, поэтому второй вариант неверен. Интерполяция внутри `li` допустима и является нормальным шаблонным синтаксисом. Тип HTML-тега не решает проблему сопоставления элементов при обновлении списка.",
    knowledgeId: "knowledge-vue-basics-q17",
  },
  {
    id: 18,
    moduleId: "vue-basics",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "key",
      "lists",
      "state",
    ],
    question: "Какой key лучше выбрать для списка пользователей?",
    answers: [
      { id: "a", text: ":key=\"index\", потому что индекс всегда есть" },
      { id: "b", text: ":key=\"user.id\", если id уникален и стабилен" },
      { id: "c", text: ":key=\"Math.random()\", чтобы Vue точно видел изменения" },
      { id: "d", text: "key не нужен, если список визуально короткий" },
    ],
    correctAnswer: "b",
    explanation: "Стабильный уникальный `user.id` — лучший вариант для динамического списка. Индекс массива может сломать соответствие DOM и данных при сортировке, фильтрации или удалении. `Math.random()` создаёт новый key на каждый рендер, из-за чего Vue будет лишний раз пересоздавать узлы. Длина списка не отменяет необходимость key, если элементы могут изменяться.",
    knowledgeId: "knowledge-vue-basics-q18",
  },
  {
    id: 19,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "event-binding",
      "v-on",
      "modifiers",
    ],
    question: "Что означает запись `@submit.prevent=\"save\"`?",
    answers: [
      { id: "a", text: "Создание нового computed-значения save" },
      { id: "b", text: "Однократный рендер формы без обновлений" },
      { id: "c", text: "Подписка на submit с отменой стандартного поведения формы" },
      { id: "d", text: "Привязка CSS-класса prevent к форме" },
    ],
    correctAnswer: "c",
    explanation: "`@submit` — сокращение для `v-on:submit`, а модификатор `.prevent` вызывает preventDefault. Это полезно для форм, чтобы браузер не перезагружал страницу при отправке. Computed-значения создаются в script, а не через обработчик события в шаблоне. CSS-классы привязывают через `:class`, поэтому вариант про класс неверен.",
    knowledgeId: "knowledge-vue-basics-q19",
  },
  {
    id: 20,
    moduleId: "vue-basics",
    type: "CodeOutput",
    difficulty: "Junior",
    tags: [
      "class-binding",
      "v-bind",
      "template",
    ],
    question: "Что делает запись `:class=\"{ active: isActive }\"`?",
    answers: [
      { id: "a", text: "Создаёт переменную active внутри script setup" },
      { id: "b", text: "Удаляет элемент из DOM, когда isActive ложно" },
      { id: "c", text: "Подписывает элемент на событие active" },
      { id: "d", text: "Добавляет класс active, когда isActive истинно" },
    ],
    correctAnswer: "d",
    explanation: "Объектный синтаксис `:class` добавляет класс, если значение соответствующего свойства истинно. Он не создаёт переменные в script setup и не управляет существованием элемента в DOM. Удаление элемента связано с `v-if`, а не с class binding. События подключаются через `v-on` или сокращение `@`, поэтому вариант про событие неверен.",
    knowledgeId: "knowledge-vue-basics-q20",
  },
  {
    id: 21,
    moduleId: "vue-basics",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "style-binding",
      "dynamic-style",
      "template",
    ],
    question: "Как лучше передать динамическую ширину прогресс-бара в Vue?",
    answers: [
      { id: "a", text: "Через `:style=\"{ width: progress + '%' }\"` или вычисленное style-значение" },
      { id: "b", text: "Через `@style`, потому что style — это событие" },
      { id: "c", text: "Через `v-for`, потому что width является числом" },
      { id: "d", text: "Через ручной поиск DOM-элемента в каждом рендере" },
    ],
    correctAnswer: "a",
    explanation: "Для динамических inline-стилей во Vue используют `:style`, которому можно передать объект или вычисленное значение. `@style` не является обработчиком события, а `v-for` нужен для списков. Ручной поиск DOM-элемента ради обычного style binding делает код хрупким и обходит декларативную модель. Для повторяемой логики форматирование стилей можно вынести в computed.",
    knowledgeId: "knowledge-vue-basics-q21",
  },
  {
    id: 22,
    moduleId: "vue-basics",
    type: "FindBug",
    difficulty: "JuniorPlus",
    tags: [
      "v-model",
      "forms",
      "ref",
    ],
    question: "Почему `v-model=\"name.value\"` обычно является ошибкой в шаблоне, если `name` создан через ref?",
    answers: [
      { id: "a", text: "v-model не работает с input" },
      { id: "b", text: "В шаблоне ref разворачивается автоматически, поэтому обычно пишут `v-model=\"name\"`" },
      { id: "c", text: "ref нельзя использовать для строк" },
      { id: "d", text: "v-model работает только с CSS-свойствами" },
    ],
    correctAnswer: "b",
    explanation: "В шаблонах Vue ref автоматически разворачивается, поэтому для input обычно пишут `v-model=\"name\"`. `v-model` как раз предназначен для input, textarea, select и кастомных компонентов. ref можно использовать со строками, числами, объектами и другими значениями. CSS-свойства к v-model не относятся; для стилей используется `:style`.",
    knowledgeId: "knowledge-vue-basics-q22",
  },
  {
    id: 23,
    moduleId: "vue-basics",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "computed",
      "methods",
      "performance",
    ],
    question: "Когда computed предпочтительнее метода?",
    answers: [
      { id: "a", text: "Когда нужно выполнить HTTP-запрос при клике" },
      { id: "b", text: "Когда функция обязательно должна принимать аргументы из шаблона" },
      { id: "c", text: "Когда нужно кешируемое значение, зависящее от реактивного состояния" },
      { id: "d", text: "Когда нужно напрямую изменить DOM-узел" },
    ],
    correctAnswer: "c",
    explanation: "computed подходит для производных значений, которые зависят от реактивных источников и могут кешироваться. HTTP-запрос при клике — действие, поэтому его лучше оформлять как метод или action. Если функция должна принимать разные аргументы, обычный метод часто проще. Прямое изменение DOM обычно не является задачей computed и может нарушить декларативность.",
    knowledgeId: "knowledge-vue-basics-q23",
  },
  {
    id: 24,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "methods",
      "template",
      "events",
    ],
    question: "Для чего обычно используют methods или обычные функции в script setup?",
    answers: [
      { id: "a", text: "Только для объявления props" },
      { id: "b", text: "Для автоматического кеширования любого значения" },
      { id: "c", text: "Для регистрации CSS-переменных в браузере" },
      { id: "d", text: "Для действий: обработчиков событий, команд и операций с параметрами" },
    ],
    correctAnswer: "d",
    explanation: "Обычные функции в script setup часто используют для действий: обработать клик, отправить форму, изменить локальное состояние или выполнить операцию с параметром. Props объявляют через defineProps, а не через methods. Автоматическое кеширование производных значений — задача computed. CSS-переменные не регистрируются через методы Vue как отдельный механизм.",
    knowledgeId: "knowledge-vue-basics-q24",
  },
  {
    id: 25,
    moduleId: "vue-basics",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "watch",
      "side-effects",
      "reactivity",
    ],
    question: "Когда watch подходит лучше, чем computed?",
    answers: [
      { id: "a", text: "Когда нужно выполнить побочный эффект при изменении реактивного значения" },
      { id: "b", text: "Когда нужно просто вывести форматированную строку в шаблоне" },
      { id: "c", text: "Когда нужно заменить все props в компоненте" },
      { id: "d", text: "Когда нужно отключить реактивность ref" },
    ],
    correctAnswer: "a",
    explanation: "watch используют для реакции на изменение значения, особенно когда нужен побочный эффект: запрос, синхронизация, логирование или сохранение. Форматированная строка без side effect лучше подходит для computed. watch не заменяет props и не должен использоваться как универсальный способ передачи данных. Отключение реактивности ref не является задачей watch.",
    knowledgeId: "knowledge-vue-basics-q25",
  },
  {
    id: 26,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "components",
      "composition",
      "reuse",
    ],
    question: "Зачем во Vue разделять интерфейс на компоненты?",
    answers: [
      { id: "a", text: "Чтобы запретить реактивность внутри интерфейса" },
      { id: "b", text: "Чтобы изолировать ответственность, переиспользовать UI и упростить поддержку" },
      { id: "c", text: "Чтобы каждый файл обязательно содержал весь экран целиком" },
      { id: "d", text: "Чтобы браузер перестал выполнять JavaScript" },
    ],
    correctAnswer: "b",
    explanation: "Компоненты помогают делить интерфейс на понятные части с ограниченной ответственностью. Это упрощает переиспользование, тестирование и поддержку. Реактивность внутри компонентов сохраняется, поэтому второй вариант неверен. Большие файлы на весь экран обычно ухудшают читаемость, а не являются целью компонентной модели.",
    knowledgeId: "knowledge-vue-basics-q26",
  },
  {
    id: 27,
    moduleId: "vue-basics",
    type: "FindBug",
    difficulty: "JuniorPlus",
    tags: [
      "props",
      "data-flow",
      "immutability",
    ],
    question: "Что не так с попыткой изменить prop напрямую внутри дочернего компонента?",
    answers: [
      { id: "a", text: "Props доступны только в Options API" },
      { id: "b", text: "Props можно читать только в CSS" },
      { id: "c", text: "Prop принадлежит родителю, поэтому дочерний компонент должен отправить событие или использовать локальную копию" },
      { id: "d", text: "Vue не позволяет передавать строки через props" },
    ],
    correctAnswer: "c",
    explanation: "Prop — входное значение дочернего компонента, источник которого находится у родителя. Прямое изменение prop нарушает однонаправленный поток данных и может быть перезаписано следующим обновлением родителя. Props доступны и в Composition API через defineProps. Строки, числа, объекты и другие значения можно передавать через props, если контракт компонента это допускает.",
    knowledgeId: "knowledge-vue-basics-q27",
  },
  {
    id: 28,
    moduleId: "vue-basics",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "emits",
      "events",
      "child-to-parent",
    ],
    question: "Как дочерний компонент обычно сообщает родителю о действии пользователя?",
    answers: [
      { id: "a", text: "Через прямую мутацию всех props родителя" },
      { id: "b", text: "Через изменение vite.config.ts" },
      { id: "c", text: "Через автоматическое создание глобальной переменной" },
      { id: "d", text: "Через emit-событие, объявленное в defineEmits" },
    ],
    correctAnswer: "d",
    explanation: "Дочерний компонент обычно сообщает о событии через emit, а родитель решает, как изменить состояние. Это сохраняет однонаправленный поток данных: props вниз, события вверх. Прямая мутация props родителя нарушает границы ответственности. Конфиг сборщика и глобальные переменные не являются нормальным способом связи компонентов.",
    knowledgeId: "knowledge-vue-basics-q28",
  },
  {
    id: 29,
    moduleId: "vue-basics",
    type: "Interview",
    difficulty: "Junior",
    tags: [
      "sfc",
      "single-file-component",
      "vue-file",
    ],
    question: "На code review спрашивают: что важно проверить в Single File Component во Vue?",
    answers: [
      { id: "a", text: "Файл .vue, который обычно объединяет template, script и style одного компонента" },
      { id: "b", text: "Файл package.json с настройками зависимостей" },
      { id: "c", text: "Любой CSS-файл, импортированный в main.ts" },
      { id: "d", text: "HTML-файл, который Vue никогда не компилирует" },
    ],
    correctAnswer: "a",
    explanation: "Single File Component — это `.vue` файл, где рядом находятся шаблон, логика и стили компонента. Такой формат помогает держать связанную часть интерфейса в одном месте. `package.json` управляет зависимостями, но не является Vue-компонентом. CSS-файл и статический HTML не дают той же SFC-структуры с template/script/style.",
    knowledgeId: "knowledge-vue-basics-q29",
  },
  {
    id: 30,
    moduleId: "vue-basics",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "virtual-dom",
      "reactivity",
      "rendering",
    ],
    question: "Как связаны реактивность Vue и virtual DOM?",
    answers: [
      { id: "a", text: "Virtual DOM полностью отключает реактивность ref и computed" },
      { id: "b", text: "Реактивность отслеживает изменения данных, а renderer обновляет нужные части DOM через виртуальное представление" },
      { id: "c", text: "Реактивность работает только для CSS, а virtual DOM только для HTML-файлов" },
      { id: "d", text: "Vue обновляет весь document.body при каждом изменении любого ref" },
    ],
    correctAnswer: "b",
    explanation: "Реактивность сообщает Vue, какие зависимости изменились, а renderer пересчитывает представление компонента и применяет нужные обновления к DOM. Virtual DOM не отключает ref и computed, а помогает эффективно сравнивать результат рендера. Реактивность не ограничена CSS, она связана с данными компонента. Vue не обязан перерисовывать весь document.body при каждом изменении; обновление ограничивается затронутыми частями дерева.",
    knowledgeId: "knowledge-vue-basics-q30",
  },
]
