import type { ContentQuestion } from '../../../types/content'

export const serverApiQuestions: ContentQuestion[] = [
  {
    id: 1001,
    moduleId: "server-api",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "server-api",
      "server/api",
      "nuxt",
    ],
    question: "Что создаёт файл server/api/users.get.ts в Nuxt 3?",
    answers: [
      { id: "a", text: "HTTP endpoint, доступный по пути /api/users для GET-запросов." },
      { id: "b", text: "Vue-компонент страницы /users." },
      { id: "c", text: "Клиентский composable useUsers." },
      { id: "d", text: "Статический файл, который отдаётся из public." },
    ],
    correctAnswer: "a",
    explanation: "Папка server/api создаёт серверные endpoint-файлы. Суффикс .get ограничивает обработчик GET-методом, а путь файла становится URL внутри /api. Компоненты, composables и public решают другие задачи.",
    knowledgeId: "server-api-1001",
  },
  {
    id: 1002,
    moduleId: "server-api",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "defineEventHandler",
      "eventHandler",
      "h3",
    ],
    question: "Для чего используется defineEventHandler в Nuxt Server API?",
    answers: [
      { id: "a", text: "Для объявления Vue lifecycle hook." },
      { id: "b", text: "Для объявления серверного обработчика запроса на базе H3/Nitro." },
      { id: "c", text: "Для регистрации глобального CSS." },
      { id: "d", text: "Для создания client-only компонента." },
    ],
    correctAnswer: "b",
    explanation: "defineEventHandler описывает функцию, которая принимает серверное событие и возвращает ответ. Это слой H3/Nitro, а не Vue lifecycle, CSS или клиентская регистрация.",
    knowledgeId: "server-api-1002",
  },
  {
    id: 1003,
    moduleId: "server-api",
    type: "CodeOutput",
    difficulty: "Junior",
    tags: [
      "query",
      "getQuery",
      "request",
    ],
    question: "Что вернёт endpoint, если вызвать /api/search?q=vue?",
    answers: [
      { id: "a", text: "{ \"query\": undefined }" },
      { id: "b", text: "{ \"q\": \"/api/search\" }" },
      { id: "c", text: "{ \"query\": \"vue\" }" },
      { id: "d", text: "Ошибка, потому что query нельзя читать на сервере." },
    ],
    correctAnswer: "c",
    explanation: "getQuery(event) читает query string текущего запроса. Значение параметра q будет доступно как query.q, поэтому endpoint может вернуть его в JSON-ответе.",
    knowledgeId: "server-api-1003",
  },
  {
    id: 1004,
    moduleId: "server-api",
    type: "Scenario",
    difficulty: "Junior",
    tags: [
      "body",
      "readBody",
      "post",
    ],
    question: "Нужно принять JSON body в POST endpoint. Какой helper подходит лучше всего?",
    answers: [
      { id: "a", text: "getQuery(event)" },
      { id: "b", text: "getRouterParam(event, \"id\")" },
      { id: "c", text: "setResponseHeader(event, \"Content-Type\", \"application/json\")" },
      { id: "d", text: "readBody(event)" },
    ],
    correctAnswer: "d",
    explanation: "readBody(event) читает тело запроса и подходит для POST, PUT и PATCH payload. getQuery работает с query string, getRouterParam — с параметрами маршрута, а setResponseHeader управляет заголовком ответа. Разделение этих API важно: оно помогает не смешивать тело запроса, URL-параметры и response metadata.",
    knowledgeId: "server-api-1004",
  },
  {
    id: 1005,
    moduleId: "server-api",
    type: "FindBug",
    difficulty: "Junior",
    tags: [
      "response",
      "setResponseStatus",
      "errors",
    ],
    question: "Endpoint создаёт пользователя, но всегда возвращает HTTP 200. Что лучше исправить для успешного создания?",
    answers: [
      { id: "a", text: "Установить статус 201 через setResponseStatus(event, 201)." },
      { id: "b", text: "Перенести endpoint в components." },
      { id: "c", text: "Вернуть строку \"created\" вместо объекта." },
      { id: "d", text: "Добавить query-параметр status=201." },
    ],
    correctAnswer: "a",
    explanation: "Для созданного ресурса корректным ответом часто является 201 Created. setResponseStatus управляет HTTP-статусом ответа; query-параметр или строковый body не меняют статус протокола.",
    knowledgeId: "server-api-1005",
  },
  {
    id: 1006,
    moduleId: "server-api",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "validation",
      "body",
      "security",
    ],
    question: "Какая практика важна при чтении body в Server API?",
    answers: [
      { id: "a", text: "Считать body всегда доверенным, потому что endpoint серверный." },
      { id: "b", text: "Валидировать входные данные до выполнения бизнес-действия." },
      { id: "c", text: "Хранить body в runtimeConfig." },
      { id: "d", text: "Передавать body в cookie без проверки." },
    ],
    correctAnswer: "b",
    explanation: "Server API находится на сервере, но входные данные всё равно приходят от клиента или внешней системы. Их нужно валидировать, нормализовать и только затем использовать в бизнес-логике.",
    knowledgeId: "server-api-1006",
  },
  {
    id: 1007,
    moduleId: "server-api",
    type: "Interview",
    difficulty: "JuniorPlus",
    tags: [
      "server-api",
      "backend",
      "bff",
    ],
    question: "Как корректно объяснить Server API Nuxt на интервью?",
    answers: [
      { id: "a", text: "Это замена всем backend-сервисам в любой архитектуре." },
      { id: "b", text: "Это способ писать Vue-компоненты без template." },
      { id: "c", text: "Это серверные endpoint-обработчики внутри Nuxt/Nitro, которые могут выполнять BFF-задачи и безопасно работать с приватной конфигурацией." },
      { id: "d", text: "Это клиентская обёртка над fetch." },
    ],
    correctAnswer: "c",
    explanation: "Server API позволяет писать серверные endpoints рядом с Nuxt-приложением. Он полезен для BFF, proxy, auth и работы с секретами, но не всегда заменяет полноценный backend-домен.",
    knowledgeId: "server-api-1007",
  },
  {
    id: 1008,
    moduleId: "server-api",
    type: "CodeReview",
    difficulty: "JuniorPlus",
    tags: [
      "params",
      "getRouterParam",
      "review",
    ],
    question: "На review видно, что id ресурса читается из query в endpoint /api/users/[id].get.ts. Что лучше предложить?",
    answers: [
      { id: "a", text: "Оставить query, потому что params в server/api не поддерживаются." },
      { id: "b", text: "Перенести id в cookie." },
      { id: "c", text: "Хранить id в nuxt.config.ts." },
      { id: "d", text: "Читать id через getRouterParam(event, \"id\"), потому что он является параметром маршрута." },
    ],
    correctAnswer: "d",
    explanation: "Динамический сегмент [id] является route param, а не query string. getRouterParam делает намерение явным и лучше соответствует структуре endpoint-файла. Query используют для фильтров и настроек запроса, а path param обычно описывает конкретный ресурс.",
    knowledgeId: "server-api-1008",
  },
  {
    id: 1009,
    moduleId: "server-api",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "cookies",
      "auth",
      "security",
    ],
    question: "Endpoint должен сохранить session id в cookie. Какой helper Nuxt/H3 подходит?",
    answers: [
      { id: "a", text: "setCookie(event, \"session\", value, options)" },
      { id: "b", text: "setResponseStatus(event, value)" },
      { id: "c", text: "readBody(event, \"session\")" },
      { id: "d", text: "getQuery(event).cookie = value" },
    ],
    correctAnswer: "a",
    explanation: "setCookie управляет cookie в ответе. Статус ответа, body и query-параметры не устанавливают cookie браузера и не позволяют задать security options.",
    knowledgeId: "server-api-1009",
  },
  {
    id: 1010,
    moduleId: "server-api",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "nitro",
      "server-engine",
    ],
    question: "Что такое Nitro в Nuxt 3?",
    answers: [
      { id: "a", text: "CSS-препроцессор для Nuxt." },
      { id: "b", text: "Серверный engine, который отвечает за server runtime, API routes и сборку под разные deployment targets." },
      { id: "c", text: "State manager для Vue." },
      { id: "d", text: "Библиотека UI-компонентов." },
    ],
    correctAnswer: "b",
    explanation: "Nitro — серверный слой Nuxt. Он обрабатывает server routes, runtime и deployment presets; CSS, state management и UI-компоненты относятся к другим инструментам.",
    knowledgeId: "server-api-1010",
  },
  {
    id: 1011,
    moduleId: "server-api",
    type: "Architecture",
    difficulty: "JuniorPlus",
    tags: [
      "bff",
      "architecture",
      "server-api",
    ],
    question: "Какая задача хорошо подходит для BFF-слоя на Nuxt Server API?",
    answers: [
      { id: "a", text: "Хранить все Vue-компоненты." },
      { id: "b", text: "Заменять CSS modules." },
      { id: "c", text: "Адаптировать внешний backend API под потребности frontend и скрыть приватные ключи." },
      { id: "d", text: "Дублировать всю базу данных в cookie." },
    ],
    correctAnswer: "c",
    explanation: "BFF помогает frontend получить удобный контракт и не раскрывать секреты клиенту. Он может агрегировать несколько backend-ответов, нормализовать данные и централизовать обработку ошибок. Компоненты, стили и cookie-хранилище сами по себе не являются задачами BFF-архитектуры.",
    knowledgeId: "server-api-1011",
  },
  {
    id: 1012,
    moduleId: "server-api",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "params",
      "dynamic-routes",
      "server/api",
    ],
    question: "Что вернёт endpoint server/api/posts/[slug].get.ts при запросе /api/posts/nuxt-nitro?",
    answers: [
      { id: "a", text: "{ \"slug\": undefined }" },
      { id: "b", text: "{ \"slug\": \"/api/posts/nuxt-nitro\" }" },
      { id: "c", text: "404, потому что server/api не поддерживает динамические сегменты." },
      { id: "d", text: "{ \"slug\": \"nuxt-nitro\" }" },
    ],
    correctAnswer: "d",
    explanation: "Динамический сегмент [slug] доступен через getRouterParam(event, \"slug\"). Значение будет `nuxt-nitro`, а не полный URL и не query-параметр. Это важно для проектирования REST-like endpoint: идентичность ресурса обычно находится в path params, а фильтры и режимы отображения — в query string.",
    knowledgeId: "server-api-1012",
  },
  {
    id: 1013,
    moduleId: "server-api",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "runtimeConfig",
      "secrets",
      "security",
    ],
    question: "API token положили в runtimeConfig.public, чтобы вызвать внешний сервис из Server API. В чём ошибка?",
    answers: [
      { id: "a", text: "public runtimeConfig доступен клиенту, поэтому секрет должен храниться в приватной части runtimeConfig." },
      { id: "b", text: "Server API вообще не может читать runtimeConfig." },
      { id: "c", text: "Все токены должны храниться только в query string." },
      { id: "d", text: "Нужно перенести токен в assets." },
    ],
    correctAnswer: "a",
    explanation: "Секреты нельзя помещать в public, потому что публичная конфигурация доступна клиентскому коду. Server API может читать приватную конфигурацию и использовать её без раскрытия браузеру.",
    knowledgeId: "server-api-1013",
  },
  {
    id: 1014,
    moduleId: "server-api",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "createError",
      "errors",
      "http",
    ],
    question: "Как лучше вернуть контролируемую ошибку 404 из Server API?",
    answers: [
      { id: "a", text: "return null без статуса." },
      { id: "b", text: "throw createError({ statusCode: 404, statusMessage: \"Not Found\" })" },
      { id: "c", text: "return { error: true } всегда со статусом 200." },
      { id: "d", text: "setCookie(event, \"error\", \"404\")." },
    ],
    correctAnswer: "b",
    explanation: "createError создаёт HTTP-ошибку с корректным статусом. Ответ 200 с error-флагом хуже для клиентов, мониторинга и кеширования, потому что протокол сообщает неверный результат.",
    knowledgeId: "server-api-1014",
  },
  {
    id: 1015,
    moduleId: "server-api",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "nitro",
      "presets",
      "deployment",
    ],
    question: "Что такое Nitro presets?",
    answers: [
      { id: "a", text: "Набор CSS-тем для Nuxt." },
      { id: "b", text: "Список Vue Router guards." },
      { id: "c", text: "Настройки сборки Nitro под разные runtime targets: node, serverless, edge и платформы деплоя." },
      { id: "d", text: "Формат именования компонентов." },
    ],
    correctAnswer: "c",
    explanation: "Nitro умеет собирать серверный runtime под разные окружения. Preset определяет, как упаковать и запустить приложение на конкретной платформе или типе runtime.",
    knowledgeId: "server-api-1015",
  },
  {
    id: 1016,
    moduleId: "server-api",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "proxy",
      "bff",
      "external-api",
    ],
    question: "Frontend должен обращаться к внешнему API, но API key нельзя отдавать в браузер. Какой подход подходит?",
    answers: [
      { id: "a", text: "Положить ключ в localStorage." },
      { id: "b", text: "Добавить ключ в public runtimeConfig." },
      { id: "c", text: "Передать ключ через query-параметр из клиента." },
      { id: "d", text: "Создать Server API endpoint, прочитать приватный ключ из runtimeConfig и вызвать внешний API на сервере." },
    ],
    correctAnswer: "d",
    explanation: "Server API может выступать proxy/BFF и скрывать секрет от клиента. localStorage, public config и query string раскрывают ключ или делают его легко перехватываемым.",
    knowledgeId: "server-api-1016",
  },
  {
    id: 1017,
    moduleId: "server-api",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "crud",
      "rest",
      "review",
    ],
    question: "На review endpoint users.post.ts создаёт пользователя, но не проверяет email и password. Что важно исправить первым?",
    answers: [
      { id: "a", text: "Добавить явную валидацию body до создания пользователя." },
      { id: "b", text: "Переименовать файл в users.vue." },
      { id: "c", text: "Вернуть всегда HTTP 200." },
      { id: "d", text: "Сохранить body целиком в cookie." },
    ],
    correctAnswer: "a",
    explanation: "CRUD endpoint должен проверять входные данные до изменения состояния. Переименование, статус 200 и cookie не решают проблему небезопасного ввода. В production важно валидировать payload, явно обрабатывать ошибки и не доверять данным, пришедшим от клиента.",
    knowledgeId: "server-api-1017",
  },
  {
    id: 1018,
    moduleId: "server-api",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "nitro-middleware",
      "server/middleware",
    ],
    question: "Для чего используется server/middleware в Nitro/Nuxt?",
    answers: [
      { id: "a", text: "Для Vue route middleware на клиентской навигации." },
      { id: "b", text: "Для серверной логики, выполняемой до route handler: логирование, общие заголовки, базовые проверки." },
      { id: "c", text: "Для хранения статических изображений." },
      { id: "d", text: "Для автоматического создания Pinia store." },
    ],
    correctAnswer: "b",
    explanation: "server/middleware относится к серверному pipeline Nitro. Он отличается от route middleware страниц и подходит для общих серверных задач перед обработчиком.",
    knowledgeId: "server-api-1018",
  },
  {
    id: 1019,
    moduleId: "server-api",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "routeRules",
      "caching",
      "nitro",
    ],
    question: "Какую задачу решают routeRules в Nuxt/Nitro?",
    answers: [
      { id: "a", text: "Описывают props Vue-компонентов." },
      { id: "b", text: "Создают миграции базы данных." },
      { id: "c", text: "Позволяют задать правила для маршрутов: caching, headers, redirects или поведение рендера/прокси." },
      { id: "d", text: "Заменяют TypeScript-типы." },
    ],
    correctAnswer: "c",
    explanation: "routeRules задают инфраструктурное поведение маршрутов: caching, prerender, proxy, headers и другие настройки. Это Nitro/Nuxt-конфигурация уровня маршрута, а не описание компонентов, базы данных или TypeScript-типов. На практике routeRules связывают URL-паттерн с runtime-поведением.",
    knowledgeId: "server-api-1019",
  },
  {
    id: 1020,
    moduleId: "server-api",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "headers",
      "getHeader",
      "request",
    ],
    question: "Какой helper подходит для чтения заголовка authorization из Server API event?",
    answers: [
      { id: "a", text: "readBody(event).authorization" },
      { id: "b", text: "getRouterParam(event, \"authorization\")" },
      { id: "c", text: "setResponseStatus(event, \"authorization\")" },
      { id: "d", text: "getHeader(event, \"authorization\")" },
    ],
    correctAnswer: "d",
    explanation: "HTTP-заголовки читаются через getHeader. Body, params и status — разные части запроса/ответа и не должны использоваться для чтения authorization header.",
    knowledgeId: "server-api-1020",
  },
  {
    id: 1021,
    moduleId: "server-api",
    type: "FindBug",
    difficulty: "MiddlePlus",
    tags: [
      "cookies",
      "security",
      "auth",
    ],
    question: "Session cookie выставляется без httpOnly и secure. Что не так с таким решением?",
    answers: [
      { id: "a", text: "Cookie становится более уязвимой: её легче прочитать из JS и передать по небезопасному каналу." },
      { id: "b", text: "Cookie перестанет отправляться на сервер в любом браузере." },
      { id: "c", text: "Nuxt не поддерживает security options для cookies." },
      { id: "d", text: "Нужно заменить cookie на query-параметр." },
    ],
    correctAnswer: "a",
    explanation: "Для session cookie важны флаги безопасности: httpOnly ограничивает доступ из JS, secure требует HTTPS, sameSite снижает CSRF-риски. Query-параметр ещё хуже для секрета.",
    knowledgeId: "server-api-1021",
  },
  {
    id: 1022,
    moduleId: "server-api",
    type: "BestPractice",
    difficulty: "MiddlePlus",
    tags: [
      "caching",
      "routeRules",
      "performance",
    ],
    question: "Что важно учитывать при включении caching для API route?",
    answers: [
      { id: "a", text: "Кешировать все POST-запросы без исключений." },
      { id: "b", text: "Кешировать только ответы, которые безопасно переиспользовать, и учитывать пользователя, авторизацию и freshness данных." },
      { id: "c", text: "Кешировать ответы с приватными данными одинаково для всех пользователей." },
      { id: "d", text: "Игнорировать HTTP status при кешировании." },
    ],
    correctAnswer: "b",
    explanation: "Кеширование ускоряет систему, но может раскрыть приватные данные или отдать устаревший ответ. Нужно понимать ключ кеша, пользователя, метод запроса и допустимую свежесть.",
    knowledgeId: "server-api-1022",
  },
  {
    id: 1023,
    moduleId: "server-api",
    type: "Interview",
    difficulty: "MiddlePlus",
    tags: [
      "edge",
      "serverless",
      "node",
      "deployment",
    ],
    question: "Как кратко сравнить node, serverless и edge runtime для Nitro?",
    answers: [
      { id: "a", text: "Это три названия одного и того же режима без различий." },
      { id: "b", text: "Edge всегда поддерживает любой Node API." },
      { id: "c", text: "Node даёт классический сервер, serverless запускает функции по запросу, edge приближает выполнение к пользователю с ограничениями среды." },
      { id: "d", text: "Serverless используется только для CSS." },
    ],
    correctAnswer: "c",
    explanation: "Deployment target влияет на startup, доступные API, latency и ограничения runtime. Edge может быть быстрым географически, но имеет ограничения; serverless и node тоже имеют свои trade-offs.",
    knowledgeId: "server-api-1023",
  },
  {
    id: 1024,
    moduleId: "server-api",
    type: "Scenario",
    difficulty: "MiddlePlus",
    tags: [
      "storage",
      "nitro",
      "cache",
    ],
    question: "Нужно хранить небольшой server-side cache, абстрагированный от конкретного deployment. Что в Nitro стоит рассмотреть?",
    answers: [
      { id: "a", text: "localStorage в браузере." },
      { id: "b", text: "Query string каждого запроса." },
      { id: "c", text: "CSS custom properties." },
      { id: "d", text: "Nitro storage с подходящим драйвером." },
    ],
    correctAnswer: "d",
    explanation: "Nitro storage предоставляет server-side абстракцию хранения. localStorage относится к браузеру, query string не является хранилищем, CSS-переменные не предназначены для данных.",
    knowledgeId: "server-api-1024",
  },
  {
    id: 1025,
    moduleId: "server-api",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "response",
      "status",
      "review",
    ],
    question: "Endpoint возвращает { ok: false, message: \"Forbidden\" } со статусом 200. Что лучше изменить?",
    answers: [
      { id: "a", text: "Возвращать корректный HTTP 403 через createError или setResponseStatus." },
      { id: "b", text: "Оставить 200, потому что body уже содержит ok: false." },
      { id: "c", text: "Переименовать message в errorMessage." },
      { id: "d", text: "Добавить cookie forbidden=true." },
    ],
    correctAnswer: "a",
    explanation: "HTTP-статус должен отражать результат запроса. 200 для forbidden-сценария ломает клиентов, мониторинг и retry/error handling, потому что ошибка выглядит как успешный ответ. Для запрета доступа нужен 403, а тело ответа может объяснять причину в безопасной форме.",
    knowledgeId: "server-api-1025",
  },
  {
    id: 1026,
    moduleId: "server-api",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "frontend-backend",
      "boundaries",
      "architecture",
    ],
    question: "Где лучше держать сложную доменную бизнес-логику крупного продукта?",
    answers: [
      { id: "a", text: "Всегда только в server/api, независимо от масштаба." },
      { id: "b", text: "В выделенном backend/domain layer, а Nuxt Server API использовать как BFF или тонкий adapter, если это соответствует архитектуре." },
      { id: "c", text: "В Vue template, чтобы логика была ближе к UI." },
      { id: "d", text: "В cookies, чтобы её видел браузер." },
    ],
    correctAnswer: "b",
    explanation: "Nuxt Server API удобен для BFF и умеренной серверной логики, но крупный backend-домен часто требует отдельного слоя. Граница зависит от команды, нагрузки, владения данными и требований безопасности.",
    knowledgeId: "server-api-1026",
  },
  {
    id: 1027,
    moduleId: "server-api",
    type: "Scenario",
    difficulty: "MiddlePlus",
    tags: [
      "authorization",
      "headers",
      "bff",
    ],
    question: "Нужно проверить Bearer token в Server API перед возвратом приватных данных. Что сделать первым?",
    answers: [
      { id: "a", text: "Вернуть данные, а проверку сделать на клиенте." },
      { id: "b", text: "Записать token в public runtimeConfig." },
      { id: "c", text: "Прочитать authorization header и провалидировать токен до доступа к данным." },
      { id: "d", text: "Игнорировать header, если endpoint находится в server/api." },
    ],
    correctAnswer: "c",
    explanation: "Доступ к приватным данным должен проверяться на сервере до выполнения действия. Клиентская проверка не является защитой, а public config не подходит для токенов.",
    knowledgeId: "server-api-1027",
  },
  {
    id: 1028,
    moduleId: "server-api",
    type: "CodeOutput",
    difficulty: "Senior",
    tags: [
      "createError",
      "statusCode",
      "errors",
    ],
    question: "Какой HTTP-статус получит клиент, если handler выполнит throw createError({ statusCode: 401 })?",
    answers: [
      { id: "a", text: "200" },
      { id: "b", text: "500 всегда, потому что это throw." },
      { id: "c", text: "204" },
      { id: "d", text: "401" },
    ],
    correctAnswer: "d",
    explanation: "createError позволяет выбросить контролируемую HTTP-ошибку с заданным statusCode и сообщением. Это не обычная непредвиденная ошибка 500, если statusCode указан корректно. Такой подход делает endpoint предсказуемым для клиента и сохраняет единый стиль error handling.",
    knowledgeId: "server-api-1028",
  },
  {
    id: 1029,
    moduleId: "server-api",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "security",
      "runtimeConfig",
      "secrets",
    ],
    question: "Почему private runtimeConfig важен для Server API?",
    answers: [
      { id: "a", text: "Он позволяет серверному коду использовать секреты без раскрытия клиентскому bundle." },
      { id: "b", text: "Он автоматически шифрует любые данные в базе." },
      { id: "c", text: "Он делает endpoint доступным только администраторам." },
      { id: "d", text: "Он заменяет валидацию входных данных." },
    ],
    correctAnswer: "a",
    explanation: "Private runtimeConfig нужен для секретов и environment values, доступных серверному коду. Он не отправляется в клиентский bundle, поэтому подходит для API keys и server-only настроек. При этом он не заменяет авторизацию, шифрование данных или валидацию входящих запросов.",
    knowledgeId: "server-api-1029",
  },
  {
    id: 1030,
    moduleId: "server-api",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "anti-patterns",
      "bff",
      "review",
    ],
    question: "На review Server API endpoint просто проксирует внешний API без фильтрации, авторизации и обработки ошибок. Что главная проблема?",
    answers: [
      { id: "a", text: "Proxy endpoint невозможен в Nuxt." },
      { id: "b", text: "Такой proxy может раскрыть лишний контракт, ошибки и данные; BFF должен контролировать безопасность и форму ответа." },
      { id: "c", text: "Внешние API можно вызывать только из Vue template." },
      { id: "d", text: "Нужно заменить endpoint на CSS-файл." },
    ],
    correctAnswer: "b",
    explanation: "BFF не должен быть слепой дырой во внешний backend. Он должен проверять доступ, нормализовать ошибки, ограничивать поля и возвращать контракт, удобный frontend-клиенту.",
    knowledgeId: "server-api-1030",
  },
  {
    id: 1031,
    moduleId: "server-api",
    type: "BestPractice",
    difficulty: "Senior",
    tags: [
      "errors",
      "observability",
      "production",
    ],
    question: "Что является хорошей production-практикой обработки ошибок в Server API?",
    answers: [
      { id: "a", text: "Всегда возвращать stack trace клиенту." },
      { id: "b", text: "Игнорировать ошибки внешних API." },
      { id: "c", text: "Разделять пользовательские ошибки и внутренние ошибки, логировать детали на сервере и отдавать клиенту безопасное сообщение." },
      { id: "d", text: "Возвращать 200 при любой ошибке." },
    ],
    correctAnswer: "c",
    explanation: "Production API должен быть наблюдаемым и безопасным. Клиенту не нужно видеть stack trace или секретные детали, но сервер должен сохранять достаточно информации для диагностики.",
    knowledgeId: "server-api-1031",
  },
  {
    id: 1032,
    moduleId: "server-api",
    type: "Architecture",
    difficulty: "Senior",
    tags: [
      "nitro",
      "deployment",
      "runtime",
    ],
    question: "Почему deployment target важен при проектировании Server API на Nitro?",
    answers: [
      { id: "a", text: "Deployment target влияет только на цвет интерфейса." },
      { id: "b", text: "Nitro всегда запускается одинаково в любом окружении без ограничений." },
      { id: "c", text: "Deployment target выбирается только после написания всех security rules." },
      { id: "d", text: "Runtime влияет на доступные API, холодные старты, latency, хранение состояния и стратегию кеширования." },
    ],
    correctAnswer: "d",
    explanation: "Node, serverless и edge имеют разные ограничения. Архитектура Server API должна учитывать доступные APIs, состояние, кеш, latency и поведение платформы.",
    knowledgeId: "server-api-1032",
  },
  {
    id: 1033,
    moduleId: "server-api",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "routeRules",
      "caching",
      "security",
    ],
    question: "routeRules включает кеширование /api/me для всех пользователей. Что нужно отметить?",
    answers: [
      { id: "a", text: "Персональные ответы нельзя кешировать как общий публичный ответ без user-specific ключа и строгих правил." },
      { id: "b", text: "routeRules не могут влиять на API routes." },
      { id: "c", text: "Любой кеш всегда безопасен, если endpoint возвращает JSON." },
      { id: "d", text: "Нужно заменить /api/me на /api/public-me." },
    ],
    correctAnswer: "a",
    explanation: "Кеширование персональных данных опасно: один пользователь может получить данные другого. Для приватных endpoints нужна осторожная cache policy или отсутствие общего кеша.",
    knowledgeId: "server-api-1033",
  },
  {
    id: 1034,
    moduleId: "server-api",
    type: "FindBug",
    difficulty: "Senior",
    tags: [
      "crud",
      "transactions",
      "architecture",
    ],
    question: "Server API endpoint выполняет несколько связанных операций: создать заказ, списать бонусы, отправить событие. Какой архитектурный риск главный?",
    answers: [
      { id: "a", text: "В Server API нельзя выполнять больше одной операции." },
      { id: "b", text: "Нужна стратегия консистентности и обработки частичных ошибок, иначе состояние может разъехаться." },
      { id: "c", text: "Все операции нужно перенести в query string." },
      { id: "d", text: "Достаточно вернуть status 200 до выполнения операций." },
    ],
    correctAnswer: "b",
    explanation: "Несколько связанных изменений требуют продуманной транзакционности, idempotency или компенсирующих действий. Простое последовательное выполнение без стратегии создаёт риск неконсистентного состояния, если один шаг успешен, а следующий падает. На senior-уровне важно обсуждать границы ответственности Server API и backend-системы.",
    knowledgeId: "server-api-1034",
  },
  {
    id: 1035,
    moduleId: "server-api",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "senior",
      "server-api",
      "architecture",
    ],
    question: "Какой ответ лучше всего описывает зрелый подход к Server API в Nuxt?",
    answers: [
      { id: "a", text: "Писать всю backend-логику в одном файле server/api/index.ts." },
      { id: "b", text: "Всегда вызывать внешние API напрямую из браузера." },
      { id: "c", text: "Использовать Server API как контролируемый server boundary: валидировать вход, защищать секреты, нормализовать ответы и учитывать Nitro runtime." },
      { id: "d", text: "Игнорировать HTTP-статусы и возвращать только ok: true/false." },
    ],
    correctAnswer: "c",
    explanation: "Зрелый подход рассматривает Server API как границу между клиентом, backend-сервисами и runtime. Важны безопасность, валидация, корректные статусы, наблюдаемость и понимание Nitro deployment.",
    knowledgeId: "server-api-1035",
  },
]
