import type { ContentQuestion } from '../../../types/content'

export const composablesQuestions: ContentQuestion[] = [
  {
    id: 701,
    moduleId: "composables",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "composables",
      "composition-api",
      "reuse",
    ],
    question: "Что такое composable во Vue?",
    answers: [
      { id: "a", text: "Функция, которая инкапсулирует переиспользуемую Composition API логику" },
      { id: "b", text: "Файл CSS для scoped styles" },
      { id: "c", text: "Глобальный компонент, зарегистрированный через app.component" },
      { id: "d", text: "Специальный формат JSON для props" },
    ],
    correctAnswer: "a",
    explanation: "Composable — это функция, обычно начинающаяся с use, которая содержит reactive state, computed, watchers, lifecycle hooks или методы. Она помогает переиспользовать поведение между компонентами. CSS, global components и JSON не описывают composable.",
    knowledgeId: "knowledge-composables-q701",
  },
  {
    id: 702,
    moduleId: "composables",
    type: "Interview",
    difficulty: "JuniorPlus",
    tags: [
      "reuse",
      "architecture",
      "composition-api",
    ],
    question: "Зачем выносить логику в composables?",
    answers: [
      { id: "a", text: "Чтобы полностью удалить template из компонентов" },
      { id: "b", text: "Чтобы переиспользовать связанную логику и разгрузить компоненты" },
      { id: "c", text: "Чтобы заменить Vue Router" },
      { id: "d", text: "Чтобы любой state автоматически стал глобальным" },
    ],
    correctAnswer: "b",
    explanation: "Composables помогают вынести повторяемый сценарий: загрузку данных, listeners, работу с localStorage или состояние UI. Они не удаляют template, не заменяют router и не делают state глобальным автоматически. Важно выносить реальную логику, а не каждую мелочь.",
    knowledgeId: "knowledge-composables-q702",
  },
  {
    id: 703,
    moduleId: "composables",
    type: "BestPractice",
    difficulty: "Junior",
    tags: [
      "naming",
      "use-prefix",
      "conventions",
    ],
    question: "Почему composables обычно называют с префиксом `use`?",
    answers: [
      { id: "a", text: "Без префикса use Vue не соберёт проект" },
      { id: "b", text: "Префикс use делает функцию глобальной" },
      { id: "c", text: "Так проще распознать функцию, которая использует Composition API и возвращает reusable logic" },
      { id: "d", text: "Префикс use нужен только для CSS-файлов" },
    ],
    correctAnswer: "c",
    explanation: "Префикс use — соглашение, а не техническое требование компилятора. Он помогает отличать composables от обычных utils и быстрее понимать назначение функции. Глобальность или сборка проекта от имени не зависят.",
    knowledgeId: "knowledge-composables-q703",
  },
  {
    id: 704,
    moduleId: "composables",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "ref",
      "reactive",
      "state",
    ],
    question: "Можно ли создавать ref или reactive внутри composable?",
    answers: [
      { id: "a", text: "Нет, ref можно использовать только внутри .vue template" },
      { id: "b", text: "Нет, reactive доступен только в Pinia stores" },
      { id: "c", text: "Только если composable является компонентом" },
      { id: "d", text: "Да, composable может создавать и возвращать reactive state" },
    ],
    correctAnswer: "d",
    explanation: "Composable — обычная функция, которая может использовать Composition API внутри setup-контекста. Она может создавать ref, reactive, computed и watchers. Важно понимать, будет state новым при каждом вызове или разделяемым между вызовами.",
    knowledgeId: "knowledge-composables-q704",
  },
  {
    id: 705,
    moduleId: "composables",
    type: "CodeReview",
    difficulty: "JuniorPlus",
    tags: [
      "return-api",
      "state",
      "methods",
    ],
    question: "Что обычно возвращает composable?",
    answers: [
      { id: "a", text: "Состояние, computed-значения и методы, которые нужны потребителю" },
      { id: "b", text: "Только HTML-строку с template" },
      { id: "c", text: "Всегда Vue-компонент" },
      { id: "d", text: "Только CSS-классы" },
    ],
    correctAnswer: "a",
    explanation: "Composable возвращает публичный API своей логики: refs, computed, функции команд, flags loading/error. Возвращать нужно только то, что действительно нужно потребителю. HTML и CSS обычно не являются задачей composable.",
    knowledgeId: "knowledge-composables-q705",
  },
  {
    id: 706,
    moduleId: "composables",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "singleton-state",
      "factory-state",
      "shared-state",
    ],
    question: "В чём разница между singleton state и factory state в composables?",
    answers: [
      { id: "a", text: "Singleton state всегда безопаснее factory state" },
      { id: "b", text: "Singleton создаётся вне функции и разделяется, factory state создаётся внутри функции для каждого вызова" },
      { id: "c", text: "Factory state доступен только в Options API" },
      { id: "d", text: "Разницы нет, Vue всегда делает state глобальным" },
    ],
    correctAnswer: "b",
    explanation: "Если ref объявлен вне composable, все вызовы функции будут разделять одно состояние. Если ref создаётся внутри composable, каждый вызов получает новый state. Оба подхода полезны, но для разных задач.",
    knowledgeId: "knowledge-composables-q706",
  },
  {
    id: 707,
    moduleId: "composables",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "shared-composables",
      "state",
      "architecture",
    ],
    question: "Когда shared composable с общим state может быть уместен?",
    answers: [
      { id: "a", text: "Когда каждому компоненту нужен полностью независимый счётчик" },
      { id: "b", text: "Когда нужно заменить все props в приложении" },
      { id: "c", text: "Когда нескольким компонентам нужен один и тот же легковесный reactive state" },
      { id: "d", text: "Когда нужно отрисовать static HTML без состояния" },
    ],
    correctAnswer: "c",
    explanation: "Shared composable уместен для небольшого общего состояния: theme, viewport, выбранная вкладка в локальном контексте. Если каждому потребителю нужен независимый state, лучше factory composable. Для сложного глобального состояния часто лучше Pinia.",
    knowledgeId: "knowledge-composables-q707",
  },
  {
    id: 708,
    moduleId: "composables",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "cleanup",
      "resources",
      "lifecycle",
    ],
    question: "Что должен сделать composable, если он создаёт внешний listener или timer?",
    answers: [
      { id: "a", text: "Оставить cleanup компоненту-потребителю всегда вручную" },
      { id: "b", text: "Сохранить listener в CSS-переменную" },
      { id: "c", text: "Передать listener через slot" },
      { id: "d", text: "Зарегистрировать cleanup, например через onUnmounted или watcher cleanup" },
    ],
    correctAnswer: "d",
    explanation: "Composable, который создаёт внешний ресурс, должен сам организовать его очистку. Это делает функцию безопасной для повторного использования. Иначе каждый потребитель должен помнить внутренние детали composable.",
    knowledgeId: "knowledge-composables-q708",
  },
  {
    id: 709,
    moduleId: "composables",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "onMounted",
      "onUnmounted",
      "composables",
    ],
    question: "Можно ли использовать onMounted и onUnmounted внутри composable?",
    answers: [
      { id: "a", text: "Да, если composable вызывается внутри setup-контекста компонента" },
      { id: "b", text: "Нет, lifecycle hooks доступны только в .vue template" },
      { id: "c", text: "Да, но они выполнятся глобально один раз на приложение" },
      { id: "d", text: "Только если composable экспортирует компонент" },
    ],
    correctAnswer: "a",
    explanation: "Lifecycle hooks можно регистрировать внутри composable, если он вызывается во время setup текущего компонента. Hooks будут привязаны к этому компонентному экземпляру. Вызов вне setup-контекста приведёт к некорректному использованию.",
    knowledgeId: "knowledge-composables-q709",
  },
  {
    id: 710,
    moduleId: "composables",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "watch",
      "watchEffect",
      "side-effects",
    ],
    question: "Когда watch внутри composable является хорошим решением?",
    answers: [
      { id: "a", text: "Когда нужно вернуть простое computed значение без side effect" },
      { id: "b", text: "Когда composable должен выполнить side effect при изменении переданного reactive источника" },
      { id: "c", text: "Когда нужно объявить props компонента" },
      { id: "d", text: "Когда нужно заменить TypeScript-типы" },
    ],
    correctAnswer: "b",
    explanation: "watch внутри composable подходит для синхронизации с localStorage, запроса при изменении query или подписки на источник. Для чистых производных значений лучше computed. Props и TypeScript решаются другими API.",
    knowledgeId: "knowledge-composables-q710",
  },
  {
    id: 711,
    moduleId: "composables",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "dependency-injection",
      "arguments",
      "testability",
    ],
    question: "Что означает dependency injection через аргументы composable?",
    answers: [
      { id: "a", text: "Всегда использовать provide/inject внутри каждого composable" },
      { id: "b", text: "Передавать зависимости только через window" },
      { id: "c", text: "Передавать зависимости параметрами вместо жёсткого импорта или обращения к глобальным объектам" },
      { id: "d", text: "Хранить зависимости в template slots" },
    ],
    correctAnswer: "c",
    explanation: "Dependency injection через аргументы делает composable гибче и тестируемее. Например, можно передать fetcher, storage или now-функцию. Это снижает скрытую связность и упрощает тесты.",
    knowledgeId: "knowledge-composables-q711",
  },
  {
    id: 712,
    moduleId: "composables",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "testability",
      "composables",
      "architecture",
    ],
    question: "Почему composables обычно проще тестировать, чем большие компоненты?",
    answers: [
      { id: "a", text: "Они автоматически тестируются Vue compiler" },
      { id: "b", text: "Они не могут содержать asynchronous code" },
      { id: "c", text: "Они всегда работают без reactive state" },
      { id: "d", text: "Они отделяют логику от template и часто имеют явный вход и выход" },
    ],
    correctAnswer: "d",
    explanation: "Composable можно тестировать как функцию: передать зависимости, вызвать методы и проверить refs. Если логика спрятана в большом компоненте, тест часто требует mount и сложной UI-настройки. Компилятор не тестирует бизнес-логику автоматически.",
    knowledgeId: "knowledge-composables-q712",
  },
  {
    id: 713,
    moduleId: "composables",
    type: "BestPractice",
    difficulty: "MiddlePlus",
    tags: [
      "ssr",
      "window",
      "document",
    ],
    question: "Что делает composable SSR-safe?",
    answers: [
      { id: "a", text: "Он не обращается к window/document до проверки client-среды или onMounted" },
      { id: "b", text: "Он всегда вызывает window в верхнем уровне модуля" },
      { id: "c", text: "Он хранит весь state в DOM" },
      { id: "d", text: "Он запрещает TypeScript" },
    ],
    correctAnswer: "a",
    explanation: "В SSR нет browser APIs, поэтому window и document недоступны. SSR-safe composable откладывает client-only код до onMounted или проверяет среду. Это важно для Nuxt и server-rendered приложений.",
    knowledgeId: "knowledge-composables-q713",
  },
  {
    id: 714,
    moduleId: "composables",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "localStorage",
      "persistence",
      "watch",
    ],
    question: "Какой подход подходит для composable, синхронизирующего ref с localStorage?",
    answers: [
      { id: "a", text: "Читать localStorage в SSR без проверок всегда" },
      { id: "b", text: "Прочитать начальное значение безопасно и записывать изменения через watch" },
      { id: "c", text: "Мутировать props каждого компонента" },
      { id: "d", text: "Передавать localStorage через slot" },
    ],
    correctAnswer: "b",
    explanation: "Composable для localStorage обычно создаёт ref, читает сохранённое значение и записывает изменения через watch. В SSR нужна защита от отсутствия window. Props и slots не являются каналом persistence.",
    knowledgeId: "knowledge-composables-q714",
  },
  {
    id: 715,
    moduleId: "composables",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "window",
      "document",
      "ssr",
    ],
    question: "Что не так с обращением к `window.innerWidth` на верхнем уровне файла composable?",
    answers: [
      { id: "a", text: "window.innerWidth всегда возвращает Promise" },
      { id: "b", text: "Vue запрещает читать window в onMounted" },
      { id: "c", text: "Код может упасть в SSR и выполняется при импорте модуля, а не при вызове composable" },
      { id: "d", text: "Это автоматически создаёт Pinia store" },
    ],
    correctAnswer: "c",
    explanation: "Top-level код выполняется при импорте модуля. В SSR window не существует, поэтому такой composable небезопасен. Browser APIs лучше читать внутри onMounted или после проверки client-среды.",
    knowledgeId: "knowledge-composables-q715",
  },
  {
    id: 716,
    moduleId: "composables",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "async-composables",
      "loading-error-data",
      "fetching",
    ],
    question: "Какой API чаще всего ожидают от async composable?",
    answers: [
      { id: "a", text: "Только HTML-строку с результатом" },
      { id: "b", text: "Только Promise без reactive state всегда" },
      { id: "c", text: "CSS-класс success или error" },
      { id: "d", text: "data, loading, error и метод execute/refetch" },
    ],
    correctAnswer: "d",
    explanation: "Async composable должен дать компоненту понятные состояния: данные, загрузку, ошибку и способ повторить запрос. Один Promise часто неудобен для UI, потому что интерфейсу нужно реагировать на промежуточные состояния.",
    knowledgeId: "knowledge-composables-q716",
  },
  {
    id: 717,
    moduleId: "composables",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "error-handling",
      "async",
      "composables",
    ],
    question: "Как composable должен работать с ошибками async-операций?",
    answers: [
      { id: "a", text: "Явно сохранять error state или пробрасывать ошибку по задокументированному контракту" },
      { id: "b", text: "Всегда молча игнорировать ошибки" },
      { id: "c", text: "Записывать ошибку в CSS-класс компонента" },
      { id: "d", text: "Автоматически перезагружать страницу" },
    ],
    correctAnswer: "a",
    explanation: "Ошибка должна быть частью контракта composable: reactive error, thrown exception или callback. Молчаливое игнорирование делает UI непредсказуемым. Перезагрузка страницы и CSS-класс не являются универсальной обработкой ошибок.",
    knowledgeId: "knowledge-composables-q717",
  },
  {
    id: 718,
    moduleId: "composables",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "loading-error-data",
      "async",
      "state",
    ],
    question: "Что означает pattern `loading/error/data`?",
    answers: [
      { id: "a", text: "Синтаксис объявления props" },
      { id: "b", text: "Явное моделирование состояния асинхронной операции для UI" },
      { id: "c", text: "Способ заменить router" },
      { id: "d", text: "Формат именования CSS-переменных" },
    ],
    correctAnswer: "b",
    explanation: "loading/error/data pattern помогает UI понять, что показывать: спиннер, ошибку или результат. Это особенно полезно в async composables. Он не связан с props, router или CSS.",
    knowledgeId: "knowledge-composables-q718",
  },
  {
    id: 719,
    moduleId: "composables",
    type: "Interview",
    difficulty: "JuniorPlus",
    tags: [
      "components-vs-composables",
      "separation-of-concerns",
    ],
    question: "Чем composable отличается от компонента?",
    answers: [
      { id: "a", text: "Composable всегда рендерит DOM" },
      { id: "b", text: "Компонент не может использовать reactive state" },
      { id: "c", text: "Composable переиспользует логику, компонент отвечает за UI и template" },
      { id: "d", text: "Composable обязательно должен иметь .vue расширение" },
    ],
    correctAnswer: "c",
    explanation: "Composable — функция для логики. Компонент — единица UI, которая может использовать composables. Composable не имеет template и не рендерит DOM сам по себе.",
    knowledgeId: "knowledge-composables-q719",
  },
  {
    id: 720,
    moduleId: "composables",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "pinia",
      "stores",
      "composables",
    ],
    question: "Чем composable отличается от Pinia store?",
    answers: [
      { id: "a", text: "Pinia store не может содержать actions" },
      { id: "b", text: "Composable всегда сохраняет state в localStorage" },
      { id: "c", text: "Pinia store используется только для CSS" },
      { id: "d", text: "Composable может быть локальной переиспользуемой логикой, Pinia store предназначен для управляемого глобального/разделяемого состояния" },
    ],
    correctAnswer: "d",
    explanation: "Composable не обязан быть глобальным и может создавать новый state на каждый вызов. Pinia store даёт централизованное состояние, devtools и явный store contract. Выбор зависит от масштаба состояния.",
    knowledgeId: "knowledge-composables-q720",
  },
  {
    id: 721,
    moduleId: "composables",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "hidden-dependencies",
      "anti-patterns",
      "testability",
    ],
    question: "Какая ошибка делает composable плохо тестируемым?",
    answers: [
      { id: "a", text: "Жёсткая зависимость от глобальных объектов и скрытых imports без возможности подмены" },
      { id: "b", text: "Явные параметры и возвращаемый API" },
      { id: "c", text: "Отдельные typed refs" },
      { id: "d", text: "Возвращение метода reset" },
    ],
    correctAnswer: "a",
    explanation: "Скрытые зависимости усложняют тестирование, потому что их трудно заменить. Явные параметры, typed refs и методы команд делают composable понятнее. Dependency injection через аргументы часто улучшает тестируемость.",
    knowledgeId: "knowledge-composables-q721",
  },
  {
    id: 722,
    moduleId: "composables",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "api-design",
      "return-shape",
      "readability",
    ],
    question: "Что стоит предложить на review, если composable возвращает большой неструктурированный объект из 25 полей?",
    answers: [
      { id: "a", text: "Добавить ещё больше полей на будущее" },
      { id: "b", text: "Проверить ответственность composable, разделить API или сгруппировать связанные части" },
      { id: "c", text: "Вернуть всё как JSON-строку" },
      { id: "d", text: "Спрятать все поля в window" },
    ],
    correctAnswer: "b",
    explanation: "Большой return API часто говорит о слишком широкой ответственности. Стоит проверить, не нужно ли разделить composable или сгруппировать state/actions. JSON-строка и window ухудшат типизацию и поддержку.",
    knowledgeId: "knowledge-composables-q722",
  },
  {
    id: 723,
    moduleId: "composables",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "factory-state",
      "forms",
      "reuse",
    ],
    question: "Компонентам нужны независимые состояния формы. Где создавать refs внутри composable?",
    answers: [
      { id: "a", text: "Только на верхнем уровне модуля, чтобы все формы делили state" },
      { id: "b", text: "В CSS-файле формы" },
      { id: "c", text: "Внутри функции composable, чтобы каждый вызов получил новый state" },
      { id: "d", text: "В глобальном объекте window всегда" },
    ],
    correctAnswer: "c",
    explanation: "Если нужен независимый state для каждого потребителя, ref создают внутри composable. Top-level ref создаст singleton state, который разделяется всеми вызовами. Для форм это часто ошибка.",
    knowledgeId: "knowledge-composables-q723",
  },
  {
    id: 724,
    moduleId: "composables",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "singleton-state",
      "module-scope",
      "shared-state",
    ],
    question: "Что произойдёт, если `const count = ref(0)` объявлен вне функции `useCounter`?",
    answers: [
      { id: "a", text: "count будет новым для каждого компонента автоматически" },
      { id: "b", text: "Vue запретит импорт файла" },
      { id: "c", text: "count станет readonly prop" },
      { id: "d", text: "Все вызовы useCounter будут разделять один и тот же count" },
    ],
    correctAnswer: "d",
    explanation: "Top-level ref создаётся один раз при импорте модуля. Все вызовы composable получают ссылку на один и тот же state. Это полезно для shared state, но опасно, если ожидалась независимость.",
    knowledgeId: "knowledge-composables-q724",
  },
  {
    id: 725,
    moduleId: "composables",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "readonly",
      "encapsulation",
      "state",
    ],
    question: "Зачем composable иногда возвращает readonly state и методы изменения отдельно?",
    answers: [
      { id: "a", text: "Чтобы потребитель читал состояние, но менял его через контролируемый API" },
      { id: "b", text: "Чтобы запретить template использовать state" },
      { id: "c", text: "Чтобы все методы стали async" },
      { id: "d", text: "Чтобы state автоматически попал в Pinia" },
    ],
    correctAnswer: "a",
    explanation: "Readonly state защищает внутренние инварианты composable. Потребитель вызывает методы вроде open, close, reset, а не мутирует refs напрямую. Это полезно для shared state и сложной логики.",
    knowledgeId: "knowledge-composables-q725",
  },
  {
    id: 726,
    moduleId: "composables",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "abstraction",
      "overengineering",
      "architecture",
    ],
    question: "Когда не стоит выносить логику в composable?",
    answers: [
      { id: "a", text: "Когда компонент использует один ref" },
      { id: "b", text: "Когда логика короткая, локальная, не повторяется и понятнее внутри компонента" },
      { id: "c", text: "Когда используется TypeScript" },
      { id: "d", text: "Когда в template есть slot" },
    ],
    correctAnswer: "b",
    explanation: "Composable должен снижать сложность, а не добавлять лишний файл. Если логика простая и локальная, её можно оставить в компоненте. TypeScript, ref или slot сами по себе не требуют новой абстракции.",
    knowledgeId: "knowledge-composables-q726",
  },
  {
    id: 727,
    moduleId: "composables",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "async-race",
      "stale-results",
      "cleanup",
    ],
    question: "Какая проблема возможна в async composable без защиты от устаревших запросов?",
    answers: [
      { id: "a", text: "Vue автоматически удалит component props" },
      { id: "b", text: "ref перестанет быть реактивным навсегда" },
      { id: "c", text: "Медленный старый ответ может перезаписать более новый результат" },
      { id: "d", text: "TypeScript выключится для всего проекта" },
    ],
    correctAnswer: "c",
    explanation: "Если несколько запросов идут параллельно, они могут завершиться не в том порядке, в котором стартовали. Без AbortController, request id или cleanup старый результат может перезаписать актуальные данные. Это типичная race condition.",
    knowledgeId: "knowledge-composables-q727",
  },
  {
    id: 728,
    moduleId: "composables",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "parameters",
      "refs",
      "inputs",
    ],
    question: "Как лучше передать reactive query в composable поиска?",
    answers: [
      { id: "a", text: "Заставить composable искать query в DOM по id" },
      { id: "b", text: "Передать query через CSS-переменную" },
      { id: "c", text: "Сохранить query в глобальную переменную без контракта" },
      { id: "d", text: "Передать Ref или getter и явно описать ожидаемый вход" },
    ],
    correctAnswer: "d",
    explanation: "Явный вход делает composable понятным и тестируемым. Ref или getter позволяют реагировать на изменения query. Поиск DOM по id и глобальные переменные создают скрытые зависимости.",
    knowledgeId: "knowledge-composables-q728",
  },
  {
    id: 729,
    moduleId: "composables",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "naming",
      "contract",
      "api-design",
    ],
    question: "Что отличает хороший composable API?",
    answers: [
      { id: "a", text: "Явный вход, понятный return API, ограниченная ответственность и предсказуемый cleanup" },
      { id: "b", text: "Максимальное количество скрытых глобальных зависимостей" },
      { id: "c", text: "Отсутствие типов у параметров и результата" },
      { id: "d", text: "Обязательная привязка к одному конкретному компоненту" },
    ],
    correctAnswer: "a",
    explanation: "Хороший composable похож на маленький typed API: понятно, что передать, что получить и кто владеет ресурсами. Скрытые зависимости и привязка к конкретному компоненту ухудшают повторное использование.",
    knowledgeId: "knowledge-composables-q729",
  },
  {
    id: 730,
    moduleId: "composables",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "component-coupling",
      "dom",
      "anti-patterns",
    ],
    question: "Что стоит исправить, если универсальный composable напрямую ищет `.profile-page .save-button` в DOM?",
    answers: [
      { id: "a", text: "Добавить ещё больше CSS-селекторов внутрь composable" },
      { id: "b", text: "Убрать привязку к конкретной странице и передать элемент/ref параметром" },
      { id: "c", text: "Сделать composable глобальным singleton всегда" },
      { id: "d", text: "Перенести selector в title prop" },
    ],
    correctAnswer: "b",
    explanation: "Универсальный composable не должен знать DOM-структуру конкретной страницы. Лучше передать ref элемента или callback параметром. Это снижает связность и упрощает тестирование.",
    knowledgeId: "knowledge-composables-q730",
  },
]
