import type { ContentQuestion } from '../../../types/content'

export const routerQuestions: ContentQuestion[] = [
  {
    id: 801,
    moduleId: "router",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "vue-router",
      "spa",
      "routing",
    ],
    question: "Что такое Vue Router?",
    answers: [
      { id: "a", text: "Официальная библиотека маршрутизации для Vue-приложений" },
      { id: "b", text: "Библиотека для управления CSS-переменными" },
      { id: "c", text: "Сборщик, который заменяет Vite" },
      { id: "d", text: "Формат хранения данных в localStorage" },
    ],
    correctAnswer: "a",
    explanation: "Vue Router связывает URL с компонентами и позволяет строить SPA с несколькими страницами. Он не управляет CSS, сборкой или persistence. Важно понимать, что router отвечает за навигацию, matched routes, guards и отображение route components.",
    knowledgeId: "knowledge-router-q801",
  },
  {
    id: 802,
    moduleId: "router",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "history",
      "createWebHistory",
      "createWebHashHistory",
    ],
    question: "Что определяет router history?",
    answers: [
      { id: "a", text: "Как Vue кеширует computed значения" },
      { id: "b", text: "Как URL синхронизируется с состоянием маршрутизатора" },
      { id: "c", text: "Как Pinia сохраняет stores" },
      { id: "d", text: "Как браузер загружает CSS modules" },
    ],
    correctAnswer: "b",
    explanation: "History mode определяет, как router работает с URL: через History API или hash. createWebHistory требует server fallback, а createWebHashHistory работает через часть URL после #. Это не относится к computed, Pinia или CSS.",
    knowledgeId: "knowledge-router-q802",
  },
  {
    id: 803,
    moduleId: "router",
    type: "CodeOutput",
    difficulty: "Junior",
    tags: [
      "createRouter",
      "routes",
      "setup",
    ],
    question: "Что создаёт вызов `createRouter({ history, routes })`?",
    answers: [
      { id: "a", text: "Pinia store для текущего маршрута" },
      { id: "b", text: "Компонент RouterView" },
      { id: "c", text: "Экземпляр router, который подключается к Vue-приложению через app.use(router)" },
      { id: "d", text: "HTML-файл для каждой страницы" },
    ],
    correctAnswer: "c",
    explanation: "createRouter создаёт экземпляр маршрутизатора с history mode и списком routes. Затем его подключают к приложению. RouterView и RouterLink являются компонентами, а не результатом createRouter.",
    knowledgeId: "knowledge-router-q803",
  },
  {
    id: 804,
    moduleId: "router",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "createWebHistory",
      "server-fallback",
      "deployment",
    ],
    question: "Что важно настроить при использовании createWebHistory на production-сервере?",
    answers: [
      { id: "a", text: "Обязательное добавление # в каждый URL" },
      { id: "b", text: "Запрет на lazy loading routes" },
      { id: "c", text: "Удаление всех navigation guards" },
      { id: "d", text: "Fallback на index.html для routes, которые обрабатываются SPA" },
    ],
    correctAnswer: "d",
    explanation: "createWebHistory использует нормальные URL без hash, поэтому прямой заход на /profile должен отдавать index.html. Без server fallback сервер может вернуть 404 до запуска SPA. Hash history такой настройки обычно не требует.",
    knowledgeId: "knowledge-router-q804",
  },
  {
    id: 805,
    moduleId: "router",
    type: "BestPractice",
    difficulty: "Junior",
    tags: [
      "createWebHashHistory",
      "deployment",
      "history",
    ],
    question: "Когда createWebHashHistory может быть практичным выбором?",
    answers: [
      { id: "a", text: "Когда нет контроля над server fallback и нужно, чтобы прямые переходы работали без настройки сервера" },
      { id: "b", text: "Когда нужно скрыть все query-параметры от приложения" },
      { id: "c", text: "Когда нужно запретить динамические маршруты" },
      { id: "d", text: "Когда приложение не использует URL вообще" },
    ],
    correctAnswer: "a",
    explanation: "Hash history хранит route после #, поэтому сервер обычно получает один и тот же path. Это удобно на статическом хостинге без rewrite-настроек. Минус — менее чистый URL.",
    knowledgeId: "knowledge-router-q805",
  },
  {
    id: 806,
    moduleId: "router",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "RouteRecord",
      "routes",
      "RouteRecordRaw",
    ],
    question: "Что описывает route record в Vue Router?",
    answers: [
      { id: "a", text: "Текущий scroll position браузера" },
      { id: "b", text: "Запись маршрута: path, component, name, children, meta и другие настройки" },
      { id: "c", text: "Список всех Pinia actions" },
      { id: "d", text: "CSS-класс активной ссылки" },
    ],
    correctAnswer: "b",
    explanation: "Route record описывает правило сопоставления URL и компонента. В нём могут быть path, name, component, redirect, alias, children и meta. Scroll, store actions и CSS-классы решаются другими частями системы.",
    knowledgeId: "knowledge-router-q806",
  },
  {
    id: 807,
    moduleId: "router",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "nested-routes",
      "children",
      "layout",
    ],
    question: "Когда уместны nested routes?",
    answers: [
      { id: "a", text: "Когда нужно заменить все компоненты одним RouterLink" },
      { id: "b", text: "Когда route не должен иметь path" },
      { id: "c", text: "Когда несколько страниц должны рендериться внутри общего route layout" },
      { id: "d", text: "Когда нужно отключить router-view" },
    ],
    correctAnswer: "c",
    explanation: "Nested routes позволяют родительскому маршруту отображать layout, а дочерним маршрутам — вложенный контент через вложенный RouterView. Это полезно для dashboard, settings, profile sections и других разделов с общей оболочкой.",
    knowledgeId: "knowledge-router-q807",
  },
  {
    id: 808,
    moduleId: "router",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "children",
      "nested-routes",
      "router-view",
    ],
    question: "Что нужно проверить, если child route не отображается внутри родительского компонента?",
    answers: [
      { id: "a", text: "Подключён ли Pinia store к child route" },
      { id: "b", text: "Есть ли у child route CSS scoped" },
      { id: "c", text: "Назван ли компонент строго Child.vue" },
      { id: "d", text: "Есть ли во вложенном layout компонент RouterView для дочерних routes" },
    ],
    correctAnswer: "d",
    explanation: "Child routes рендерятся в RouterView родительского route component. Если вложенного RouterView нет, matched child component некуда вставить. Pinia, CSS и имя файла не являются причиной по умолчанию.",
    knowledgeId: "knowledge-router-q808",
  },
  {
    id: 809,
    moduleId: "router",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "dynamic-routes",
      "params",
      "path",
    ],
    question: "Что означает path `/users/:id`?",
    answers: [
      { id: "a", text: "Динамический сегмент маршрута, где id доступен как route param" },
      { id: "b", text: "Query-параметр id после знака ?" },
      { id: "c", text: "Named route с именем id" },
      { id: "d", text: "Redirect на /users/id" },
    ],
    correctAnswer: "a",
    explanation: "Сегмент `:id` является dynamic param и берётся из path. Для /users/42 route.params.id будет 42. Query-параметры находятся после ? и доступны в route.query.",
    knowledgeId: "knowledge-router-q809",
  },
  {
    id: 810,
    moduleId: "router",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "params",
      "named-routes",
      "programmatic-navigation",
    ],
    question: "Почему `router.push({ path: \"/users\", params: { id: \"42\" } })` не подставит id в path?",
    answers: [
      { id: "a", text: "params можно передавать только через localStorage" },
      { id: "b", text: "params работают с named routes или path-шаблоном, но игнорируются при обычном path без динамического сегмента" },
      { id: "c", text: "router.push не поддерживает объекты" },
      { id: "d", text: "id обязан быть числом" },
    ],
    correctAnswer: "b",
    explanation: "При navigation object лучше использовать named route: `{ name: \"user\", params: { id: \"42\" } }`. Если указан plain path `/users`, router не знает, куда подставлять params. Для query используется отдельное поле query.",
    knowledgeId: "knowledge-router-q810",
  },
  {
    id: 811,
    moduleId: "router",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "query",
      "params",
      "url",
    ],
    question: "Чем query отличается от params?",
    answers: [
      { id: "a", text: "query всегда скрыт от пользователя" },
      { id: "b", text: "params работают только в hash history" },
      { id: "c", text: "query хранится после ? в URL, params являются частью path-шаблона" },
      { id: "d", text: "query нельзя читать через useRoute" },
    ],
    correctAnswer: "c",
    explanation: "Params описывают path-сегменты вроде /users/:id, а query — параметры после ? вроде ?tab=posts. Оба видны в URL и доступны через useRoute. Выбор зависит от смысла данных.",
    knowledgeId: "knowledge-router-q811",
  },
  {
    id: 812,
    moduleId: "router",
    type: "BestPractice",
    difficulty: "Junior",
    tags: [
      "named-routes",
      "refactoring",
      "navigation",
    ],
    question: "Зачем использовать named routes?",
    answers: [
      { id: "a", text: "Чтобы отключить route params" },
      { id: "b", text: "Чтобы route component стал глобальным" },
      { id: "c", text: "Чтобы query автоматически шифровался" },
      { id: "d", text: "Чтобы навигация меньше зависела от строковых path и была устойчивее к изменению URL" },
    ],
    correctAnswer: "d",
    explanation: "Named routes позволяют навигировать по имени и params, не дублируя path-строки по коду. Это облегчает рефакторинг URL. Они не отключают params и не меняют безопасность query.",
    knowledgeId: "knowledge-router-q812",
  },
  {
    id: 813,
    moduleId: "router",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "redirect",
      "routes",
      "navigation",
    ],
    question: "Что делает redirect в route record?",
    answers: [
      { id: "a", text: "Автоматически перенаправляет навигацию с одного маршрута на другой" },
      { id: "b", text: "Создаёт alias без изменения URL" },
      { id: "c", text: "Кеширует компонент маршрута" },
      { id: "d", text: "Отключает navigation guards" },
    ],
    correctAnswer: "a",
    explanation: "Redirect заменяет целевой маршрут на другой при навигации. Alias, наоборот, позволяет нескольким path отображать один route record без такого же смысла перенаправления. Guards всё равно могут участвовать в навигации.",
    knowledgeId: "knowledge-router-q813",
  },
  {
    id: 814,
    moduleId: "router",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "alias",
      "routes",
      "url",
    ],
    question: "Что делает alias в Vue Router?",
    answers: [
      { id: "a", text: "Всегда меняет URL на canonical path" },
      { id: "b", text: "Позволяет открыть тот же route record по дополнительному path" },
      { id: "c", text: "Создаёт navigation guard" },
      { id: "d", text: "Запрещает lazy loading" },
    ],
    correctAnswer: "b",
    explanation: "Alias даёт альтернативный URL для того же route record. В отличие от redirect, он не обязательно меняет URL на другой. Это полезно для совместимости URL или нескольких публичных путей к одному экрану.",
    knowledgeId: "knowledge-router-q814",
  },
  {
    id: 815,
    moduleId: "router",
    type: "CodeOutput",
    difficulty: "MiddlePlus",
    tags: [
      "catch-all",
      "404",
      "routes",
    ],
    question: "Для чего используют route path `/:pathMatch(.*)*`?",
    answers: [
      { id: "a", text: "Для обязательной авторизации всех routes" },
      { id: "b", text: "Для создания query-параметров" },
      { id: "c", text: "Для catch all маршрута, который обычно показывает 404 страницу" },
      { id: "d", text: "Для автоматического scroll restoration" },
    ],
    correctAnswer: "c",
    explanation: "Catch all route ловит URL, которые не совпали с другими routes. Обычно его размещают последним и показывают NotFound page. Он не отвечает за auth, query или scroll.",
    knowledgeId: "knowledge-router-q815",
  },
  {
    id: 816,
    moduleId: "router",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "navigation-guards",
      "guards",
      "routing",
    ],
    question: "Что такое navigation guards?",
    answers: [
      { id: "a", text: "CSS-классы активных RouterLink" },
      { id: "b", text: "Компоненты для отображения вложенных routes" },
      { id: "c", text: "Функции для создания Pinia stores" },
      { id: "d", text: "Hooks маршрутизации, которые могут разрешить, отменить или перенаправить навигацию" },
    ],
    correctAnswer: "d",
    explanation: "Navigation guards позволяют проверять условия перехода: auth, роли, unsaved changes, доступность данных. Они не являются CSS-классами или компонентами. Guards должны быть предсказуемыми и завершать навигацию явно.",
    knowledgeId: "knowledge-router-q816",
  },
  {
    id: 817,
    moduleId: "router",
    type: "Scenario",
    difficulty: "MiddlePlus",
    tags: [
      "beforeEach",
      "auth-guard",
      "meta",
    ],
    question: "Где обычно размещают глобальную проверку авторизации перед входом на защищённые страницы?",
    answers: [
      { id: "a", text: "В router.beforeEach с проверкой route meta" },
      { id: "b", text: "В CSS-классе RouterLink" },
      { id: "c", text: "В каждом template через v-if без router guard" },
      { id: "d", text: "В scrollBehavior" },
    ],
    correctAnswer: "a",
    explanation: "Глобальный auth guard обычно проверяет `to.meta.requiresAuth` и состояние пользователя. Если доступа нет, guard перенаправляет на login. CSS, template-only checks и scrollBehavior не защищают навигацию.",
    knowledgeId: "knowledge-router-q817",
  },
  {
    id: 818,
    moduleId: "router",
    type: "Interview",
    difficulty: "MiddlePlus",
    tags: [
      "beforeResolve",
      "guards",
      "data",
    ],
    question: "Чем beforeResolve отличается от beforeEach?",
    answers: [
      { id: "a", text: "beforeResolve выполняется только после afterEach" },
      { id: "b", text: "beforeResolve вызывается позже, когда async components и in-component guards уже разрешены" },
      { id: "c", text: "beforeResolve работает только с hash history" },
      { id: "d", text: "beforeResolve запрещает redirect" },
    ],
    correctAnswer: "b",
    explanation: "beforeEach срабатывает рано для каждой навигации. beforeResolve вызывается перед подтверждением навигации, когда большая часть разрешения маршрута уже завершена. Он полезен для финальных проверок перед входом.",
    knowledgeId: "knowledge-router-q818",
  },
  {
    id: 819,
    moduleId: "router",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "afterEach",
      "analytics",
      "guards",
    ],
    question: "Для чего подходит afterEach?",
    answers: [
      { id: "a", text: "Для отмены навигации до входа на маршрут" },
      { id: "b", text: "Для объявления child routes" },
      { id: "c", text: "Для side effects после завершения навигации, например analytics или title update" },
      { id: "d", text: "Для создания history mode" },
    ],
    correctAnswer: "c",
    explanation: "afterEach вызывается после завершения навигации и не может отменить переход. Он подходит для аналитики, логирования и побочных эффектов после перехода. Для отмены или redirect используют before guards.",
    knowledgeId: "knowledge-router-q819",
  },
  {
    id: 820,
    moduleId: "router",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "route-meta",
      "auth",
      "breadcrumbs",
    ],
    question: "Для чего используют route meta?",
    answers: [
      { id: "a", text: "Для хранения всего state страницы" },
      { id: "b", text: "Для замены params и query" },
      { id: "c", text: "Для автоматического lazy loading" },
      { id: "d", text: "Для дополнительных данных маршрута: auth requirements, roles, title, breadcrumb labels" },
    ],
    correctAnswer: "d",
    explanation: "meta хранит статичные сведения о route record, полезные guards, layout и navigation UI. Не стоит превращать meta в хранилище runtime state. Params, query и lazy loading решаются отдельно.",
    knowledgeId: "knowledge-router-q820",
  },
  {
    id: 821,
    moduleId: "router",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "lazy-loading",
      "dynamic-imports",
      "performance",
    ],
    question: "Почему route components часто загружают через dynamic import?",
    answers: [
      { id: "a", text: "Чтобы разделить bundle и загружать код страницы по требованию" },
      { id: "b", text: "Чтобы запретить navigation guards" },
      { id: "c", text: "Чтобы route перестал иметь URL" },
      { id: "d", text: "Чтобы компонент нельзя было типизировать" },
    ],
    correctAnswer: "a",
    explanation: "Dynamic imports позволяют code splitting: каждая крупная страница может попасть в отдельный chunk. Это улучшает initial load. Guards, URL и TypeScript от lazy loading не исчезают.",
    knowledgeId: "knowledge-router-q821",
  },
  {
    id: 822,
    moduleId: "router",
    type: "FindBug",
    difficulty: "MiddlePlus",
    tags: [
      "dynamic-imports",
      "lazy-loading",
      "chunks",
    ],
    question: "Что стоит проверить, если все route components импортированы статически в router config?",
    answers: [
      { id: "a", text: "Нужно ли заменить routes на CSS classes" },
      { id: "b", text: "Не увеличивает ли это initial bundle и стоит ли применить lazy loading для крупных страниц" },
      { id: "c", text: "Можно ли удалить RouterView" },
      { id: "d", text: "Почему query параметры стали обязательными" },
    ],
    correctAnswer: "b",
    explanation: "Статические imports могут попасть в стартовый bundle. Для крупных route-level screens lazy loading часто полезен. Но для маленьких критичных страниц статический импорт может быть нормальным.",
    knowledgeId: "knowledge-router-q822",
  },
  {
    id: 823,
    moduleId: "router",
    type: "Interview",
    difficulty: "Junior",
    tags: [
      "router-link",
      "navigation",
      "links",
    ],
    question: "Что делает RouterLink?",
    answers: [
      { id: "a", text: "Рендерит текущий route component" },
      { id: "b", text: "Создаёт navigation guard" },
      { id: "c", text: "Создаёт ссылку, которая навигирует через Vue Router без полной перезагрузки страницы" },
      { id: "d", text: "Хранит route meta" },
    ],
    correctAnswer: "c",
    explanation: "RouterLink заменяет обычный anchor для внутренних переходов SPA. Он генерирует ссылку и вызывает router navigation. RouterView отвечает за отображение компонента текущего route.",
    knowledgeId: "knowledge-router-q823",
  },
  {
    id: 824,
    moduleId: "router",
    type: "CodeReview",
    difficulty: "Junior",
    tags: [
      "router-view",
      "route-components",
      "layout",
    ],
    question: "Что делает RouterView?",
    answers: [
      { id: "a", text: "Создаёт кликабельную ссылку на route" },
      { id: "b", text: "Запускает Pinia action при каждом клике" },
      { id: "c", text: "Автоматически создаёт 404 страницу" },
      { id: "d", text: "Отображает компонент, соответствующий текущему matched route" },
    ],
    correctAnswer: "d",
    explanation: "RouterView — место, куда Vue Router вставляет component текущего matched route. RouterLink создаёт ссылки. 404 route нужно описывать в routes отдельно.",
    knowledgeId: "knowledge-router-q824",
  },
  {
    id: 825,
    moduleId: "router",
    type: "Interview",
    difficulty: "JuniorPlus",
    tags: [
      "useRouter",
      "useRoute",
      "composition-api",
    ],
    question: "Чем useRouter отличается от useRoute?",
    answers: [
      { id: "a", text: "useRouter возвращает router instance для навигации, useRoute возвращает текущий route object" },
      { id: "b", text: "useRoute нужен только для отправки push" },
      { id: "c", text: "useRouter возвращает только params" },
      { id: "d", text: "Они полностью идентичны" },
    ],
    correctAnswer: "a",
    explanation: "useRouter нужен для действий: push, replace, back. useRoute нужен для чтения текущего маршрута: params, query, meta, name, path. Путать их — частая ошибка новичков.",
    knowledgeId: "knowledge-router-q825",
  },
  {
    id: 826,
    moduleId: "router",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "programmatic-navigation",
      "router.push",
      "navigation",
    ],
    question: "Как выполнить программную навигацию на named route `profile`?",
    answers: [
      { id: "a", text: "route.push({ name: \"profile\" })" },
      { id: "b", text: "router.push({ name: \"profile\" })" },
      { id: "c", text: "RouterView.push(\"profile\")" },
      { id: "d", text: "meta.navigate(\"profile\")" },
    ],
    correctAnswer: "b",
    explanation: "Программная навигация выполняется через router instance. useRoute возвращает текущий route object и не имеет push. RouterView и meta не являются API навигации.",
    knowledgeId: "knowledge-router-q826",
  },
  {
    id: 827,
    moduleId: "router",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "active-classes",
      "router-link",
      "navigation",
    ],
    question: "Какой класс Vue Router по умолчанию добавляет активному RouterLink?",
    answers: [
      { id: "a", text: "active-route-link" },
      { id: "b", text: "is-current-view" },
      { id: "c", text: "router-link-active" },
      { id: "d", text: "vue-active-page" },
    ],
    correctAnswer: "c",
    explanation: "RouterLink получает классы активности, включая router-link-active и router-link-exact-active. Их можно переопределять глобально или через props. Это полезно для меню и nav UI.",
    knowledgeId: "knowledge-router-q827",
  },
  {
    id: 828,
    moduleId: "router",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "scrollBehavior",
      "ux",
      "navigation",
    ],
    question: "Для чего нужен scrollBehavior в router config?",
    answers: [
      { id: "a", text: "Чтобы валидировать auth token" },
      { id: "b", text: "Чтобы создавать route records" },
      { id: "c", text: "Чтобы менять active classes RouterLink" },
      { id: "d", text: "Чтобы управлять scroll position после навигации" },
    ],
    correctAnswer: "d",
    explanation: "scrollBehavior управляет прокруткой после перехода: наверх страницы, к anchor или сохранённой позиции. Это UX-настройка router. Auth, routes и active classes решаются отдельно.",
    knowledgeId: "knowledge-router-q828",
  },
  {
    id: 829,
    moduleId: "router",
    type: "Architecture",
    difficulty: "Senior",
    tags: [
      "auth-guard",
      "security",
      "architecture",
    ],
    question: "Какое утверждение про auth guard наиболее точное?",
    answers: [
      { id: "a", text: "Client-side guard улучшает UX, но не заменяет серверную проверку доступа" },
      { id: "b", text: "Client-side guard полностью защищает API от любых запросов" },
      { id: "c", text: "Auth guard должен хранить пароль пользователя в route meta" },
      { id: "d", text: "Auth guard нужен только для hash history" },
    ],
    correctAnswer: "a",
    explanation: "Router guard может не пустить пользователя на экран, но клиентский код нельзя считать границей безопасности. API всё равно должен проверять права на сервере. Route meta хранит требования доступа, а не секреты.",
    knowledgeId: "knowledge-router-q829",
  },
  {
    id: 830,
    moduleId: "router",
    type: "Scenario",
    difficulty: "Senior",
    tags: [
      "role-guard",
      "meta",
      "authorization",
    ],
    question: "Как лучше описать role guard для маршрутов с разными ролями?",
    answers: [
      { id: "a", text: "Дублировать проверки ролей в каждом template через v-if" },
      { id: "b", text: "Хранить required roles в route meta и проверять их в guard через централизованную функцию доступа" },
      { id: "c", text: "Хранить роли только в query string" },
      { id: "d", text: "Считать, что роль проверяется CSS-классом активной ссылки" },
    ],
    correctAnswer: "b",
    explanation: "Route meta хорошо подходит для декларативного описания требований маршрута. Guard может централизованно проверить пользователя и вернуть redirect. Template-only проверки не защищают навигацию, а query и CSS не являются источником авторизации.",
    knowledgeId: "knowledge-router-q830",
  },
  {
    id: 831,
    moduleId: "router",
    type: "Architecture",
    difficulty: "Senior",
    tags: [
      "breadcrumbs",
      "matched-routes",
      "meta",
    ],
    question: "Как обычно строят breadcrumbs на основе Vue Router?",
    answers: [
      { id: "a", text: "Парсят CSS-классы активных RouterLink" },
      { id: "b", text: "Берут breadcrumbs только из localStorage" },
      { id: "c", text: "Используют route.matched и meta с labels или функциями получения label" },
      { id: "d", text: "Создают отдельный router instance для каждой крошки" },
    ],
    correctAnswer: "c",
    explanation: "route.matched содержит цепочку matched route records, что удобно для breadcrumbs в nested routes. meta может хранить label, icon или функцию label от route. CSS и localStorage не являются устойчивым источником структуры маршрута.",
    knowledgeId: "knowledge-router-q831",
  },
  {
    id: 832,
    moduleId: "router",
    type: "BestPractice",
    difficulty: "Senior",
    tags: [
      "404",
      "not-found",
      "catch-all",
    ],
    question: "Что важно для 404 страницы в Vue Router?",
    answers: [
      { id: "a", text: "404 route должен быть первым в массиве routes" },
      { id: "b", text: "404 route обязан иметь children" },
      { id: "c", text: "404 route невозможен в SPA" },
      { id: "d", text: "Catch all route должен идти после более специфичных routes" },
    ],
    correctAnswer: "d",
    explanation: "Catch all route должен быть последним, чтобы не перехватить валидные маршруты раньше времени. Он отображает NotFound page для неизвестных URL. SPA вполне может иметь 404 экран.",
    knowledgeId: "knowledge-router-q832",
  },
  {
    id: 833,
    moduleId: "router",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "transitions",
      "router-view",
      "keep-alive",
    ],
    question: "Что важно учесть при transition между страницами через RouterView?",
    answers: [
      { id: "a", text: "Использовать slot API RouterView и правильно выбрать key, transition и KeepAlive при необходимости" },
      { id: "b", text: "Обернуть RouterLink в transition вместо RouterView всегда" },
      { id: "c", text: "Удалить route params, потому что transitions с ними не работают" },
      { id: "d", text: "Сделать все route components глобальными" },
    ],
    correctAnswer: "a",
    explanation: "Для page transitions часто используют `<RouterView v-slot=\"{ Component, route }\">` и оборачивают dynamic component в Transition. Key влияет на пересоздание компонентов. KeepAlive добавляет отдельные lifecycle considerations.",
    knowledgeId: "knowledge-router-q833",
  },
  {
    id: 834,
    moduleId: "router",
    type: "FindBug",
    difficulty: "Senior",
    tags: [
      "common-mistakes",
      "guards",
      "infinite-redirect",
    ],
    question: "Что может вызвать бесконечный redirect loop в navigation guard?",
    answers: [
      { id: "a", text: "Route имеет name вместо path" },
      { id: "b", text: "Guard перенаправляет на route, который снова удовлетворяет тому же условию redirect" },
      { id: "c", text: "RouterLink использует exact active class" },
      { id: "d", text: "Компонент загружается через dynamic import" },
    ],
    correctAnswer: "b",
    explanation: "Redirect loop возникает, если guard снова и снова возвращает redirect, не исключая целевой маршрут. Например, redirect на login должен проверять, что текущий route ещё не login. Name, active class и dynamic import не вызывают loop сами по себе.",
    knowledgeId: "knowledge-router-q834",
  },
  {
    id: 835,
    moduleId: "router",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "router-architecture",
      "common-mistakes",
      "senior",
    ],
    question: "Какая ошибка в архитектуре маршрутизации чаще всего проявляется при росте приложения?",
    answers: [
      { id: "a", text: "Использование named routes для программной навигации" },
      { id: "b", text: "Наличие отдельной 404 страницы" },
      { id: "c", text: "Смешивание auth, layout, breadcrumbs, permissions и route definitions без единого контракта meta" },
      { id: "d", text: "Lazy loading крупных route components" },
    ],
    correctAnswer: "c",
    explanation: "При росте приложения маршруты становятся инфраструктурой. Если требования доступа, layout, breadcrumbs и titles разбросаны по компонентам, систему трудно поддерживать. Named routes, 404 и lazy loading обычно помогают архитектуре.",
    knowledgeId: "knowledge-router-q835",
  },
]
