import type { ContentQuestion } from '../../../types/content'

export const slotsQuestions: ContentQuestion[] = [
  {
    id: 501,
    moduleId: "slots",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "slots",
      "component-api",
      "composition",
    ],
    question: "Что такое slot во Vue?",
    answers: [
      { id: "a", text: "Точка расширения компонента, куда родитель может передать разметку" },
      { id: "b", text: "Prop для передачи только строковых данных без разметки" },
      { id: "c", text: "Способ объявить событие компонента" },
      { id: "d", text: "Provide/inject канал для передачи состояния глубоко вниз" },
    ],
    correctAnswer: "a",
    explanation: "Slot позволяет родителю передать разметку в заранее определённое место дочернего компонента. Это отличается от props, которые передают данные и настройки, и от emits, которые сообщают о событиях. Provide/inject может передавать зависимости глубоко вниз, но не заменяет точку расширения разметки.",
    knowledgeId: "knowledge-slots-q501",
  },
  {
    id: 502,
    moduleId: "slots",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "default-slot",
      "slots",
      "template",
    ],
    question: "Что такое default slot?",
    answers: [
      { id: "a", text: "Prop со значением по умолчанию" },
      { id: "b", text: "Slot без имени, который принимает основной контент компонента" },
      { id: "c", text: "Событие, которое отправляется автоматически" },
      { id: "d", text: "Компонент, зарегистрированный глобально" },
    ],
    correctAnswer: "b",
    explanation: "Default slot — слот без имени, обычно используемый для главного содержимого компонента. Он не является prop, событием или глобальной регистрацией. Если родитель не передал контент, можно показать fallback.",
    knowledgeId: "knowledge-slots-q502",
  },
  {
    id: 503,
    moduleId: "slots",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "named-slots",
      "modal",
      "layout",
    ],
    question: "Что выбрать для модального окна с областями header, body и footer?",
    answers: [
      { id: "a", text: "Один prop с HTML-строкой для всей модалки" },
      { id: "b", text: "Глобальный event bus для передачи разметки" },
      { id: "c", text: "Named slots для header и footer плюс default slot для body" },
      { id: "d", text: "Только scoped CSS без slots" },
    ],
    correctAnswer: "c",
    explanation: "Named slots хорошо подходят для нескольких областей контента. Родитель может явно передать header, основное содержимое и footer. HTML-строки хуже для безопасности и композиции, а event bus и CSS не решают передачу разметки.",
    knowledgeId: "knowledge-slots-q503",
  },
  {
    id: 504,
    moduleId: "slots",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "scoped-slots",
      "slot-props",
      "headless",
    ],
    question: "Что такое scoped slot?",
    answers: [
      { id: "a", text: "Slot, который работает только со scoped CSS" },
      { id: "b", text: "Slot, который нельзя использовать повторно" },
      { id: "c", text: "Slot, автоматически создающий Pinia store" },
      { id: "d", text: "Slot, который получает данные от дочернего компонента через slot props" },
    ],
    correctAnswer: "d",
    explanation: "Scoped slot получает данные от дочернего компонента и позволяет родителю решить, как их отрисовать. Название не связано со scoped CSS. Это важный паттерн для headless и renderless компонентов.",
    knowledgeId: "knowledge-slots-q504",
  },
  {
    id: 505,
    moduleId: "slots",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "fallback-content",
      "default-slot",
      "template",
    ],
    question: "Что отрендерит `<slot>Нет данных</slot>`, если родитель не передал контент?",
    answers: [
      { id: "a", text: "Текст \"Нет данных\"" },
      { id: "b", text: "Пустой комментарий вместо slot" },
      { id: "c", text: "Ошибку компиляции" },
      { id: "d", text: "Имя родительского компонента" },
    ],
    correctAnswer: "a",
    explanation: "Контент внутри slot является fallback и отображается, когда родитель не передал содержимое. Это не ошибка компиляции. Vue не подставляет имя компонента автоматически.",
    knowledgeId: "knowledge-slots-q505",
  },
  {
    id: 506,
    moduleId: "slots",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "slot-props",
      "scoped-slots",
      "data-flow",
    ],
    question: "Для чего нужны slot props?",
    answers: [
      { id: "a", text: "Чтобы родитель напрямую мутировал state дочернего компонента" },
      { id: "b", text: "Чтобы дочерний компонент передал данные в slot-контент родителя" },
      { id: "c", text: "Чтобы заменить все props компонента" },
      { id: "d", text: "Чтобы объявить глобальные CSS-переменные" },
    ],
    correctAnswer: "b",
    explanation: "Slot props передают контекст из дочернего компонента в разметку, которую предоставляет родитель. Они не предназначены для прямой мутации внутреннего состояния. Это точечный API для кастомного рендера.",
    knowledgeId: "knowledge-slots-q506",
  },
  {
    id: 507,
    moduleId: "slots",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "useSlots",
      "composition-api",
      "conditional-ui",
    ],
    question: "Когда может понадобиться useSlots?",
    answers: [
      { id: "a", text: "Когда нужно объявить props компонента" },
      { id: "b", text: "Когда нужно отправить событие родителю" },
      { id: "c", text: "Когда в script setup нужно проверить наличие slot или передать slots дальше" },
      { id: "d", text: "Когда нужно создать computed из числа" },
    ],
    correctAnswer: "c",
    explanation: "useSlots даёт доступ к slots внутри setup-кода. Это полезно для условной разметки или forwarding. Props объявляет defineProps, события — defineEmits, а computed не требует useSlots.",
    knowledgeId: "knowledge-slots-q507",
  },
  {
    id: 508,
    moduleId: "slots",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "dynamic-slot-names",
      "named-slots",
      "template",
    ],
    question: "Что позволяют делать динамические имена слотов?",
    answers: [
      { id: "a", text: "Автоматически создавать component props" },
      { id: "b", text: "Менять имя файла компонента во время runtime" },
      { id: "c", text: "Отключать virtual DOM" },
      { id: "d", text: "Выбирать имя slot через выражение, например `#[slotName]`" },
    ],
    correctAnswer: "d",
    explanation: "Динамические имена слотов позволяют выбрать целевой named slot через выражение. Это полезно в генеративных layout или таблицах. Они не создают props и не влияют на имя файла или virtual DOM.",
    knowledgeId: "knowledge-slots-q508",
  },
  {
    id: 509,
    moduleId: "slots",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "slot-forwarding",
      "wrapper-components",
      "component-libraries",
    ],
    question: "Что такое slot forwarding?",
    answers: [
      { id: "a", text: "Проброс slot-контента через wrapper-компонент во внутренний компонент" },
      { id: "b", text: "Отправка slots через emit событие" },
      { id: "c", text: "Копирование props в localStorage" },
      { id: "d", text: "Автоматическое кеширование всех slots" },
    ],
    correctAnswer: "a",
    explanation: "Slot forwarding нужен wrapper-компонентам, которые оборачивают другой компонент и сохраняют его точки расширения. Slots не передаются через emit и не имеют отношения к localStorage. Такой паттерн важен в компонентных библиотеках.",
    knowledgeId: "knowledge-slots-q509",
  },
  {
    id: 510,
    moduleId: "slots",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "layout-components",
      "slots",
      "composition",
    ],
    question: "Почему layout-компоненты часто строят через slots?",
    answers: [
      { id: "a", text: "Slots автоматически делают layout быстрее любого CSS" },
      { id: "b", text: "Они задают структуру, но не должны знать конкретное содержимое" },
      { id: "c", text: "Slots запрещают родителю передавать компоненты" },
      { id: "d", text: "Layout-компоненты не могут принимать props" },
    ],
    correctAnswer: "b",
    explanation: "Layout-компонент задаёт рамку: панель, колонку, секцию, модалку. Конкретное содержимое лучше передать через slots. Props всё ещё могут задавать настройки layout, но не должны заменять произвольную разметку.",
    knowledgeId: "knowledge-slots-q510",
  },
  {
    id: 511,
    moduleId: "slots",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "renderless-components",
      "scoped-slots",
      "logic",
    ],
    question: "Что такое renderless component?",
    answers: [
      { id: "a", text: "Компонент, который полностью скрывает логику и не отдаёт данные наружу" },
      { id: "b", text: "Компонент, который навязывает фиксированную HTML-разметку без точек расширения" },
      { id: "c", text: "Компонент, который инкапсулирует логику и отдаёт данные для рендера через slot" },
      { id: "d", text: "Компонент, запрещающий scoped slots" },
    ],
    correctAnswer: "c",
    explanation: "Renderless component управляет логикой, но не навязывает HTML-структуру. Он отдаёт состояние и методы через scoped slot. Родитель сам решает, как отрисовать UI.",
    knowledgeId: "knowledge-slots-q511",
  },
  {
    id: 512,
    moduleId: "slots",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "headless-components",
      "renderless-components",
      "architecture",
    ],
    question: "Чем headless component похож на renderless component?",
    answers: [
      { id: "a", text: "Он всегда обязан использовать global registration" },
      { id: "b", text: "Он запрещает TypeScript" },
      { id: "c", text: "Он работает только без slots" },
      { id: "d", text: "Он отдаёт поведение и состояние, а визуальное представление оставляет потребителю" },
    ],
    correctAnswer: "d",
    explanation: "Headless component фокусируется на поведении и accessibility, оставляя визуальный слой потребителю. Slots часто становятся способом отдать контекст наружу. Это не связано с запретом TypeScript или глобальной регистрацией.",
    knowledgeId: "knowledge-slots-q512",
  },
  {
    id: 513,
    moduleId: "slots",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "slots-vs-props",
      "component-api",
      "design",
    ],
    question: "Главное отличие slots от props?",
    answers: [
      { id: "a", text: "Props передают данные и настройки, slots передают разметку" },
      { id: "b", text: "Slots работают только с числами" },
      { id: "c", text: "Props всегда медленнее slots" },
      { id: "d", text: "Slots нельзя использовать внутри SFC" },
    ],
    correctAnswer: "a",
    explanation: "Props и slots решают разные задачи компонентного API. Props подходят для данных, slots — для UI-фрагментов. Нельзя оценивать их как универсальную замену друг другу.",
    knowledgeId: "knowledge-slots-q513",
  },
  {
    id: 514,
    moduleId: "slots",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "when-slots-better",
      "props",
      "rich-content",
    ],
    question: "Когда slot обычно лучше prop?",
    answers: [
      { id: "a", text: "Когда нужно передать простое boolean значение disabled" },
      { id: "b", text: "Когда родителю нужно передать произвольную разметку, иконки или вложенные компоненты" },
      { id: "c", text: "Когда нужно передать id выбранного элемента" },
      { id: "d", text: "Когда нужно объявить payload события" },
    ],
    correctAnswer: "b",
    explanation: "Slot лучше, когда API должен принять не просто данные, а HTML-структуру или компонент. Простые значения вроде disabled и id лучше передавать props. Payload события описывается через emits.",
    knowledgeId: "knowledge-slots-q514",
  },
  {
    id: 515,
    moduleId: "slots",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "scoped-slots",
      "encapsulation",
      "headless",
    ],
    question: "Как scoped slots помогают сохранить инкапсуляцию?",
    answers: [
      { id: "a", text: "Они делают все внутренние refs родительскими" },
      { id: "b", text: "Они автоматически открывают private методы" },
      { id: "c", text: "Компонент отдаёт наружу только выбранный контекст, не раскрывая всю внутреннюю реализацию" },
      { id: "d", text: "Они запрещают дочернему компоненту хранить состояние" },
    ],
    correctAnswer: "c",
    explanation: "Scoped slot позволяет выбрать, какие данные и методы доступны для кастомного рендера. Внутренние детали компонента остаются скрытыми. Это сильнее, чем отдавать наружу весь state.",
    knowledgeId: "knowledge-slots-q515",
  },
  {
    id: 516,
    moduleId: "slots",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "slots-typing",
      "typescript",
      "component-api",
    ],
    question: "Зачем типизировать slots в компоненте?",
    answers: [
      { id: "a", text: "Чтобы запретить fallback content" },
      { id: "b", text: "Чтобы slots стали props автоматически" },
      { id: "c", text: "Чтобы отключить runtime rendering" },
      { id: "d", text: "Чтобы описать имена slots и slot props для TypeScript и потребителей компонента" },
    ],
    correctAnswer: "d",
    explanation: "Типизация slots помогает понять, какие slots поддерживает компонент и какие данные передаются в scoped slots. Она улучшает DX и снижает ошибки. Это не запрещает fallback и не превращает slots в props.",
    knowledgeId: "knowledge-slots-q516",
  },
  {
    id: 517,
    moduleId: "slots",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "defineSlots",
      "typescript",
      "script-setup",
    ],
    question: "Для чего используется defineSlots?",
    answers: [
      { id: "a", text: "Для типизации slots в `<script setup>`" },
      { id: "b", text: "Для объявления props компонента" },
      { id: "c", text: "Для отправки events родителю" },
      { id: "d", text: "Для создания async component" },
    ],
    correctAnswer: "a",
    explanation: "defineSlots — macro для описания slots и их props в script setup. Props объявляются через defineProps, события — через defineEmits. Async components создаются отдельным API.",
    knowledgeId: "knowledge-slots-q517",
  },
  {
    id: 518,
    moduleId: "slots",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "slot-data",
      "anti-pattern",
      "state",
    ],
    question: "Какая ошибка часто возникает при передаче данных через slots?",
    answers: [
      { id: "a", text: "Slot автоматически мутирует state родителя" },
      { id: "b", text: "Через slot начинают передавать данные, которым лучше быть props или typed state" },
      { id: "c", text: "Slot всегда удаляет fallback" },
      { id: "d", text: "Vue запрещает использовать slot props" },
    ],
    correctAnswer: "b",
    explanation: "Slots предназначены в первую очередь для разметки и кастомного рендера. Если через slots передаются обычные данные без UI-смысла, API становится запутанным. Props часто чище для структурированных значений.",
    knowledgeId: "knowledge-slots-q518",
  },
  {
    id: 519,
    moduleId: "slots",
    type: "Interview",
    difficulty: "MiddlePlus",
    tags: [
      "slots-performance",
      "rendering",
      "optimization",
    ],
    question: "Какое утверждение о производительности slots наиболее точное?",
    answers: [
      { id: "a", text: "Slots всегда быстрее любого prop" },
      { id: "b", text: "Slots полностью отключают обновления DOM" },
      { id: "c", text: "Slots обычно безопасны, но тяжёлый slot-контент всё равно участвует в рендере и должен проектироваться разумно" },
      { id: "d", text: "Scoped slots нельзя использовать в списках из-за ошибок Vue" },
    ],
    correctAnswer: "c",
    explanation: "Slots сами по себе не являются проблемой производительности, но переданный контент может быть тяжёлым. В списках, таблицах и scoped slots важно избегать лишней работы. Остальные варианты слишком категоричны и неверны.",
    knowledgeId: "knowledge-slots-q519",
  },
  {
    id: 520,
    moduleId: "slots",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "component-libraries",
      "slots",
      "ui-kit",
    ],
    question: "Почему slots важны в компонентных библиотеках?",
    answers: [
      { id: "a", text: "Они заменяют необходимость документировать API" },
      { id: "b", text: "Они автоматически делают все компоненты headless" },
      { id: "c", text: "Они запрещают использование props" },
      { id: "d", text: "Они дают пользователям библиотеки точки расширения без переписывания компонента" },
    ],
    correctAnswer: "d",
    explanation: "В библиотеках slots позволяют настраивать контент карточек, таблиц, модалок и форм. При этом компонент сохраняет структуру и поведение. Slots не отменяют документацию и props.",
    knowledgeId: "knowledge-slots-q520",
  },
  {
    id: 521,
    moduleId: "slots",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "tables",
      "scoped-slots",
      "custom-cell",
    ],
    question: "Как лучше дать пользователю таблицы кастомизировать рендер ячейки?",
    answers: [
      { id: "a", text: "Через scoped slot, передающий row, column и value" },
      { id: "b", text: "Через строку HTML в prop cellHtml" },
      { id: "c", text: "Через глобальный CSS-класс с JSON" },
      { id: "d", text: "Через прямую мутацию данных таблицы" },
    ],
    correctAnswer: "a",
    explanation: "Scoped slot позволяет таблице управлять данными и структурой, а родителю — кастомизировать отображение ячейки. HTML-строки хуже для безопасности и типизации. CSS и мутация данных не решают задачу рендера.",
    knowledgeId: "knowledge-slots-q521",
  },
  {
    id: 522,
    moduleId: "slots",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "modals",
      "named-slots",
      "actions",
    ],
    question: "Какие slots обычно полезны в компоненте модального окна?",
    answers: [
      { id: "a", text: "Только один slot с именем modelValue" },
      { id: "b", text: "header, default/body и footer/actions" },
      { id: "c", text: "Slots для каждого CSS-свойства" },
      { id: "d", text: "Только scoped slot без default контента" },
    ],
    correctAnswer: "b",
    explanation: "Модалка обычно имеет заголовок, основное содержимое и действия. Named slots делают эти области явными. modelValue лучше оставить prop для открытого состояния, а не именем slot.",
    knowledgeId: "knowledge-slots-q522",
  },
  {
    id: 523,
    moduleId: "slots",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "cards",
      "slots",
      "ui-components",
    ],
    question: "Какой API карточки гибче для произвольного содержимого?",
    answers: [
      { id: "a", text: "Один prop contentText для любого HTML" },
      { id: "b", text: "Только boolean props под каждый вариант" },
      { id: "c", text: "Default slot для body и named slots для header/actions" },
      { id: "d", text: "Глобальный event bus для передачи title" },
    ],
    correctAnswer: "c",
    explanation: "Карточка часто является контейнером, поэтому slots дают гибкую композицию. Props могут задавать варианты и состояния, но произвольную разметку лучше передавать slot. HTML-строки и множество boolean props ухудшают API.",
    knowledgeId: "knowledge-slots-q523",
  },
  {
    id: 524,
    moduleId: "slots",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "forms",
      "slots",
      "field-components",
    ],
    question: "Зачем field-компоненту может понадобиться slot для helper/error текста?",
    answers: [
      { id: "a", text: "Чтобы input перестал быть controlled" },
      { id: "b", text: "Чтобы отключить label" },
      { id: "c", text: "Чтобы заменить все emits" },
      { id: "d", text: "Чтобы родитель мог передать форматированное пояснение или ссылку" },
    ],
    correctAnswer: "d",
    explanation: "Helper или error область иногда содержит не только строку, но и ссылки, подсказки или форматирование. Slot даёт гибкость без HTML-строк. Он не меняет controlled-поведение и не заменяет events.",
    knowledgeId: "knowledge-slots-q524",
  },
  {
    id: 525,
    moduleId: "slots",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "slot-forwarding",
      "wrapper-components",
      "attrs",
    ],
    question: "Что стоит проверить в wrapper-компоненте, который оборачивает сторонний компонент со slots?",
    answers: [
      { id: "a", text: "Пробрасываются ли нужные slots и slot props без потери контракта" },
      { id: "b", text: "Удалены ли все slots ради простоты" },
      { id: "c", text: "Заменены ли все slots глобальными переменными" },
      { id: "d", text: "Мутирует ли wrapper slot props напрямую" },
    ],
    correctAnswer: "a",
    explanation: "Wrapper должен сохранять важные точки расширения внутреннего компонента. Если slots не проброшены, потребители теряют возможности кастомизации. Прямая мутация slot props и глобальные переменные ухудшают архитектуру.",
    knowledgeId: "knowledge-slots-q525",
  },
  {
    id: 526,
    moduleId: "slots",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "slot-api",
      "naming",
      "component-api",
    ],
    question: "Как лучше именовать named slots?",
    answers: [
      { id: "a", text: "Случайными сокращениями, чтобы template был короче" },
      { id: "b", text: "По смыслу области: header, footer, actions, item, empty" },
      { id: "c", text: "Именами внутренних ref дочернего компонента" },
      { id: "d", text: "Только числами, чтобы сортировать slots" },
    ],
    correctAnswer: "b",
    explanation: "Имена slots должны описывать область или назначение контента. Это делает API понятным без чтения внутренней реализации. Случайные имена и внутренние ref привязывают потребителя к деталям компонента.",
    knowledgeId: "knowledge-slots-q526",
  },
  {
    id: 527,
    moduleId: "slots",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "scoped-slots",
      "slot-props",
      "mutation",
    ],
    question: "Что не так с подходом, где родитель через scoped slot напрямую меняет переданный объект строки таблицы?",
    answers: [
      { id: "a", text: "Scoped slots вообще не могут получать объекты" },
      { id: "b", text: "Vue всегда копирует slot props глубоко" },
      { id: "c", text: "Slot используется для рендера, а мутация данных должна идти через явный API" },
      { id: "d", text: "Named slots перестают работать после мутации" },
    ],
    correctAnswer: "c",
    explanation: "Slot props могут содержать объекты, но прямые мутации из slot-контента создают неявные изменения. Лучше передать callback или отправить событие. Vue не делает глубокую копию slot props автоматически.",
    knowledgeId: "knowledge-slots-q527",
  },
  {
    id: 528,
    moduleId: "slots",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "scoped-slots",
      "destructuring",
      "template",
    ],
    question: "Что означает `#default=\"{ item }\"` в родительском template?",
    answers: [
      { id: "a", text: "Родитель объявляет prop item для дочернего компонента" },
      { id: "b", text: "Vue создаёт глобальную переменную item" },
      { id: "c", text: "Компонент отключает fallback content" },
      { id: "d", text: "Родитель получает slot prop item из default scoped slot" },
    ],
    correctAnswer: "d",
    explanation: "Синтаксис `#default=\"{ item }\"` деструктурирует slot props, переданные дочерним компонентом в default slot. Это не объявление props и не глобальная переменная. Fallback работает отдельно.",
    knowledgeId: "knowledge-slots-q528",
  },
  {
    id: 529,
    moduleId: "slots",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "slots",
      "api-design",
      "overengineering",
    ],
    question: "Когда slots могут сделать API компонента хуже?",
    answers: [
      { id: "a", text: "Когда через них передают простые данные и скрывают понятные props" },
      { id: "b", text: "Когда компонент имеет default slot для содержимого карточки" },
      { id: "c", text: "Когда named slots отражают реальные области layout" },
      { id: "d", text: "Когда fallback помогает пустому состоянию" },
    ],
    correctAnswer: "a",
    explanation: "Slots не должны заменять все props. Для простых данных typed props читаются лучше и проще валидируются. Slots сильны в передаче разметки и кастомного рендера, но могут усложнить API при неправильном применении.",
    knowledgeId: "knowledge-slots-q529",
  },
  {
    id: 530,
    moduleId: "slots",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "slots",
      "component-library",
      "documentation",
    ],
    question: "Что важно добавить в документацию компонента со scoped slots?",
    answers: [
      { id: "a", text: "Только цвет рамки компонента" },
      { id: "b", text: "Имена slots, структуру slot props и примеры использования" },
      { id: "c", text: "Список внутренних private refs" },
      { id: "d", text: "Запрет на TypeScript" },
    ],
    correctAnswer: "b",
    explanation: "Scoped slots являются частью публичного API, поэтому им нужны имена, типы slot props и примеры. Без документации потребителю сложно понять контракт. Внутренние refs раскрывать не нужно.",
    knowledgeId: "knowledge-slots-q530",
  },
]
