import type { ContentQuestion } from '../../../types/content'

export const componentsQuestions: ContentQuestion[] = [
  {
    id: 301,
    moduleId: "components",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "components",
      "architecture",
      "vue",
    ],
    question: "Что такое компонент во Vue?",
    answers: [
      { id: "a", text: "Переиспользуемая часть интерфейса со своим template, логикой и стилями" },
      { id: "b", text: "Отдельный npm-пакет, который всегда публикуется в registry" },
      { id: "c", text: "Способ заменить все CSS-классы JavaScript-функциями" },
      { id: "d", text: "Файл конфигурации только для роутера" },
    ],
    correctAnswer: "a",
    explanation: "Компонент во Vue — это самостоятельная единица интерфейса, которую можно переиспользовать и комбинировать с другими компонентами. Он может принимать props, отправлять события и иметь собственное состояние. Остальные варианты описывают unrelated вещи: npm-пакеты, CSS-подходы и конфигурацию роутера.",
    knowledgeId: "knowledge-components-q301",
  },
  {
    id: 302,
    moduleId: "components",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "sfc",
      "single-file-component",
      "vue",
    ],
    question: "Что такое Single File Component во Vue?",
    answers: [
      { id: "a", text: "JSON-файл с настройками всех маршрутов" },
      { id: "b", text: "Файл .vue, который объединяет template, script и style одного компонента" },
      { id: "c", text: "Компонент, который нельзя импортировать в другие файлы" },
      { id: "d", text: "CSS-файл, автоматически превращающийся в компонент" },
    ],
    correctAnswer: "b",
    explanation: "Single File Component — это .vue-файл, где рядом находятся разметка, логика и стили компонента. Такой формат делает границы компонента понятными и удобными для сборщика. JSON, запрет импортов и CSS-файлы не описывают SFC.",
    knowledgeId: "knowledge-components-q302",
  },
  {
    id: 303,
    moduleId: "components",
    type: "CodeReview",
    difficulty: "JuniorPlus",
    tags: [
      "template",
      "script",
      "style",
      "sfc",
    ],
    question: "Какую роль обычно выполняет блок `<template>` в SFC?",
    answers: [
      { id: "a", text: "Устанавливает зависимости npm" },
      { id: "b", text: "Заменяет TypeScript-компилятор" },
      { id: "c", text: "Описывает декларативную структуру DOM, которую рендерит компонент" },
      { id: "d", text: "Хранит только глобальные CSS-переменные" },
    ],
    correctAnswer: "c",
    explanation: "template отвечает за декларативное описание UI. script содержит состояние, props, emits и логику, а style — стили компонента. Установка зависимостей, компиляция TypeScript и хранение глобальных CSS-переменных не являются задачей template.",
    knowledgeId: "knowledge-components-q303",
  },
  {
    id: 304,
    moduleId: "components",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "registration",
      "local-registration",
      "global-registration",
    ],
    question: "Когда локальная регистрация компонента обычно предпочтительнее глобальной?",
    answers: [
      { id: "a", text: "Когда компонент должен стать доступен без импорта во всех файлах" },
      { id: "b", text: "Когда нужно отключить tree-shaking для всех компонентов" },
      { id: "c", text: "Когда компонент не имеет template" },
      { id: "d", text: "Когда компонент используется в ограниченном месте и не нужен всему приложению" },
    ],
    correctAnswer: "d",
    explanation: "Локальная регистрация делает зависимости компонента явными и снижает риск разрастания глобального пространства имён. Глобальная регистрация удобна для базовых UI-элементов или компонентов, которые действительно используются повсюду. Остальные варианты не являются преимуществами локальной регистрации.",
    knowledgeId: "knowledge-components-q304",
  },
  {
    id: 305,
    moduleId: "components",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "props",
      "component-api",
      "data-flow",
    ],
    question: "Для чего нужны props в компонентах Vue?",
    answers: [
      { id: "a", text: "Чтобы передавать данные от родителя к дочернему компоненту" },
      { id: "b", text: "Чтобы дочерний компонент напрямую менял state родителя" },
      { id: "c", text: "Чтобы заменить все события компонента" },
      { id: "d", text: "Чтобы хранить глобальный кэш приложения" },
    ],
    correctAnswer: "a",
    explanation: "Props описывают входные данные компонента и задают его публичный API. Они передаются сверху вниз: от родителя к дочернему компоненту. Для уведомления родителя используют emits, а не прямую мутацию props.",
    knowledgeId: "knowledge-components-q305",
  },
  {
    id: 306,
    moduleId: "components",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "emits",
      "events",
      "component-api",
    ],
    question: "Что описывает emits в компоненте Vue?",
    answers: [
      { id: "a", text: "Список CSS-классов компонента" },
      { id: "b", text: "События, которые компонент может отправить родителю" },
      { id: "c", text: "Все props, полученные от родителя" },
      { id: "d", text: "Маршруты, доступные компоненту" },
    ],
    correctAnswer: "b",
    explanation: "emits задаёт события компонента и делает его коммуникацию с родителем явной. Через события дочерний компонент сообщает о действиях пользователя или внутренних изменениях. CSS-классы, props и маршруты решаются другими механизмами.",
    knowledgeId: "knowledge-components-q306",
  },
  {
    id: 307,
    moduleId: "components",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "component-events",
      "data-flow",
      "parent-child",
    ],
    question: "Дочерний компонент должен сообщить родителю, что пользователь выбрал пункт. Что лучше использовать?",
    answers: [
      { id: "a", text: "Прямую мутацию prop внутри дочернего компонента" },
      { id: "b", text: "Изменение document.title" },
      { id: "c", text: "emit события с payload выбранного пункта" },
      { id: "d", text: "Создание глобальной переменной window.selected" },
    ],
    correctAnswer: "c",
    explanation: "Для связи снизу вверх во Vue используют события компонента. Дочерний компонент отправляет событие, а родитель решает, как обновить состояние. Мутация prop нарушает однонаправленный поток данных, а глобальные переменные делают поведение хрупким.",
    knowledgeId: "knowledge-components-q307",
  },
  {
    id: 308,
    moduleId: "components",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "slots",
      "composition",
      "content",
    ],
    question: "Что позволяют делать slots во Vue?",
    answers: [
      { id: "a", text: "Автоматически типизировать все emits" },
      { id: "b", text: "Создавать новые props без объявления" },
      { id: "c", text: "Отключать reactivity tracking" },
      { id: "d", text: "Передавать фрагменты разметки внутрь компонента" },
    ],
    correctAnswer: "d",
    explanation: "Slots позволяют родителю передать контент в заранее предусмотренное место дочернего компонента. Это делает компонент гибким без расширения числа props. Типизация emits, объявление props и отключение реактивности к slots не относятся.",
    knowledgeId: "knowledge-components-q308",
  },
  {
    id: 309,
    moduleId: "components",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "named-slots",
      "slots",
      "layout",
    ],
    question: "Для чего нужны named slots?",
    answers: [
      { id: "a", text: "Чтобы передавать разные фрагменты контента в разные области компонента" },
      { id: "b", text: "Чтобы дать компоненту несколько имён файла" },
      { id: "c", text: "Чтобы заменить props на CSS-переменные" },
      { id: "d", text: "Чтобы отключить default slot" },
    ],
    correctAnswer: "a",
    explanation: "Named slots нужны, когда компонент имеет несколько областей для контента: header, default, footer и другие. Родитель явно указывает, какой фрагмент куда попадёт. Это не связано с именами файлов или CSS-переменными.",
    knowledgeId: "knowledge-components-q309",
  },
  {
    id: 310,
    moduleId: "components",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "scoped-slots",
      "slots",
      "slot-props",
    ],
    question: "Как scoped slot помогает компоненту передать данные наружу?",
    answers: [
      { id: "a", text: "Slot, который работает только со scoped CSS" },
      { id: "b", text: "Slot, который получает данные от дочернего компонента через slot props" },
      { id: "c", text: "Slot, который нельзя переиспользовать" },
      { id: "d", text: "Slot, который автоматически становится глобальным" },
    ],
    correctAnswer: "b",
    explanation: "Scoped slot позволяет дочернему компоненту передать данные в slot-контент родителя. Это удобно для headless-компонентов и списков с кастомным отображением. Scoped CSS и глобальность не определяют scoped slots.",
    knowledgeId: "knowledge-components-q310",
  },
  {
    id: 311,
    moduleId: "components",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "attrs",
      "fallthrough-attributes",
      "component-api",
    ],
    question: "Что такое fallthrough attributes во Vue?",
    answers: [
      { id: "a", text: "Props, которые Vue всегда удаляет при рендере" },
      { id: "b", text: "События, которые автоматически становятся slots" },
      { id: "c", text: "Атрибуты, не объявленные как props, которые могут попасть на корневой элемент компонента" },
      { id: "d", text: "CSS-переменные, доступные только в style scoped" },
    ],
    correctAnswer: "c",
    explanation: "Fallthrough attributes — это class, id, aria-* и другие атрибуты, которые не объявлены как props. Vue может передать их на корневой элемент компонента. Для wrapper-компонентов ими часто управляют вручную через attrs.",
    knowledgeId: "knowledge-components-q311",
  },
  {
    id: 312,
    moduleId: "components",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "attrs",
      "inheritAttrs",
      "wrapper-components",
    ],
    question: "Когда стоит управлять attrs вручную через `useAttrs()` или `inheritAttrs: false`?",
    answers: [
      { id: "a", text: "Когда нужно запретить все props компонента" },
      { id: "b", text: "Когда нужно отключить template" },
      { id: "c", text: "Когда нужно создать computed без зависимостей" },
      { id: "d", text: "Когда wrapper-компонент должен передать атрибуты на конкретный внутренний элемент" },
    ],
    correctAnswer: "d",
    explanation: "Wrapper-компонент может иметь несколько внутренних элементов, и атрибуты важно передать на правильный DOM-узел. useAttrs и inheritAttrs помогают контролировать этот поток. Они не запрещают props и не относятся к computed или template.",
    knowledgeId: "knowledge-components-q312",
  },
  {
    id: 313,
    moduleId: "components",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "dynamic-components",
      "component-is",
      "tabs",
    ],
    question: "Что выбрать, если нужно переключать несколько компонентов в одной области UI?",
    answers: [
      { id: "a", text: "Dynamic component через `<component :is=\"currentComponent\" />`" },
      { id: "b", text: "Один огромный v-if со всей логикой во всех ветках" },
      { id: "c", text: "Прямое изменение innerHTML" },
      { id: "d", text: "Глобальную переменную с HTML-строкой" },
    ],
    correctAnswer: "a",
    explanation: "Dynamic components позволяют выбрать компонент во время рендера и хорошо подходят для вкладок, режимов и pluggable UI. Большой набор v-if может быстро стать плохо поддерживаемым. innerHTML и глобальные HTML-строки ухудшают безопасность и архитектуру.",
    knowledgeId: "knowledge-components-q313",
  },
  {
    id: 314,
    moduleId: "components",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "keep-alive",
      "dynamic-components",
      "cache",
    ],
    question: "Для чего используется `<KeepAlive>`?",
    answers: [
      { id: "a", text: "Чтобы запретить unmount всего приложения" },
      { id: "b", text: "Чтобы кэшировать состояние переключаемых компонентов" },
      { id: "c", text: "Чтобы сделать props mutable" },
      { id: "d", text: "Чтобы загрузить CSS асинхронно" },
    ],
    correctAnswer: "b",
    explanation: "KeepAlive кэширует экземпляры компонентов, чаще всего при dynamic components или router view. Это сохраняет локальное состояние между переключениями. Он не делает props изменяемыми и не управляет загрузкой CSS.",
    knowledgeId: "knowledge-components-q314",
  },
  {
    id: 315,
    moduleId: "components",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "async-components",
      "performance",
      "code-splitting",
    ],
    question: "Когда полезны async components?",
    answers: [
      { id: "a", text: "Когда нужно сделать ref асинхронным" },
      { id: "b", text: "Когда нужно запретить slots" },
      { id: "c", text: "Когда компонент тяжёлый или нужен не сразу, и его можно загрузить по требованию" },
      { id: "d", text: "Когда компонент должен работать без сборщика" },
    ],
    correctAnswer: "c",
    explanation: "Async components помогают откладывать загрузку тяжёлых или редко используемых частей интерфейса. Это улучшает начальную загрузку и поддерживает code splitting. Они не относятся к ref, slots или отказу от сборщика.",
    knowledgeId: "knowledge-components-q315",
  },
  {
    id: 316,
    moduleId: "components",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "template-refs",
      "component-refs",
      "dom",
    ],
    question: "Когда template ref на дочерний компонент становится доступен?",
    answers: [
      { id: "a", text: "До выполнения setup" },
      { id: "b", text: "Только после изменения props" },
      { id: "c", text: "Он никогда не доступен для компонентов" },
      { id: "d", text: "После монтирования родительского компонента" },
    ],
    correctAnswer: "d",
    explanation: "Template ref на DOM или компонент становится доступен после монтирования. До этого дочерний экземпляр ещё не создан в DOM-дереве. Для доступа к методам дочернего компонента в script setup может понадобиться defineExpose.",
    knowledgeId: "knowledge-components-q316",
  },
  {
    id: 317,
    moduleId: "components",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "v-model",
      "component-api",
      "forms",
    ],
    question: "Что обычно означает v-model на компоненте?",
    answers: [
      { id: "a", text: "Связку prop modelValue и события update:modelValue или defineModel" },
      { id: "b", text: "Автоматическую мутацию любого prop" },
      { id: "c", text: "Запрет на emits в компоненте" },
      { id: "d", text: "Подключение Vue Router к форме" },
    ],
    correctAnswer: "a",
    explanation: "v-model на компоненте — это соглашение для двустороннего API: значение приходит через prop, изменение отправляется событием. В современных компонентах это может упрощаться через defineModel. Прямая мутация prop не является корректным v-model.",
    knowledgeId: "knowledge-components-q317",
  },
  {
    id: 318,
    moduleId: "components",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "defineProps",
      "script-setup",
      "props",
    ],
    question: "Что делает defineProps в `<script setup>`?",
    answers: [
      { id: "a", text: "Отправляет событие родителю" },
      { id: "b", text: "Объявляет входные props компонента" },
      { id: "c", text: "Открывает методы компонента через ref" },
      { id: "d", text: "Создаёт named slots" },
    ],
    correctAnswer: "b",
    explanation: "defineProps — compile-time макрос для объявления props в script setup. События объявляются через defineEmits, публичные методы через defineExpose, а slots передаются через template. Макрос задаёт входной контракт компонента.",
    knowledgeId: "knowledge-components-q318",
  },
  {
    id: 319,
    moduleId: "components",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "defineEmits",
      "script-setup",
      "events",
    ],
    question: "Что возвращает defineEmits в `<script setup>`?",
    answers: [
      { id: "a", text: "Объект всех props" },
      { id: "b", text: "DOM-элемент компонента" },
      { id: "c", text: "Функцию emit для отправки объявленных событий" },
      { id: "d", text: "Компонентный slot" },
    ],
    correctAnswer: "c",
    explanation: "defineEmits объявляет события компонента и возвращает функцию emit. Через неё компонент сообщает родителю о действиях. Props, DOM-элементы и slots получаются другими API.",
    knowledgeId: "knowledge-components-q319",
  },
  {
    id: 320,
    moduleId: "components",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "defineExpose",
      "public-api",
      "component-ref",
    ],
    question: "Когда нужен defineExpose?",
    answers: [
      { id: "a", text: "Когда нужно автоматически открыть все локальные переменные глобально" },
      { id: "b", text: "Когда нужно объявить props" },
      { id: "c", text: "Когда нужно зарегистрировать CSS module" },
      { id: "d", text: "Когда компонент на script setup должен явно открыть методы или значения родителю через ref" },
    ],
    correctAnswer: "d",
    explanation: "Компоненты на script setup по умолчанию не раскрывают все локальные объявления наружу. defineExpose позволяет явно сформировать публичный API для template ref. Это не глобализация переменных и не замена props.",
    knowledgeId: "knowledge-components-q320",
  },
  {
    id: 321,
    moduleId: "components",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "defineOptions",
      "script-setup",
      "component-options",
    ],
    question: "Для чего используется defineOptions?",
    answers: [
      { id: "a", text: "Чтобы задать опции компонента внутри script setup, например name или inheritAttrs" },
      { id: "b", text: "Чтобы объявить runtime route guards" },
      { id: "c", text: "Чтобы отправлять emits без объявления" },
      { id: "d", text: "Чтобы превратить slots в props" },
    ],
    correctAnswer: "a",
    explanation: "defineOptions позволяет указать некоторые опции компонента прямо в script setup. Частые примеры — name и inheritAttrs. Он не относится к роутеру, не отменяет объявления emits и не превращает slots в props.",
    knowledgeId: "knowledge-components-q321",
  },
  {
    id: 322,
    moduleId: "components",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "decomposition",
      "component-design",
      "architecture",
    ],
    question: "Какой признак говорит, что компонент пора декомпозировать?",
    answers: [
      { id: "a", text: "В компоненте есть один prop" },
      { id: "b", text: "В компоненте смешались несколько независимых ответственностей и сценариев UI" },
      { id: "c", text: "В template есть один div" },
      { id: "d", text: "Компонент использует scoped styles" },
    ],
    correctAnswer: "b",
    explanation: "Декомпозиция нужна, когда компонент становится трудно читать из-за смешения обязанностей. Хорошая граница выделяет самостоятельную часть UI или поведения. Один prop, один div или scoped styles сами по себе не требуют разбиения.",
    knowledgeId: "knowledge-components-q322",
  },
  {
    id: 323,
    moduleId: "components",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "dumb-components",
      "smart-components",
      "architecture",
    ],
    question: "Как обычно различают dumb и smart components?",
    answers: [
      { id: "a", text: "Dumb-компоненты всегда запрещены во Vue" },
      { id: "b", text: "Smart-компоненты не могут иметь props" },
      { id: "c", text: "Dumb-компоненты отвечают за отображение, smart-компоненты координируют данные и сценарии" },
      { id: "d", text: "Dumb-компоненты обязательно должны быть глобальными" },
    ],
    correctAnswer: "c",
    explanation: "Dumb-компоненты обычно получают данные через props и отправляют события, не зная источника данных. Smart-компоненты собирают данные, вызывают composables или stores и передают всё ниже. Это архитектурное разделение, а не строгий запрет или требование глобальности.",
    knowledgeId: "knowledge-components-q323",
  },
  {
    id: 324,
    moduleId: "components",
    type: "Architecture",
    difficulty: "MiddlePlus",
    tags: [
      "controlled-components",
      "uncontrolled-components",
      "forms",
    ],
    question: "Что означает controlled component подход?",
    answers: [
      { id: "a", text: "Компонент полностью скрывает состояние и не принимает props" },
      { id: "b", text: "Компонент нельзя переиспользовать" },
      { id: "c", text: "Компонент управляется только CSS" },
      { id: "d", text: "Важное состояние хранится снаружи, а компонент получает value и сообщает изменения событиями" },
    ],
    correctAnswer: "d",
    explanation: "Controlled component получает значение извне и сообщает о намерении изменить его через событие. Родитель остаётся источником истины. Uncontrolled-подход хранит состояние внутри компонента и подходит для более автономных сценариев.",
    knowledgeId: "knowledge-components-q324",
  },
  {
    id: 325,
    moduleId: "components",
    type: "FindBug",
    difficulty: "JuniorPlus",
    tags: [
      "props",
      "mutation",
      "anti-pattern",
    ],
    question: "Что не так с кодом, где дочерний компонент напрямую меняет `props.title`?",
    answers: [
      { id: "a", text: "Props считаются входными данными, их нельзя мутировать напрямую в дочернем компоненте" },
      { id: "b", text: "Props нельзя читать в template" },
      { id: "c", text: "Props работают только с числами" },
      { id: "d", text: "Props автоматически становятся global state" },
    ],
    correctAnswer: "a",
    explanation: "Props передаются от родителя к дочернему компоненту и должны оставаться входным контрактом. Дочерний компонент может отправить событие, чтобы родитель обновил значение. Чтение props в template разрешено, тип props не ограничен только числами.",
    knowledgeId: "knowledge-components-q325",
  },
  {
    id: 326,
    moduleId: "components",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "key",
      "component-lifecycle",
      "lists",
    ],
    question: "Почему для компонентов в списке важен стабильный `key`?",
    answers: [
      { id: "a", text: "Он делает props readonly" },
      { id: "b", text: "Он помогает Vue корректно сопоставлять экземпляры компонентов при обновлениях списка" },
      { id: "c", text: "Он автоматически сортирует массив" },
      { id: "d", text: "Он заменяет emit событиями DOM" },
    ],
    correctAnswer: "b",
    explanation: "Стабильный key помогает Vue понять, какой элемент списка соответствует какому экземпляру компонента. Это особенно важно, если у компонентов есть локальное состояние или поля ввода. key не сортирует данные и не меняет поведение props или emits.",
    knowledgeId: "knowledge-components-q326",
  },
  {
    id: 327,
    moduleId: "components",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "reuse",
      "component-api",
      "composition",
    ],
    question: "Что делает компонент действительно переиспользуемым?",
    answers: [
      { id: "a", text: "Большое количество внутренних глобальных переменных" },
      { id: "b", text: "Жёсткая привязка к одному родительскому компоненту" },
      { id: "c", text: "Понятный API через props, события и slots без скрытых зависимостей" },
      { id: "d", text: "Отсутствие типов у props и emits" },
    ],
    correctAnswer: "c",
    explanation: "Переиспользуемый компонент имеет ясный контракт: что он принимает, что отправляет и где позволяет вставить контент. Скрытые зависимости и привязка к одному родителю делают компонент хрупким. Типизация API улучшает поддержку.",
    knowledgeId: "knowledge-components-q327",
  },
  {
    id: 328,
    moduleId: "components",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "slots",
      "fallback-content",
      "template",
    ],
    question: "Что отрендерится внутри `<slot>Fallback</slot>`, если родитель не передал контент?",
    answers: [
      { id: "a", text: "Пустая строка всегда" },
      { id: "b", text: "Ошибка компиляции" },
      { id: "c", text: "Имя компонента" },
      { id: "d", text: "Fallback-контент" },
    ],
    correctAnswer: "d",
    explanation: "Если родитель не передал содержимое для slot, Vue показывает fallback-контент внутри slot. Это удобный способ задать безопасное значение по умолчанию. Ошибка компиляции не возникает, а имя компонента не подставляется автоматически.",
    knowledgeId: "knowledge-components-q328",
  },
  {
    id: 329,
    moduleId: "components",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "component-api",
      "props-vs-slots",
      "design-system",
    ],
    question: "Что лучше выбрать для кастомного содержимого карточки: prop `contentText` или slot?",
    answers: [
      { id: "a", text: "Slot, если родителю нужно передавать произвольную разметку, а не только строку" },
      { id: "b", text: "Только prop, потому что slots не поддерживают HTML" },
      { id: "c", text: "Только глобальную переменную, чтобы избежать props" },
      { id: "d", text: "Ни props, ни slot, потому что компонент не может принимать контент" },
    ],
    correctAnswer: "a",
    explanation: "Props хорошо подходят для структурированных данных и простых значений. Slots лучше подходят для произвольной разметки, например кнопок, форматированного текста или вложенных элементов. Это делает компонент гибким без усложнения набора props.",
    knowledgeId: "knowledge-components-q329",
  },
  {
    id: 330,
    moduleId: "components",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "component-boundaries",
      "coupling",
      "architecture",
    ],
    question: "Что является тревожным признаком в API переиспользуемого компонента?",
    answers: [
      { id: "a", text: "Компонент принимает typed props" },
      { id: "b", text: "Props отражают внутренние детали конкретного родителя, а не смысл самого компонента" },
      { id: "c", text: "Компонент отправляет явно объявленные events" },
      { id: "d", text: "Компонент имеет slot для дополнительного контента" },
    ],
    correctAnswer: "b",
    explanation: "Если API компонента повторяет внутренние детали одного родителя, переиспользование становится почти невозможным. Хороший компонент говорит языком своей ответственности: label, value, disabled, selected и так далее. Typed props, events и slots обычно помогают контракту.",
    knowledgeId: "knowledge-components-q330",
  },
]
