import type { ContentQuestion } from '../../../types/content'

export const lifecycleQuestions: ContentQuestion[] = [
  {
    id: 601,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "lifecycle",
      "component",
      "vue",
    ],
    question: "Что описывает жизненный цикл компонента Vue?",
    answers: [
      { id: "a", text: "Этапы создания, монтирования, обновления, деактивации и удаления компонента" },
      { id: "b", text: "Только порядок вызова watchers после каждого изменения ref" },
      { id: "c", text: "Только процесс передачи props от родителя к дочернему компоненту" },
      { id: "d", text: "Только правила кеширования компонента внутри KeepAlive" },
    ],
    correctAnswer: "a",
    explanation: "Жизненный цикл описывает, когда компонент создаётся, монтируется в DOM, обновляется, деактивируется и удаляется. Watchers, props и KeepAlive связаны с жизнью компонента, но не описывают весь набор этапов сами по себе. Hooks жизненного цикла позволяют выполнить код в нужный момент.",
    knowledgeId: "knowledge-lifecycle-q601",
  },
  {
    id: 602,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "setup",
      "composition-api",
      "lifecycle",
    ],
    question: "Когда выполняется setup в Composition API?",
    answers: [
      { id: "a", text: "Только после onUnmounted" },
      { id: "b", text: "До монтирования компонента, при создании его экземпляра" },
      { id: "c", text: "После каждого обновления DOM" },
      { id: "d", text: "Только при наведении мыши" },
    ],
    correctAnswer: "b",
    explanation: "setup выполняется рано, до монтирования DOM. В нём создают reactive state, computed, watchers и регистрируют lifecycle hooks. DOM-элементы ещё недоступны, поэтому для работы с ними используют onMounted.",
    knowledgeId: "knowledge-lifecycle-q602",
  },
  {
    id: 603,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "onBeforeMount",
      "mounting",
      "dom",
    ],
    question: "Что означает onBeforeMount?",
    answers: [
      { id: "a", text: "Hook после удаления компонента" },
      { id: "b", text: "Hook, который вызывается только при ошибке" },
      { id: "c", text: "Hook перед первым монтированием, когда render уже подготовлен, но DOM ещё не вставлен" },
      { id: "d", text: "Hook для кешированных компонентов KeepAlive после активации" },
    ],
    correctAnswer: "c",
    explanation: "onBeforeMount вызывается перед вставкой компонента в DOM. Это не момент для чтения template refs, потому что DOM ещё не готов. Для доступа к DOM используют onMounted.",
    knowledgeId: "knowledge-lifecycle-q603",
  },
  {
    id: 604,
    moduleId: "lifecycle",
    type: "Scenario",
    difficulty: "Junior",
    tags: [
      "onMounted",
      "dom",
      "template-refs",
    ],
    question: "В каком hook обычно безопасно вызвать focus() на input через template ref?",
    answers: [
      { id: "a", text: "setup до объявления ref" },
      { id: "b", text: "onBeforeMount всегда" },
      { id: "c", text: "onErrorCaptured" },
      { id: "d", text: "onMounted" },
    ],
    correctAnswer: "d",
    explanation: "Template ref на DOM-элемент становится доступен после монтирования. Поэтому focus, измерения размеров и интеграции с DOM обычно выполняют в onMounted. До монтирования ссылка будет null.",
    knowledgeId: "knowledge-lifecycle-q604",
  },
  {
    id: 605,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "onBeforeUpdate",
      "updates",
      "dom",
    ],
    question: "Когда вызывается onBeforeUpdate?",
    answers: [
      { id: "a", text: "Перед обновлением DOM после изменения реактивных зависимостей" },
      { id: "b", text: "Перед первым созданием setup" },
      { id: "c", text: "Только перед удалением компонента" },
      { id: "d", text: "Только внутри SSR" },
    ],
    correctAnswer: "a",
    explanation: "onBeforeUpdate вызывается после изменения reactive state, но до patch DOM. Этот hook нужен редко, но полезен, если нужно получить состояние DOM перед обновлением. Он не относится к первому setup или удалению.",
    knowledgeId: "knowledge-lifecycle-q605",
  },
  {
    id: 606,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "onUpdated",
      "updates",
      "dom",
    ],
    question: "Что важно помнить про onUpdated?",
    answers: [
      { id: "a", text: "Он вызывается до setup" },
      { id: "b", text: "Он вызывается после DOM-обновления, но менять там state нужно осторожно, чтобы не создать цикл" },
      { id: "c", text: "Он заменяет computed для derived state" },
      { id: "d", text: "Он работает только для props" },
    ],
    correctAnswer: "b",
    explanation: "onUpdated срабатывает после обновления DOM. Если внутри него без условий менять reactive state, можно вызвать новое обновление и получить цикл. Для derived state лучше computed, а не lifecycle hook.",
    knowledgeId: "knowledge-lifecycle-q606",
  },
  {
    id: 607,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "onBeforeUnmount",
      "cleanup",
      "unmount",
    ],
    question: "Для чего может быть полезен onBeforeUnmount?",
    answers: [
      { id: "a", text: "Чтобы получить DOM до первого mount" },
      { id: "b", text: "Чтобы объявить props" },
      { id: "c", text: "Чтобы выполнить действия перед удалением компонента, пока экземпляр ещё активен" },
      { id: "d", text: "Чтобы заменить router guard" },
    ],
    correctAnswer: "c",
    explanation: "onBeforeUnmount вызывается перед размонтированием. Он полезен для подготовки cleanup, сохранения финального состояния или остановки процессов. Props и router guards решаются другими механизмами.",
    knowledgeId: "knowledge-lifecycle-q607",
  },
  {
    id: 608,
    moduleId: "lifecycle",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "onUnmounted",
      "cleanup",
      "subscriptions",
    ],
    question: "Что обычно делают в onUnmounted?",
    answers: [
      { id: "a", text: "Создают props компонента" },
      { id: "b", text: "Добавляют новый route" },
      { id: "c", text: "Запускают бесконечный render loop" },
      { id: "d", text: "Очищают подписки, timers, observers и внешние listeners" },
    ],
    correctAnswer: "d",
    explanation: "onUnmounted — подходящее место для очистки ресурсов, которые компонент создал во время жизни. Это предотвращает утечки памяти и обращения к устаревшему состоянию. Props и routes не относятся к cleanup.",
    knowledgeId: "knowledge-lifecycle-q608",
  },
  {
    id: 609,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "onActivated",
      "keep-alive",
      "cache",
    ],
    question: "Когда вызывается onActivated?",
    answers: [
      { id: "a", text: "Когда кешированный KeepAlive-компонент снова становится активным" },
      { id: "b", text: "Перед первым созданием reactive state" },
      { id: "c", text: "При любой ошибке внутри дочернего компонента" },
      { id: "d", text: "Только при изменении CSS-класса" },
    ],
    correctAnswer: "a",
    explanation: "onActivated связан с KeepAlive. Он срабатывает, когда кешированный компонент возвращается в активное состояние. Для обычного mount используется onMounted, а для ошибок — onErrorCaptured.",
    knowledgeId: "knowledge-lifecycle-q609",
  },
  {
    id: 610,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "onDeactivated",
      "keep-alive",
      "cache",
    ],
    question: "Что означает onDeactivated?",
    answers: [
      { id: "a", text: "Компонент окончательно удалён из памяти" },
      { id: "b", text: "KeepAlive-компонент скрыт из активной области, но его экземпляр сохранён" },
      { id: "c", text: "Компонент впервые вставлен в DOM" },
      { id: "d", text: "Произошла ошибка в render-функции" },
    ],
    correctAnswer: "b",
    explanation: "onDeactivated не равен onUnmounted. KeepAlive сохраняет экземпляр, но временно деактивирует его. Это важно для паузы timers, listeners или запросов, которые не должны работать в скрытом состоянии.",
    knowledgeId: "knowledge-lifecycle-q610",
  },
  {
    id: 611,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "MiddlePlus",
    tags: [
      "onErrorCaptured",
      "errors",
      "boundaries",
    ],
    question: "Для чего используется onErrorCaptured?",
    answers: [
      { id: "a", text: "Для автоматического retry любого HTTP-запроса" },
      { id: "b", text: "Для объявления required props" },
      { id: "c", text: "Для перехвата ошибок из дочерних компонентов и управления распространением ошибки" },
      { id: "d", text: "Для запуска KeepAlive-кеша" },
    ],
    correctAnswer: "c",
    explanation: "onErrorCaptured позволяет родительскому компоненту обработать ошибку из дочернего дерева. Hook может вернуть false, чтобы остановить дальнейшее распространение. Он не является универсальным retry-механизмом.",
    knowledgeId: "knowledge-lifecycle-q611",
  },
  {
    id: 612,
    moduleId: "lifecycle",
    type: "Interview",
    difficulty: "JuniorPlus",
    tags: [
      "vue-2",
      "created",
      "mounted",
      "migration",
    ],
    question: "Как объяснить разницу между created и mounted из Vue 2?",
    answers: [
      { id: "a", text: "created выполнялся только после удаления компонента" },
      { id: "b", text: "mounted был нужен только для CSS" },
      { id: "c", text: "created и mounted всегда были одним и тем же hook" },
      { id: "d", text: "created выполнялся до DOM-монтирования, mounted — после вставки компонента в DOM" },
    ],
    correctAnswer: "d",
    explanation: "В Vue 2 created происходил до монтирования DOM, поэтому template refs ещё не были доступны. mounted выполнялся после вставки в DOM. В Composition API похожая логика распределяется между setup и onMounted.",
    knowledgeId: "knowledge-lifecycle-q612",
  },
  {
    id: 613,
    moduleId: "lifecycle",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "cleanup",
      "subscriptions",
      "memory-leak",
    ],
    question: "Что не так с подпиской на внешний источник без очистки при unmount?",
    answers: [
      { id: "a", text: "Подписка может продолжить работать после удаления компонента и создать утечку" },
      { id: "b", text: "Vue автоматически превратит подписку в prop" },
      { id: "c", text: "Компонент перестанет принимать slots" },
      { id: "d", text: "Подписка всегда удалится браузером сразу после render" },
    ],
    correctAnswer: "a",
    explanation: "Внешние подписки не всегда знают о жизненном цикле Vue-компонента. Если их не остановить, callback может обращаться к устаревшему состоянию. Поэтому cleanup регистрируют в onUnmounted или watcher cleanup.",
    knowledgeId: "knowledge-lifecycle-q613",
  },
  {
    id: 614,
    moduleId: "lifecycle",
    type: "FindBug",
    difficulty: "JuniorPlus",
    tags: [
      "timers",
      "setInterval",
      "cleanup",
    ],
    question: "Что нужно сделать с setInterval, созданным в onMounted?",
    answers: [
      { id: "a", text: "Ничего, Vue всегда очищает setInterval автоматически" },
      { id: "b", text: "Сохранить id интервала и вызвать clearInterval в onUnmounted" },
      { id: "c", text: "Передать interval id в defineProps" },
      { id: "d", text: "Заменить interval на CSS-анимацию всегда" },
    ],
    correctAnswer: "b",
    explanation: "setInterval — внешний ресурс браузера, и Vue не очищает его автоматически. Нужно сохранить id и остановить интервал при размонтировании. Иначе callback продолжит выполняться.",
    knowledgeId: "knowledge-lifecycle-q614",
  },
  {
    id: 615,
    moduleId: "lifecycle",
    type: "CodeReview",
    difficulty: "JuniorPlus",
    tags: [
      "event-listeners",
      "cleanup",
      "window",
    ],
    question: "Как правильно работать с window.addEventListener внутри компонента?",
    answers: [
      { id: "a", text: "Добавлять listener при каждом render без удаления" },
      { id: "b", text: "Удалять listener другим anonymous callback" },
      { id: "c", text: "Добавить listener при mount и удалить тот же handler при unmount" },
      { id: "d", text: "Хранить listener в template slot" },
    ],
    correctAnswer: "c",
    explanation: "removeEventListener должен получить ту же функцию, что была передана в addEventListener. Anonymous callback нельзя корректно удалить, если ссылка потеряна. Добавление при каждом render создаст накопление handlers.",
    knowledgeId: "knowledge-lifecycle-q615",
  },
  {
    id: 616,
    moduleId: "lifecycle",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "dom",
      "onMounted",
      "measurements",
    ],
    question: "Когда лучше измерять размеры DOM-элемента через getBoundingClientRect?",
    answers: [
      { id: "a", text: "В начале setup до render" },
      { id: "b", text: "Только внутри defineProps" },
      { id: "c", text: "После onUnmounted" },
      { id: "d", text: "После монтирования, когда элемент уже существует в DOM" },
    ],
    correctAnswer: "d",
    explanation: "Размер DOM-элемента можно измерить, когда элемент уже отрендерен и вставлен в DOM. Поэтому используют onMounted, а иногда ещё nextTick после изменения state. В setup DOM ещё нет.",
    knowledgeId: "knowledge-lifecycle-q616",
  },
  {
    id: 617,
    moduleId: "lifecycle",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "template-refs",
      "onMounted",
      "null",
    ],
    question: "Какое значение обычно имеет template ref на DOM-элемент до onMounted?",
    answers: [
      { id: "a", text: "null или начальное значение ref" },
      { id: "b", text: "Готовый DOM-элемент всегда" },
      { id: "c", text: "Строка с HTML компонента" },
      { id: "d", text: "Promise с компонентом" },
    ],
    correctAnswer: "a",
    explanation: "До монтирования DOM-элемент ещё не назначен в template ref. Поэтому ref обычно инициализируют null и проверяют значение перед использованием. Готовый DOM доступен после mount.",
    knowledgeId: "knowledge-lifecycle-q617",
  },
  {
    id: 618,
    moduleId: "lifecycle",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "nextTick",
      "dom-update",
      "reactivity",
    ],
    question: "Когда нужен nextTick?",
    answers: [
      { id: "a", text: "Чтобы объявить props после render" },
      { id: "b", text: "Когда нужно дождаться DOM-обновления после изменения reactive state" },
      { id: "c", text: "Чтобы полностью заменить watch" },
      { id: "d", text: "Чтобы создать новый component instance вручную" },
    ],
    correctAnswer: "b",
    explanation: "Vue обновляет DOM асинхронно и батчит изменения. nextTick позволяет дождаться, когда DOM отразит новое состояние. Он не объявляет props и не заменяет watch.",
    knowledgeId: "knowledge-lifecycle-q618",
  },
  {
    id: 619,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "keep-alive",
      "lifecycle",
      "activated",
    ],
    question: "Какая пара hooks важна для KeepAlive-компонентов?",
    answers: [
      { id: "a", text: "defineProps и defineEmits" },
      { id: "b", text: "watch и computed только" },
      { id: "c", text: "onActivated и onDeactivated" },
      { id: "d", text: "useSlots и useAttrs" },
    ],
    correctAnswer: "c",
    explanation: "KeepAlive не уничтожает компонент при скрытии, а деактивирует его. Поэтому onActivated и onDeactivated помогают возобновлять или ставить на паузу ресурсы. onMounted/onUnmounted работают иначе в кешированном сценарии.",
    knowledgeId: "knowledge-lifecycle-q619",
  },
  {
    id: 620,
    moduleId: "lifecycle",
    type: "Theory",
    difficulty: "MiddlePlus",
    tags: [
      "async-setup",
      "suspense",
      "loading",
    ],
    question: "Что важно помнить про async setup?",
    answers: [
      { id: "a", text: "Он автоматически выполняется только на unmount" },
      { id: "b", text: "Он запрещает lifecycle hooks" },
      { id: "c", text: "Он делает все props mutable" },
      { id: "d", text: "Он делает setup асинхронным и обычно требует Suspense или продуманного состояния загрузки" },
    ],
    correctAnswer: "d",
    explanation: "async setup возвращает Promise и влияет на момент готовности компонента. В UI нужно учитывать загрузку и ошибки, часто через Suspense или локальный loading state. Он не делает props mutable и не запрещает hooks.",
    knowledgeId: "knowledge-lifecycle-q620",
  },
  {
    id: 621,
    moduleId: "lifecycle",
    type: "Interview",
    difficulty: "MiddlePlus",
    tags: [
      "ssr",
      "lifecycle",
      "server-rendering",
    ],
    question: "Какое утверждение про lifecycle hooks и SSR корректно?",
    answers: [
      { id: "a", text: "DOM-зависимые hooks вроде onMounted не выполняются на сервере" },
      { id: "b", text: "onMounted всегда выполняется до server render" },
      { id: "c", text: "SSR разрешает прямой доступ к window в setup без проверок" },
      { id: "d", text: "onUnmounted нужен для генерации HTML на сервере" },
    ],
    correctAnswer: "a",
    explanation: "На сервере нет браузерного DOM, поэтому DOM-зависимые hooks вроде onMounted не выполняются. Код с window или document должен быть защищён проверками среды. Для server-side загрузки данных используются отдельные подходы.",
    knowledgeId: "knowledge-lifecycle-q621",
  },
  {
    id: 622,
    moduleId: "lifecycle",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "lifecycle-mistakes",
      "state-loop",
      "onUpdated",
    ],
    question: "Какая ошибка часто возникает при изменении state внутри onUpdated?",
    answers: [
      { id: "a", text: "Vue автоматически удалит все props" },
      { id: "b", text: "Можно вызвать новое обновление и получить цикл обновлений" },
      { id: "c", text: "Компонент перестанет поддерживать slots" },
      { id: "d", text: "onMounted больше никогда не выполнится" },
    ],
    correctAnswer: "b",
    explanation: "onUpdated вызывается после DOM update. Если в нём без условий менять reactive state, Vue снова обновит DOM и снова вызовет hook. Для derived state лучше computed, а для side effects — watch с условиями.",
    knowledgeId: "knowledge-lifecycle-q622",
  },
  {
    id: 623,
    moduleId: "lifecycle",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "composables",
      "lifecycle",
      "cleanup",
    ],
    question: "Как composable должен работать с lifecycle cleanup?",
    answers: [
      { id: "a", text: "Composable не может использовать lifecycle hooks" },
      { id: "b", text: "Cleanup всегда должен выполняться только в родительском компоненте вручную" },
      { id: "c", text: "Если composable создаёт внешний ресурс, он должен зарегистрировать очистку" },
      { id: "d", text: "Composable обязан хранить cleanup в localStorage" },
    ],
    correctAnswer: "c",
    explanation: "Composable может использовать lifecycle hooks, если вызывается в setup-контексте. Если он добавляет listener, timer или subscription, он должен организовать cleanup. Это делает composable безопасным и переиспользуемым.",
    knowledgeId: "knowledge-lifecycle-q623",
  },
  {
    id: 624,
    moduleId: "lifecycle",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "watch-cleanup",
      "async",
      "race-condition",
    ],
    question: "Зачем в watcher может понадобиться cleanup callback?",
    answers: [
      { id: "a", text: "Чтобы удалить сам prop из компонента" },
      { id: "b", text: "Чтобы заменить onMounted" },
      { id: "c", text: "Чтобы сделать computed writable" },
      { id: "d", text: "Чтобы отменить или пометить устаревший async effect перед следующим запуском watcher" },
    ],
    correctAnswer: "d",
    explanation: "Watcher может запускаться снова до завершения предыдущей async-операции. Cleanup помогает отменить запрос, убрать listener или пометить результат устаревшим. Это снижает риск race conditions.",
    knowledgeId: "knowledge-lifecycle-q624",
  },
  {
    id: 625,
    moduleId: "lifecycle",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "fetching",
      "onMounted",
      "architecture",
    ],
    question: "Что стоит обсудить на review, если вся загрузка данных без условий находится в onMounted?",
    answers: [
      { id: "a", text: "Подходит ли lifecycle hook для этой задачи, учтены ли loading, error, SSR и повторные запросы" },
      { id: "b", text: "Нужно ли заменить onMounted на CSS-класс" },
      { id: "c", text: "Можно ли удалить все reactive значения" },
      { id: "d", text: "Почему запрос не находится в defineProps" },
    ],
    correctAnswer: "a",
    explanation: "onMounted часто используют для client-only эффектов, но загрузка данных требует продуманного состояния, ошибок, отмены и SSR-сценариев. На review важно смотреть на архитектуру, а не только на факт использования hook.",
    knowledgeId: "knowledge-lifecycle-q625",
  },
  {
    id: 626,
    moduleId: "lifecycle",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "resources",
      "ownership",
      "cleanup",
    ],
    question: "Какое правило помогает избежать утечек ресурсов в lifecycle?",
    answers: [
      { id: "a", text: "Все ресурсы нужно хранить в props" },
      { id: "b", text: "Код, который создаёт ресурс, должен быть ответственен за его очистку" },
      { id: "c", text: "Cleanup нужен только для CSS-анимаций" },
      { id: "d", text: "Listeners можно добавлять только в template" },
    ],
    correctAnswer: "b",
    explanation: "Принцип ownership прост: создал listener, timer, observer или subscription — организуй cleanup рядом. Это снижает риск утечек и делает код понятнее. Props и template не заменяют управление ресурсами.",
    knowledgeId: "knowledge-lifecycle-q626",
  },
  {
    id: 627,
    moduleId: "lifecycle",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "third-party-libraries",
      "dom",
      "cleanup",
    ],
    question: "Как безопасно интегрировать DOM-библиотеку, которой нужен реальный элемент?",
    answers: [
      { id: "a", text: "Инициализировать в setup до создания DOM" },
      { id: "b", text: "Передать DOM instance через prop от родителя всегда" },
      { id: "c", text: "Инициализировать в onMounted через template ref и уничтожить instance в onUnmounted" },
      { id: "d", text: "Создать библиотеку внутри computed" },
    ],
    correctAnswer: "c",
    explanation: "DOM-библиотеке нужен существующий элемент, поэтому инициализация обычно происходит в onMounted. Если библиотека создаёт listeners или observers, её instance нужно уничтожить при unmount. Computed не подходит для side effects.",
    knowledgeId: "knowledge-lifecycle-q627",
  },
  {
    id: 628,
    moduleId: "lifecycle",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "side-effects",
      "computed",
      "watch",
    ],
    question: "Где лучше размещать side effects, связанные с изменением reactive значения?",
    answers: [
      { id: "a", text: "Всегда внутри computed getter" },
      { id: "b", text: "Только в template interpolation" },
      { id: "c", text: "В типах TypeScript" },
      { id: "d", text: "В watch или lifecycle hook, а не в computed getter" },
    ],
    correctAnswer: "d",
    explanation: "Computed должен оставаться чистым derived state. Side effects вроде записи в storage, запроса или DOM-интеграции лучше размещать в watch или lifecycle hook. Это делает поведение предсказуемым.",
    knowledgeId: "knowledge-lifecycle-q628",
  },
  {
    id: 629,
    moduleId: "lifecycle",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "hook-order",
      "mental-model",
      "lifecycle",
    ],
    question: "Какой порядок лучше описывает первый client-side render компонента?",
    answers: [
      { id: "a", text: "setup, before mount, mount, затем mounted hook" },
      { id: "b", text: "onUnmounted, onUpdated, setup, onMounted" },
      { id: "c", text: "onUpdated, onBeforeMount, setup, onUnmounted" },
      { id: "d", text: "onErrorCaptured, onDeactivated, setup, CSS" },
    ],
    correctAnswer: "a",
    explanation: "На первом рендере сначала выполняется setup, затем компонент готовится к монтированию, вставляется в DOM и после этого вызывается mounted hook. Update и unmount hooks относятся к другим этапам.",
    knowledgeId: "knowledge-lifecycle-q629",
  },
  {
    id: 630,
    moduleId: "lifecycle",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "lifecycle",
      "architecture",
      "large-component",
    ],
    question: "Что стоит предложить, если компонент содержит много несвязанных lifecycle effects?",
    answers: [
      { id: "a", text: "Перенести все effects в template" },
      { id: "b", text: "Разделить эффекты по ответственности и вынести повторяемые сценарии в composables" },
      { id: "c", text: "Объединить все hooks в один большой onMounted без cleanup" },
      { id: "d", text: "Удалить TypeScript-типы компонента" },
    ],
    correctAnswer: "b",
    explanation: "Несвязанные lifecycle effects ухудшают читаемость. Их стоит сгруппировать по смыслу, а повторяемые подписки, listeners или timers вынести в composables с cleanup. Template и удаление типов проблему не решают.",
    knowledgeId: "knowledge-lifecycle-q630",
  },
]
