import type { ContentQuestion } from '../../../types/content'

export const propsEmitsQuestions: ContentQuestion[] = [
  {
    id: 401,
    moduleId: "props-emits",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "props",
      "component-api",
      "data-flow",
    ],
    question: "Что такое props во Vue?",
    answers: [
      { id: "a", text: "Входные данные компонента, передаваемые от родителя к дочернему компоненту" },
      { id: "b", text: "События, которые дочерний компонент отправляет родителю" },
      { id: "c", text: "Глобальное состояние, автоматически доступное всем компонентам" },
      { id: "d", text: "CSS-переменные внутри scoped style" },
    ],
    correctAnswer: "a",
    explanation: "Props задают входной контракт компонента и передаются сверху вниз. События описываются через emits, глобальное состояние хранится отдельно, а CSS-переменные не являются props. На интервью важно связывать props с однонаправленным потоком данных.",
    knowledgeId: "knowledge-props-emits-q401",
  },
  {
    id: 402,
    moduleId: "props-emits",
    type: "Interview",
    difficulty: "Junior",
    tags: [
      "one-way-data-flow",
      "props",
      "events",
    ],
    question: "Что означает однонаправленный поток данных в связке props и emits?",
    answers: [
      { id: "a", text: "Данные могут свободно мутироваться любым дочерним компонентом" },
      { id: "b", text: "Данные идут вниз через props, а изменения сообщаются вверх через события" },
      { id: "c", text: "Все компоненты должны читать данные только из localStorage" },
      { id: "d", text: "События должны заменять все props" },
    ],
    correctAnswer: "b",
    explanation: "Однонаправленный поток делает источник состояния понятным: родитель передаёт данные вниз, ребёнок отправляет сигнал вверх. Прямая мутация из дочернего компонента ломает предсказуемость. localStorage и полный отказ от props не описывают этот паттерн.",
    knowledgeId: "knowledge-props-emits-q402",
  },
  {
    id: 403,
    moduleId: "props-emits",
    type: "FindBug",
    difficulty: "JuniorPlus",
    tags: [
      "props",
      "mutation",
      "anti-pattern",
    ],
    question: "Почему нельзя напрямую мутировать prop внутри дочернего компонента?",
    answers: [
      { id: "a", text: "Props доступны только внутри CSS" },
      { id: "b", text: "Vue разрешает props только для строк" },
      { id: "c", text: "Prop принадлежит родителю, поэтому прямое изменение нарушает источник истины" },
      { id: "d", text: "После мутации prop автоматически становится emit" },
    ],
    correctAnswer: "c",
    explanation: "Prop является входным значением, которым управляет родитель. Дочерний компонент должен отправить событие или создать локальную копию для редактирования. Остальные варианты технически неверны и не объясняют проблему источника истины.",
    knowledgeId: "knowledge-props-emits-q403",
  },
  {
    id: 404,
    moduleId: "props-emits",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "defineProps",
      "script-setup",
      "props",
    ],
    question: "Для чего используется defineProps в `<script setup>`?",
    answers: [
      { id: "a", text: "Для объявления событий компонента" },
      { id: "b", text: "Для создания Pinia store" },
      { id: "c", text: "Для регистрации маршрута" },
      { id: "d", text: "Для объявления props компонента" },
    ],
    correctAnswer: "d",
    explanation: "defineProps — compiler macro для объявления входных props в script setup. События объявляет defineEmits, store создаётся через Pinia, а маршруты через Vue Router. Макрос не нужно импортировать.",
    knowledgeId: "knowledge-props-emits-q404",
  },
  {
    id: 405,
    moduleId: "props-emits",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "props-typing",
      "typescript",
      "defineProps",
    ],
    question: "Как лучше типизировать props в Vue-компоненте на TypeScript?",
    answers: [
      { id: "a", text: "Описать интерфейс props и передать его в defineProps<Props>()" },
      { id: "b", text: "Оставить props без типов, чтобы не мешать runtime" },
      { id: "c", text: "Хранить типы props в названии CSS-класса" },
      { id: "d", text: "Передавать все props как JSON-строку" },
    ],
    correctAnswer: "a",
    explanation: "Интерфейс props делает контракт компонента явным и проверяемым TypeScript. Отсутствие типов ухудшает поддержку и автодополнение. CSS-классы и JSON-строки не решают задачу типизации component API.",
    knowledgeId: "knowledge-props-emits-q405",
  },
  {
    id: 406,
    moduleId: "props-emits",
    type: "CodeReview",
    difficulty: "JuniorPlus",
    tags: [
      "default-values",
      "withDefaults",
      "props",
    ],
    question: "Как корректно задать значение по умолчанию для typed props в script setup?",
    answers: [
      { id: "a", text: "Мутировать prop в onMounted, если он не передан" },
      { id: "b", text: "Использовать withDefaults вместе с defineProps<Props>()" },
      { id: "c", text: "Задать default через emit" },
      { id: "d", text: "Создать CSS-переменную с таким же именем" },
    ],
    correctAnswer: "b",
    explanation: "withDefaults позволяет задать defaults для типизированных props. Мутация prop в onMounted нарушает data flow, emit не задаёт входные значения, а CSS-переменные не влияют на props. Для объектов и массивов важно помнить о фабриках значений.",
    knowledgeId: "knowledge-props-emits-q406",
  },
  {
    id: 407,
    moduleId: "props-emits",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "required-props",
      "props",
      "contract",
    ],
    question: "Что означает required prop?",
    answers: [
      { id: "a", text: "Компонент может сам удалить prop при рендере" },
      { id: "b", text: "Prop доступен только внутри style" },
      { id: "c", text: "Компонент ожидает, что родитель обязательно передаст это значение" },
      { id: "d", text: "Prop всегда становится boolean" },
    ],
    correctAnswer: "c",
    explanation: "Required prop — обязательная часть API компонента. В TypeScript это обычно выражается отсутствием `?` в интерфейсе. Он не удаляется автоматически, не связан со style и не меняет тип на boolean.",
    knowledgeId: "knowledge-props-emits-q407",
  },
  {
    id: 408,
    moduleId: "props-emits",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "boolean-props",
      "props",
      "template",
    ],
    question: "Как обычно ведёт себя boolean prop в template?",
    answers: [
      { id: "a", text: "Он всегда превращается в строку \"false\"" },
      { id: "b", text: "Он может использоваться только с v-for" },
      { id: "c", text: "Он автоматически отправляет событие update" },
      { id: "d", text: "Переданный без значения атрибут обычно означает true" },
    ],
    correctAnswer: "d",
    explanation: "Boolean prop в template похож на HTML boolean attributes: наличие атрибута часто означает true. Для динамического значения используют `:disabled=\"condition\"`. Он не связан с v-for и не отправляет события автоматически.",
    knowledgeId: "knowledge-props-emits-q408",
  },
  {
    id: 409,
    moduleId: "props-emits",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "object-props",
      "array-props",
      "default-values",
    ],
    question: "Что важно помнить о default value для object или array props?",
    answers: [
      { id: "a", text: "В runtime-объявлении default должен быть фабрикой, чтобы не делить ссылку между экземплярами" },
      { id: "b", text: "Object и array props нельзя передавать во Vue" },
      { id: "c", text: "Default всегда должен быть строкой" },
      { id: "d", text: "Default заменяет emits" },
    ],
    correctAnswer: "a",
    explanation: "Для объектных и массивных defaults в runtime props используют функцию, возвращающую новое значение. Иначе несколько экземпляров могут разделить одну ссылку. Vue поддерживает object и array props, а default не имеет отношения к emits.",
    knowledgeId: "knowledge-props-emits-q409",
  },
  {
    id: 410,
    moduleId: "props-emits",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "validator",
      "props",
      "runtime-validation",
    ],
    question: "Для чего нужен validator у prop?",
    answers: [
      { id: "a", text: "Для типизации emit payload" },
      { id: "b", text: "Для runtime-проверки допустимости значения prop" },
      { id: "c", text: "Для автоматической загрузки async component" },
      { id: "d", text: "Для изменения scoped CSS" },
    ],
    correctAnswer: "b",
    explanation: "Validator проверяет значение prop во время выполнения и помогает поймать неправильные значения. TypeScript проверяет код на этапе разработки, но не заменяет runtime-валидацию внешних значений. Emits, async components и CSS решаются другими API.",
    knowledgeId: "knowledge-props-emits-q410",
  },
  {
    id: 411,
    moduleId: "props-emits",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "props-destructuring",
      "reactivity",
      "toRefs",
    ],
    question: "В чём риск обычной деструктуризации props?",
    answers: [
      { id: "a", text: "Props станут глобальными переменными" },
      { id: "b", text: "Компонент перестанет принимать events" },
      { id: "c", text: "Можно потерять реактивную связь с обновлениями prop" },
      { id: "d", text: "Vue отключит template" },
    ],
    correctAnswer: "c",
    explanation: "Обычная деструктуризация может превратить prop в локальное значение и потерять обновления. Безопаснее читать `props.value`, использовать toRef/toRefs или учитывать поведение актуальной версии Vue. Остальные варианты не описывают реальный риск.",
    knowledgeId: "knowledge-props-emits-q411",
  },
  {
    id: 412,
    moduleId: "props-emits",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "toRefs",
      "props",
      "reactivity",
    ],
    question: "Что даёт `toRefs(props)` при работе с props?",
    answers: [
      { id: "a", text: "Создаёт копию props без реактивности" },
      { id: "b", text: "Автоматически отправляет update-события" },
      { id: "c", text: "Удаляет optional props" },
      { id: "d", text: "Создаёт refs для свойств props с сохранением реактивной связи" },
    ],
    correctAnswer: "d",
    explanation: "toRefs создаёт refs, связанные со свойствами реактивного объекта. Это полезно при передаче prop в composable или при деструктуризации. Он не отправляет события и не удаляет optional props.",
    knowledgeId: "knowledge-props-emits-q412",
  },
  {
    id: 413,
    moduleId: "props-emits",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "computed",
      "props",
      "derived-state",
    ],
    question: "Когда computed на основе props является хорошим решением?",
    answers: [
      { id: "a", text: "Когда нужно получить производное значение без мутации входного prop" },
      { id: "b", text: "Когда нужно изменить prop внутри дочернего компонента" },
      { id: "c", text: "Когда нужно заменить emit на computed" },
      { id: "d", text: "Когда нужно создать глобальный singleton" },
    ],
    correctAnswer: "a",
    explanation: "Computed хорошо подходит для derived state: форматирования, фильтрации и вычисления статусов на основе props. Он не должен мутировать prop и не заменяет события. Глобальный singleton не связан с computed.",
    knowledgeId: "knowledge-props-emits-q413",
  },
  {
    id: 414,
    moduleId: "props-emits",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "emits",
      "component-events",
      "data-flow",
    ],
    question: "Что такое emits во Vue?",
    answers: [
      { id: "a", text: "Входные данные компонента" },
      { id: "b", text: "Объявление событий, которые компонент может отправить наружу" },
      { id: "c", text: "Список глобальных CSS-классов" },
      { id: "d", text: "Механизм автоматического кеширования компонентов" },
    ],
    correctAnswer: "b",
    explanation: "Emits описывают события компонента и помогают общаться с родителем. Входные данные — это props, кеширование — KeepAlive, а CSS-классы не относятся к emits. Хороший компонент явно описывает события.",
    knowledgeId: "knowledge-props-emits-q414",
  },
  {
    id: 415,
    moduleId: "props-emits",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "defineEmits",
      "script-setup",
      "events",
    ],
    question: "Что возвращает defineEmits?",
    answers: [
      { id: "a", text: "Объект props" },
      { id: "b", text: "DOM-ссылку на компонент" },
      { id: "c", text: "Функцию emit для отправки объявленных событий" },
      { id: "d", text: "Массив slots" },
    ],
    correctAnswer: "c",
    explanation: "defineEmits объявляет события и возвращает функцию emit. Через emit компонент отправляет событие родителю. Props, DOM refs и slots получаются другими механизмами.",
    knowledgeId: "knowledge-props-emits-q415",
  },
  {
    id: 416,
    moduleId: "props-emits",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "emits-typing",
      "typescript",
      "payload",
    ],
    question: "Что даёт типизация defineEmits?",
    answers: [
      { id: "a", text: "Автоматическое создание props из событий" },
      { id: "b", text: "Запрет на использование v-model" },
      { id: "c", text: "Глубокое клонирование payload" },
      { id: "d", text: "Проверку имён событий и формы payload при вызове emit" },
    ],
    correctAnswer: "d",
    explanation: "Типизация emits защищает от ошибок в имени события и структуре payload. Она не создаёт props автоматически и не запрещает v-model. Клонирование данных остаётся отдельной задачей.",
    knowledgeId: "knowledge-props-emits-q416",
  },
  {
    id: 417,
    moduleId: "props-emits",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "payload",
      "events",
      "component-api",
    ],
    question: "Каким должен быть payload события компонента?",
    answers: [
      { id: "a", text: "Минимальным и понятным: id, новое значение или объект с явным контрактом" },
      { id: "b", text: "Всегда полным снимком всего состояния приложения" },
      { id: "c", text: "Всегда строкой, даже если событие передаёт объект" },
      { id: "d", text: "Случайной структурой для каждого вызова emit" },
    ],
    correctAnswer: "a",
    explanation: "Payload должен быть предсказуемым и достаточным для обработки события. Полный снимок состояния перегружает API, а разные структуры под одним событием создают ошибки. Типизация помогает удерживать контракт стабильным.",
    knowledgeId: "knowledge-props-emits-q417",
  },
  {
    id: 418,
    moduleId: "props-emits",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "v-model",
      "components",
      "two-way-binding",
    ],
    question: "Как работает v-model на компоненте в классическом варианте Vue 3?",
    answers: [
      { id: "a", text: "Через прямую мутацию modelValue внутри дочернего компонента" },
      { id: "b", text: "Через prop modelValue и событие update:modelValue" },
      { id: "c", text: "Через обязательный global event bus" },
      { id: "d", text: "Через автоматическую запись в localStorage" },
    ],
    correctAnswer: "b",
    explanation: "v-model на компоненте — это соглашение: значение приходит через modelValue, изменения отправляются через update:modelValue. Дочерний компонент не мутирует prop напрямую. Event bus и localStorage не являются частью базового v-model.",
    knowledgeId: "knowledge-props-emits-q418",
  },
  {
    id: 419,
    moduleId: "props-emits",
    type: "CodeOutput",
    difficulty: "JuniorPlus",
    tags: [
      "modelValue",
      "v-model",
      "props",
    ],
    question: "Что обычно означает prop `modelValue` в компоненте?",
    answers: [
      { id: "a", text: "Имя компонента в devtools" },
      { id: "b", text: "Список всех events компонента" },
      { id: "c", text: "Текущее значение, переданное через v-model" },
      { id: "d", text: "CSS-класс для root element" },
    ],
    correctAnswer: "c",
    explanation: "modelValue — стандартное имя prop для default v-model в Vue 3. Событие update:modelValue сообщает новое значение. Имя компонента, events и CSS-классы не связаны с этим prop.",
    knowledgeId: "knowledge-props-emits-q419",
  },
  {
    id: 420,
    moduleId: "props-emits",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "update:modelValue",
      "v-model",
      "emits",
    ],
    question: "Когда компонент должен emit `update:modelValue`?",
    answers: [
      { id: "a", text: "При каждом render независимо от изменений" },
      { id: "b", text: "Только внутри CSS transition" },
      { id: "c", text: "Когда компонент получает любой prop" },
      { id: "d", text: "Когда пользовательское действие должно изменить значение v-model у родителя" },
    ],
    correctAnswer: "d",
    explanation: "update:modelValue отправляют при намерении изменить controlled value: ввод текста, переключение, выбор опции. Отправка на каждый render может создать циклы и лишние обновления. Получение prop само по себе не требует emit.",
    knowledgeId: "knowledge-props-emits-q420",
  },
  {
    id: 421,
    moduleId: "props-emits",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "multiple-v-model",
      "v-model",
      "forms",
    ],
    question: "Что выбрать, если компоненту нужны два независимых v-model значения, например `firstName` и `lastName`?",
    answers: [
      { id: "a", text: "Использовать аргументы v-model: v-model:first-name и v-model:last-name" },
      { id: "b", text: "Передавать оба значения одной строкой через default slot" },
      { id: "c", text: "Мутировать два props напрямую" },
      { id: "d", text: "Создать два global event bus канала" },
    ],
    correctAnswer: "a",
    explanation: "Vue поддерживает несколько v-model через аргументы, например v-model:title или v-model:first-name. Каждый канал имеет свой prop и update-событие. Slots, мутация props и event bus не являются корректным решением этой задачи.",
    knowledgeId: "knowledge-props-emits-q421",
  },
  {
    id: 422,
    moduleId: "props-emits",
    type: "Theory",
    difficulty: "Middle",
    tags: [
      "defineModel",
      "v-model",
      "script-setup",
    ],
    question: "Что упрощает defineModel?",
    answers: [
      { id: "a", text: "Регистрацию Pinia store" },
      { id: "b", text: "Объявление prop и update-события для v-model" },
      { id: "c", text: "Создание scoped slot" },
      { id: "d", text: "Автоматическую валидацию всех props" },
    ],
    correctAnswer: "b",
    explanation: "defineModel сокращает boilerplate вокруг v-model в компоненте. Он не создаёт store, не объявляет slots и не заменяет все виды validation. На интервью важно понимать, что это удобный синтаксис поверх component model.",
    knowledgeId: "knowledge-props-emits-q422",
  },
  {
    id: 423,
    moduleId: "props-emits",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "controlled-components",
      "state",
      "component-api",
    ],
    question: "Что такое controlled component в контексте Vue?",
    answers: [
      { id: "a", text: "Компонент, который запрещает props и emits" },
      { id: "b", text: "Компонент, который хранит значение внутри и не синхронизирует его с родителем" },
      { id: "c", text: "Компонент, где важное значение хранится снаружи и меняется через props/events контракт" },
      { id: "d", text: "Компонент, который принимает defaultValue и дальше меняет состояние автономно" },
    ],
    correctAnswer: "c",
    explanation: "Controlled component получает значение через prop и сообщает изменения через event. Родитель остаётся источником истины. Это особенно важно для форм, фильтров и компонентов дизайн-системы.",
    knowledgeId: "knowledge-props-emits-q423",
  },
  {
    id: 424,
    moduleId: "props-emits",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "parent-child-events",
      "communication",
      "emits",
    ],
    question: "Как дочерний компонент должен сообщить родителю о клике по кнопке удаления?",
    answers: [
      { id: "a", text: "Удалить элемент напрямую из массива родителя через prop" },
      { id: "b", text: "Изменить URL без участия родителя" },
      { id: "c", text: "Записать id в CSS-переменную" },
      { id: "d", text: "Отправить событие, например `delete`, с id удаляемого элемента" },
    ],
    correctAnswer: "d",
    explanation: "Дочерний компонент отправляет событие с понятным payload, а родитель решает, как изменить список. Прямая мутация массива из prop нарушает data flow. URL и CSS-переменные не являются правильным каналом компонентной коммуникации.",
    knowledgeId: "knowledge-props-emits-q424",
  },
  {
    id: 425,
    moduleId: "props-emits",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "event-bus",
      "anti-pattern",
      "architecture",
    ],
    question: "Почему глобальный event bus часто считают анти-паттерном?",
    answers: [
      { id: "a", text: "Он создаёт неявные связи и усложняет поиск источника изменений" },
      { id: "b", text: "Он полностью запрещён JavaScript" },
      { id: "c", text: "Он автоматически удаляет props" },
      { id: "d", text: "Он работает только внутри scoped CSS" },
    ],
    correctAnswer: "a",
    explanation: "Event bus может скрывать связи между компонентами: отправитель и получатель не видны рядом в коде. Это усложняет debugging и поддержку. В современных Vue-приложениях часто выбирают props/events, provide/inject или store в зависимости от масштаба связи.",
    knowledgeId: "knowledge-props-emits-q425",
  },
  {
    id: 426,
    moduleId: "props-emits",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "pinia",
      "emits-chain",
      "state-management",
    ],
    question: "Когда Pinia может быть лучше длинной цепочки emits?",
    answers: [
      { id: "a", text: "Когда нужно передать один клик от дочерней кнопки к ближайшему родителю" },
      { id: "b", text: "Когда состояние нужно многим удалённым частям интерфейса и цепочка событий стала хрупкой" },
      { id: "c", text: "Когда prop имеет тип string" },
      { id: "d", text: "Когда компонент содержит один slot" },
    ],
    correctAnswer: "b",
    explanation: "Если состояние разделяется многими независимыми участками UI, store может быть чище цепочки props и emits через несколько уровней. Для локальной связи ближайших компонентов emits остаются простым решением. Тип prop и наличие slot сами по себе не требуют Pinia.",
    knowledgeId: "knowledge-props-emits-q426",
  },
  {
    id: 427,
    moduleId: "props-emits",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "state-sync",
      "watch",
      "v-model",
    ],
    question: "Какая ошибка часто возникает при синхронизации локального state с prop?",
    answers: [
      { id: "a", text: "Vue автоматически удаляет локальный state" },
      { id: "b", text: "Prop перестаёт быть доступен в template навсегда" },
      { id: "c", text: "Создаются две версии истины, которые могут разъехаться" },
      { id: "d", text: "emit начинает работать как computed" },
    ],
    correctAnswer: "c",
    explanation: "Локальная копия prop может устареть, если не продумать синхронизацию. Особенно опасны watchers, которые обновляют друг друга и создают циклы. Нужно ясно определить источник истины: controlled value, локальный draft или store.",
    knowledgeId: "knowledge-props-emits-q427",
  },
  {
    id: 428,
    moduleId: "props-emits",
    type: "CodeOutput",
    difficulty: "MiddlePlus",
    tags: [
      "emit-loops",
      "watch",
      "state-sync",
    ],
    question: "Что может случиться, если watch на prop без условий каждый раз emitит update того же значения?",
    answers: [
      { id: "a", text: "Vue автоматически превратит watch в computed" },
      { id: "b", text: "Событие станет prop по умолчанию" },
      { id: "c", text: "Компонент перестанет поддерживать TypeScript" },
      { id: "d", text: "Могут появиться лишние обновления или цикл синхронизации" },
    ],
    correctAnswer: "d",
    explanation: "Если watcher отправляет update без проверки изменений, родитель может обновить prop и снова запустить watcher. Это создаёт лишние рендеры или цикл. Нужно сравнивать значения и проектировать sync-поток аккуратно.",
    knowledgeId: "knowledge-props-emits-q428",
  },
  {
    id: 429,
    moduleId: "props-emits",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "naming",
      "events",
      "component-api",
    ],
    question: "Как лучше именовать события компонента?",
    answers: [
      { id: "a", text: "По смыслу действия или изменения: select, close, submit, update:value" },
      { id: "b", text: "Случайными короткими буквами, чтобы API был компактнее" },
      { id: "c", text: "Именами внутренних переменных родителя" },
      { id: "d", text: "Только именем компонента без действия" },
    ],
    correctAnswer: "a",
    explanation: "Имя события должно объяснять, что произошло или какое изменение запрошено. Это делает код родителя читаемым. Случайные имена и привязка к внутренностям родителя ухудшают component API.",
    knowledgeId: "knowledge-props-emits-q429",
  },
  {
    id: 430,
    moduleId: "props-emits",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "component-contract",
      "props-emits",
      "architecture",
    ],
    question: "Что стоит предложить на review, если компонент имеет 20 props и 12 events для разных частных случаев?",
    answers: [
      { id: "a", text: "Добавить ещё props для каждого будущего случая" },
      { id: "b", text: "Пересмотреть границы компонента, выделить подкомпоненты и упростить публичный API" },
      { id: "c", text: "Спрятать все props в одну строку JSON" },
      { id: "d", text: "Заменить все events глобальным event bus" },
    ],
    correctAnswer: "b",
    explanation: "Большой набор props и events может означать, что компонент отвечает за слишком многое. На review стоит проверить декомпозицию, slots, controlled API и разделение smart/dumb частей. JSON-строка и event bus скрывают проблему, а не решают её.",
    knowledgeId: "knowledge-props-emits-q430",
  },
]
