import type { ContentQuestion } from '../../../types/content'

export const performanceQuestions: ContentQuestion[] = [
  {
    id: 1201,
    moduleId: "performance",
    type: "Theory",
    difficulty: "Junior",
    tags: [
      "vue",
      "performance",
      "virtual-dom",
    ],
    question: "Почему Vue 3 обычно быстро обновляет интерфейс?",
    answers: [
      { id: "a", text: "Vue сочетает реактивность, Virtual DOM, compiler hints, batching и точечное обновление зависимых частей." },
      { id: "b", text: "Vue полностью перерисовывает весь document.body при каждом ref.value++." },
      { id: "c", text: "Vue не использует JavaScript во время обновлений." },
      { id: "d", text: "Vue ускоряется только за счёт CSS-анимаций." },
    ],
    correctAnswer: "a",
    explanation: "Vue быстрый не из-за одного механизма, а из-за связки реактивности, компилятора и планировщика обновлений. Полная перерисовка всего документа была бы дорогой, а CSS не решает логику обновления DOM.",
    knowledgeId: "performance-1201",
  },
  {
    id: 1202,
    moduleId: "performance",
    type: "Interview",
    difficulty: "Junior",
    tags: [
      "virtual-dom",
      "interview",
    ],
    question: "Как лучше объяснить Virtual DOM на интервью?",
    answers: [
      { id: "a", text: "Это полная копия браузера внутри JavaScript." },
      { id: "b", text: "Это легковесное представление UI, которое Vue сравнивает и применяет минимально нужные DOM-изменения." },
      { id: "c", text: "Это способ отключить реактивность." },
      { id: "d", text: "Это инструмент только для серверного рендера." },
    ],
    correctAnswer: "b",
    explanation: "Virtual DOM описывает желаемое состояние UI в JavaScript-структурах. Vue сравнивает старое и новое дерево, но в Vue 3 этот процесс дополнительно ускоряется compiler hints, patch flags и block tree.",
    knowledgeId: "performance-1202",
  },
  {
    id: 1203,
    moduleId: "performance",
    type: "Scenario",
    difficulty: "Junior",
    tags: [
      "v-if",
      "v-show",
      "rendering",
    ],
    question: "Модальное окно открывается и закрывается много раз в минуту. Что часто эффективнее?",
    answers: [
      { id: "a", text: "v-if всегда быстрее при любом переключении." },
      { id: "b", text: "Удалить условный рендеринг и менять innerHTML вручную." },
      { id: "c", text: "v-show, если компонент дорогой и нужно часто переключать видимость." },
      { id: "d", text: "Заменить модальное окно на watchEffect." },
    ],
    correctAnswer: "c",
    explanation: "v-show оставляет элемент в DOM и переключает display, поэтому частые переключения могут быть дешевле. v-if уничтожает и создаёт subtree, что полезно для редкого показа или тяжёлого initial render.",
    knowledgeId: "performance-1203",
  },
  {
    id: 1204,
    moduleId: "performance",
    type: "CodeReview",
    difficulty: "Junior",
    tags: [
      "key",
      "v-for",
      "code-review",
    ],
    question: "На review найден v-for с :key=\"index\" для списка редактируемых задач. Что важно отметить?",
    answers: [
      { id: "a", text: "index всегда лучший key, потому что он короткий." },
      { id: "b", text: "key нужен только для CSS." },
      { id: "c", text: "v-for не поддерживает key во Vue 3." },
      { id: "d", text: "Для изменяемого списка нужен стабильный key из данных, иначе Vue может переиспользовать DOM некорректно." },
    ],
    correctAnswer: "d",
    explanation: "Стабильный key помогает Vue правильно сопоставлять элементы между обновлениями. Index ломается при вставке, удалении и сортировке, особенно если внутри есть состояние или input.",
    knowledgeId: "performance-1204",
  },
  {
    id: 1205,
    moduleId: "performance",
    type: "BestPractice",
    difficulty: "JuniorPlus",
    tags: [
      "computed",
      "caching",
    ],
    question: "Когда computed лучше метода с точки зрения производительности?",
    answers: [
      { id: "a", text: "Когда значение зависит от реактивных данных и должно кешироваться до изменения зависимостей." },
      { id: "b", text: "Когда нужно выполнить побочный эффект." },
      { id: "c", text: "Когда значение вообще не зависит от состояния." },
      { id: "d", text: "Когда нужно каждый render принудительно пересчитывать результат." },
    ],
    correctAnswer: "a",
    explanation: "computed кеширует результат по реактивным зависимостям. Метод вызывается при каждом render, если используется в template, поэтому для дорогих производных значений computed обычно эффективнее.",
    knowledgeId: "performance-1205",
  },
  {
    id: 1206,
    moduleId: "performance",
    type: "Interview",
    difficulty: "JuniorPlus",
    tags: [
      "scheduler",
      "batching",
      "nextTick",
    ],
    question: "Что делает batching updates во Vue?",
    answers: [
      { id: "a", text: "Запрещает менять несколько refs подряд." },
      { id: "b", text: "Группирует несколько реактивных изменений в один цикл обновления DOM." },
      { id: "c", text: "Отправляет все изменения на сервер." },
      { id: "d", text: "Отключает computed caching." },
    ],
    correctAnswer: "b",
    explanation: "Vue не обязан обновлять DOM после каждой строки изменения состояния. Планировщик группирует изменения и применяет обновления асинхронно, поэтому nextTick нужен для ожидания DOM после flush.",
    knowledgeId: "performance-1206",
  },
  {
    id: 1207,
    moduleId: "performance",
    type: "Scenario",
    difficulty: "JuniorPlus",
    tags: [
      "nextTick",
      "dom",
      "scheduler",
    ],
    question: "После изменения ref нужно измерить новую высоту DOM-элемента. Что использовать?",
    answers: [
      { id: "a", text: "Сразу читать DOM до обновления Vue." },
      { id: "b", text: "JSON.stringify(ref)." },
      { id: "c", text: "await nextTick(), затем измерить DOM." },
      { id: "d", text: "markRaw для DOM-элемента." },
    ],
    correctAnswer: "c",
    explanation: "DOM обновляется после flush очереди Vue, а не обязательно в той же строке, где изменилось reactive state. nextTick позволяет дождаться применения изменений, а затем безопасно измерить элемент или сфокусировать DOM-узел. Это важно для сценариев с layout measurement, scroll и интеграцией с browser API.",
    knowledgeId: "performance-1207",
  },
  {
    id: 1208,
    moduleId: "performance",
    type: "CodeReview",
    difficulty: "JuniorPlus",
    tags: [
      "watchEffect",
      "dependencies",
    ],
    question: "watchEffect внутри себя читает много реактивных полей и запускает тяжёлый запрос. Что стоит проверить?",
    answers: [
      { id: "a", text: "Не нужно ли заменить все refs на Math.random." },
      { id: "b", text: "Не отключён ли CSS." },
      { id: "c", text: "Не стоит ли перенести запрос в template." },
      { id: "d", text: "Не создаёт ли watchEffect лишние зависимости и слишком частые перезапуски." },
    ],
    correctAnswer: "d",
    explanation: "watchEffect автоматически отслеживает всё, что прочитано внутри. Если эффект читает лишнее состояние, он будет перезапускаться чаще, чем нужно; иногда лучше явный watch.",
    knowledgeId: "performance-1208",
  },
  {
    id: 1209,
    moduleId: "performance",
    type: "Theory",
    difficulty: "JuniorPlus",
    tags: [
      "patch-flags",
      "compiler",
    ],
    question: "Что такое Patch Flags во Vue 3?",
    answers: [
      { id: "a", text: "Подсказки компилятора, которые помогают runtime обновлять только динамические части vnode." },
      { id: "b", text: "Флаги браузера для включения GPU." },
      { id: "c", text: "Параметры CSS transition." },
      { id: "d", text: "Настройки Pinia persisted state." },
    ],
    correctAnswer: "a",
    explanation: "Patch Flags создаются компилятором Vue и сообщают runtime, что именно динамично в template. Благодаря этому Vue не сравнивает всё дерево одинаково дорого, а фокусируется на изменяемых частях. Это одна из причин, почему Vue 3 быстрее классического generic Virtual DOM-подхода.",
    knowledgeId: "performance-1209",
  },
  {
    id: 1210,
    moduleId: "performance",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "block-tree",
      "compiler",
      "performance",
    ],
    question: "Зачем Vue 3 использует Block Tree?",
    answers: [
      { id: "a", text: "Чтобы хранить CSS в бинарном дереве." },
      { id: "b", text: "Чтобы группировать динамические узлы и быстрее проходить update path." },
      { id: "c", text: "Чтобы запретить slots." },
      { id: "d", text: "Чтобы заменить реактивность на polling." },
    ],
    correctAnswer: "b",
    explanation: "Block Tree помогает runtime сосредоточиться на динамических частях шаблона. Вместе с Patch Flags это снижает объём работы при обновлении компонента.",
    knowledgeId: "performance-1210",
  },
  {
    id: 1211,
    moduleId: "performance",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "shallowRef",
      "large-data",
    ],
    question: "В компонент приходит большой объект chart instance, который не должен быть глубоко реактивным. Что уместно?",
    answers: [
      { id: "a", text: "reactive для всего экземпляра, включая внутренние поля библиотеки." },
      { id: "b", text: "computed для каждого приватного поля chart instance." },
      { id: "c", text: "shallowRef или markRaw, чтобы избежать лишнего глубокого reactive tracking." },
      { id: "d", text: "v-for по всем методам объекта." },
    ],
    correctAnswer: "c",
    explanation: "Экземпляры сторонних библиотек часто не должны становиться глубоко реактивными. shallowRef отслеживает замену значения, а markRaw исключает объект из реактивности. Это снижает лишний tracking и защищает внутреннюю модель библиотеки от Vue Proxy, что особенно важно для chart, editor и map-инстансов.",
    knowledgeId: "performance-1211",
  },
  {
    id: 1212,
    moduleId: "performance",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "large-list",
      "virtualization",
      "review",
    ],
    question: "Страница рендерит 20 000 строк через обычный v-for. Что предложить первым?",
    answers: [
      { id: "a", text: "Увеличить z-index каждой строки." },
      { id: "b", text: "Заменить key на Math.random()." },
      { id: "c", text: "Обернуть весь список в Teleport." },
      { id: "d", text: "Виртуализацию списка или пагинацию, чтобы не держать тысячи DOM-узлов одновременно." },
    ],
    correctAnswer: "d",
    explanation: "Главная стоимость больших списков — количество DOM-узлов и обновлений. Виртуализация рендерит только видимую часть, а пагинация уменьшает объём данных на экране.",
    knowledgeId: "performance-1212",
  },
  {
    id: 1213,
    moduleId: "performance",
    type: "FindBug",
    difficulty: "Middle",
    tags: [
      "key",
      "random",
      "rerender",
    ],
    question: "Компонент получает :key=\"Math.random()\". Почему это плохо?",
    answers: [
      { id: "a", text: "Vue будет считать компонент новым при каждом render и терять переиспользование subtree." },
      { id: "b", text: "Math.random всегда возвращает одинаковое значение." },
      { id: "c", text: "key ускоряет компонент только если он случайный." },
      { id: "d", text: "Vue запрещает key для компонентов." },
    ],
    correctAnswer: "a",
    explanation: "Нестабильный key заставляет Vue уничтожать и пересоздавать vnode/component subtree. Это дорого и может сбрасывать локальное состояние, фокус, анимации и состояние дочерних компонентов. Для списков нужен стабильный id из данных, а не index или случайное значение.",
    knowledgeId: "performance-1213",
  },
  {
    id: 1214,
    moduleId: "performance",
    type: "BestPractice",
    difficulty: "Middle",
    tags: [
      "v-once",
      "static-content",
    ],
    question: "Когда v-once может быть полезен?",
    answers: [
      { id: "a", text: "Для данных, которые меняются каждую секунду." },
      { id: "b", text: "Для большого статического блока, который после первого render не должен обновляться." },
      { id: "c", text: "Для формы с v-model." },
      { id: "d", text: "Для watchEffect с побочными эффектами." },
    ],
    correctAnswer: "b",
    explanation: "v-once говорит Vue отрендерить блок один раз и пропустить будущие updates. Это полезно для действительно статичного содержимого, но вредно для изменяемого UI.",
    knowledgeId: "performance-1214",
  },
  {
    id: 1215,
    moduleId: "performance",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "v-memo",
      "rendering",
    ],
    question: "Что делает v-memo?",
    answers: [
      { id: "a", text: "Создаёт глобальный кеш HTTP-запросов." },
      { id: "b", text: "Отключает все watchers в приложении." },
      { id: "c", text: "Пропускает обновление subtree, пока зависимости memo не изменились." },
      { id: "d", text: "Заменяет computed для всех случаев." },
    ],
    correctAnswer: "c",
    explanation: "v-memo позволяет Vue пропустить patching subtree, если массив зависимостей не изменился. Это точечный инструмент для тяжёлых повторяемых блоков, а не универсальная оптимизация.",
    knowledgeId: "performance-1215",
  },
  {
    id: 1216,
    moduleId: "performance",
    type: "Scenario",
    difficulty: "Middle",
    tags: [
      "defineAsyncComponent",
      "lazy-loading",
    ],
    question: "Тяжёлый график нужен только после клика “Показать аналитику”. Что разумно сделать?",
    answers: [
      { id: "a", text: "Импортировать график в главный bundle всегда." },
      { id: "b", text: "Сделать график readonly." },
      { id: "c", text: "Заменить график на watchEffect." },
      { id: "d", text: "Загрузить компонент лениво через defineAsyncComponent или dynamic import." },
    ],
    correctAnswer: "d",
    explanation: "Lazy loading убирает тяжёлый компонент из initial bundle и загружает его только при необходимости. Это улучшает стартовую загрузку, если компонент не нужен сразу.",
    knowledgeId: "performance-1216",
  },
  {
    id: 1217,
    moduleId: "performance",
    type: "CodeReview",
    difficulty: "Middle",
    tags: [
      "computed",
      "filtering",
      "review",
    ],
    question: "В template вызывается expensiveFilter(items) несколько раз. Что лучше предложить?",
    answers: [
      { id: "a", text: "Вынести результат в computed, чтобы использовать кеширование по зависимостям." },
      { id: "b", text: "Оставить метод в template, Vue всегда кеширует методы." },
      { id: "c", text: "Заменить items на document.body." },
      { id: "d", text: "Добавить setTimeout в template." },
    ],
    correctAnswer: "a",
    explanation: "Метод в template может вызываться при каждом render, даже если входные данные не изменились. computed пересчитывается только при изменении зависимостей, поэтому подходит для дорогой фильтрации и сортировки. Это не делает computed универсально быстрее всегда, но помогает избежать повторной работы для производных данных.",
    knowledgeId: "performance-1217",
  },
  {
    id: 1218,
    moduleId: "performance",
    type: "CodeOutput",
    difficulty: "Middle",
    tags: [
      "computed",
      "caching",
    ],
    question: "Когда computed пересчитает значение?",
    answers: [
      { id: "a", text: "При каждом mousemove на странице." },
      { id: "b", text: "Когда изменится одна из реактивных зависимостей, прочитанных внутри computed." },
      { id: "c", text: "Только после перезагрузки браузера." },
      { id: "d", text: "Никогда, computed всегда статичен." },
    ],
    correctAnswer: "b",
    explanation: "computed лениво кеширует результат и инвалидируется при изменении зависимостей. Это делает его полезным для производных данных, которые читаются в template или других эффектах. Если значение не зависит от reactive sources или вычисление имеет side effects, computed будет неправильным инструментом.",
    knowledgeId: "performance-1218",
  },
  {
    id: 1219,
    moduleId: "performance",
    type: "Architecture",
    difficulty: "Middle",
    tags: [
      "premature-optimization",
      "architecture",
    ],
    question: "Почему преждевременная оптимизация может быть вредна?",
    answers: [
      { id: "a", text: "Потому что быстрый код всегда неправильный." },
      { id: "b", text: "Потому что Vue запрещает оптимизации." },
      { id: "c", text: "Она усложняет код без доказанной проблемы и может ухудшить поддержку." },
      { id: "d", text: "Потому что DevTools нельзя открывать в production." },
    ],
    correctAnswer: "c",
    explanation: "Оптимизация должна отвечать на измеренный bottleneck, а не на ощущение, что код можно сделать сложнее. Если усложнить код заранее, команда получает стоимость поддержки без гарантированной пользы. Хороший подход: сначала измерить, затем выбрать минимальное изменение с понятным эффектом.",
    knowledgeId: "performance-1219",
  },
  {
    id: 1220,
    moduleId: "performance",
    type: "Interview",
    difficulty: "Middle",
    tags: [
      "bottleneck",
      "devtools",
      "lighthouse",
    ],
    question: "Как правильно начинать работу с performance-проблемой?",
    answers: [
      { id: "a", text: "Сразу добавить v-memo в каждый компонент." },
      { id: "b", text: "Удалить все computed." },
      { id: "c", text: "Заменить TypeScript на JavaScript." },
      { id: "d", text: "Измерить bottleneck через профилирование, Web Vitals, Vue DevTools или Lighthouse, а не гадать." },
    ],
    correctAnswer: "d",
    explanation: "Performance начинается с измерений. Нужно понять, проблема в network, render, JavaScript, layout, сервере, hydration или bundle, и только потом выбирать оптимизацию.",
    knowledgeId: "performance-1220",
  },
  {
    id: 1221,
    moduleId: "performance",
    type: "Scenario",
    difficulty: "MiddlePlus",
    tags: [
      "nuxt",
      "payload",
      "performance",
    ],
    question: "Nuxt payload стал очень большим из-за raw backend objects. Что сделать?",
    answers: [
      { id: "a", text: "Возвращать в payload только нужные клиенту поля и разбивать тяжёлые данные." },
      { id: "b", text: "Добавить все данные в runtimeConfig.public." },
      { id: "c", text: "Увеличить z-index корневого layout." },
      { id: "d", text: "Отключить TypeScript для payload." },
    ],
    correctAnswer: "a",
    explanation: "Большой payload замедляет загрузку, parsing и hydration, потому что клиенту нужно скачать и обработать больше данных. Нужно фильтровать DTO, не отправлять лишние поля и отделять critical данные от второстепенных. Для Nuxt это особенно важно: payload напрямую влияет на первое отображение и интерактивность.",
    knowledgeId: "performance-1221",
  },
  {
    id: 1222,
    moduleId: "performance",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "markRaw",
      "third-party",
      "review",
    ],
    question: "В reactive state положили большой экземпляр редактора Monaco. Что лучше проверить?",
    answers: [
      { id: "a", text: "Не нужно ли сделать все методы редактора computed." },
      { id: "b", text: "Не нужно ли исключить экземпляр из реактивности через markRaw или хранить в shallowRef." },
      { id: "c", text: "Не стоит ли рендерить редактор через v-for." },
      { id: "d", text: "Не нужно ли добавить key=Math.random()." },
    ],
    correctAnswer: "b",
    explanation: "Экземпляры сложных библиотек не должны становиться глубоко реактивными. Это создаёт лишний dependency tracking и может ломать внутреннюю модель библиотеки, если она ожидает обычные объекты. markRaw подходит для объектов, которыми Vue не должен управлять на уровне вложенных свойств.",
    knowledgeId: "performance-1222",
  },
  {
    id: 1223,
    moduleId: "performance",
    type: "CodeOutput",
    difficulty: "MiddlePlus",
    tags: [
      "v-once",
      "updates",
    ],
    question: "Что произойдёт с блоком v-once при изменении реактивных данных внутри него?",
    answers: [
      { id: "a", text: "Блок будет обновляться в два раза чаще." },
      { id: "b", text: "Vue автоматически заменит v-once на v-show." },
      { id: "c", text: "Блок не будет обновляться после первого render." },
      { id: "d", text: "Компонент перестанет монтироваться." },
    ],
    correctAnswer: "c",
    explanation: "v-once фиксирует результат первого render для subtree и исключает его из последующих обновлений. Если данные внутри блока должны меняться, UI останется устаревшим, даже если reactive state обновился. Поэтому v-once подходит только для действительно статичного содержимого, где такой контракт безопасен.",
    knowledgeId: "performance-1223",
  },
  {
    id: 1224,
    moduleId: "performance",
    type: "FindBug",
    difficulty: "MiddlePlus",
    tags: [
      "watch",
      "deep-watch",
      "performance",
    ],
    question: "deep watch стоит на большом объекте формы и запускает autosave при каждом изменении. В чём риск?",
    answers: [
      { id: "a", text: "deep watch никогда не отслеживает вложенные поля." },
      { id: "b", text: "watch запрещён во Vue 3." },
      { id: "c", text: "Autosave можно запускать только из CSS." },
      { id: "d", text: "Глубокий обход и частые autosave могут создать лишнюю нагрузку и сетевые запросы." },
    ],
    correctAnswer: "d",
    explanation: "Deep watch на больших структурах дорогой и может срабатывать слишком часто. Для autosave обычно нужны debounce, явные поля или более узкие зависимости.",
    knowledgeId: "performance-1224",
  },
  {
    id: 1225,
    moduleId: "performance",
    type: "BestPractice",
    difficulty: "MiddlePlus",
    tags: [
      "customRef",
      "debounce",
    ],
    question: "Когда customRef может помочь с производительностью?",
    answers: [
      { id: "a", text: "Когда нужно контролировать trigger, например сделать debounce для input state." },
      { id: "b", text: "Когда нужно полностью отключить Vue compiler." },
      { id: "c", text: "Когда нужно заменить HTTP cache." },
      { id: "d", text: "Когда нужно ускорить CSS selector." },
    ],
    correctAnswer: "a",
    explanation: "customRef позволяет вручную управлять track и trigger. Это удобно для debounced input, чтобы не обновлять зависимый UI на каждый символ.",
    knowledgeId: "performance-1225",
  },
  {
    id: 1226,
    moduleId: "performance",
    type: "Interview",
    difficulty: "MiddlePlus",
    tags: [
      "web-vitals",
      "lcp",
      "cls",
      "inp",
    ],
    question: "Какие Web Vitals особенно важны для frontend performance?",
    answers: [
      { id: "a", text: "Только количество Vue-компонентов." },
      { id: "b", text: "LCP, CLS и INP, потому что они отражают загрузку, стабильность layout и отзывчивость." },
      { id: "c", text: "Только размер package.json." },
      { id: "d", text: "Только число CSS-переменных." },
    ],
    correctAnswer: "b",
    explanation: "LCP показывает крупный контент, CLS — сдвиги layout, INP — отзывчивость взаимодействий. Эти метрики помогают связать оптимизацию с пользовательским опытом.",
    knowledgeId: "performance-1226",
  },
  {
    id: 1227,
    moduleId: "performance",
    type: "Scenario",
    difficulty: "MiddlePlus",
    tags: [
      "route-rules",
      "nuxt",
      "ttfb",
    ],
    question: "Публичная страница каталога редко меняется и имеет высокий TTFB. Что стоит рассмотреть в Nuxt?",
    answers: [
      { id: "a", text: "Полный запрет кеша для всех запросов." },
      { id: "b", text: "Замена всех компонентов на watchers." },
      { id: "c", text: "routeRules с кешированием, ISR/prerender или другую cache-first стратегию." },
      { id: "d", text: "Генерация random key для каталога." },
    ],
    correctAnswer: "c",
    explanation: "Если данные публичные и редко меняются, кеширование или генерация могут снизить TTFB. SSR на каждый запрос часто становится лишней работой.",
    knowledgeId: "performance-1227",
  },
  {
    id: 1228,
    moduleId: "performance",
    type: "CodeReview",
    difficulty: "MiddlePlus",
    tags: [
      "bundle",
      "import",
      "tree-shaking",
    ],
    question: "На review в общий layout импортирован огромный charting SDK, хотя график есть на одной странице. Что предложить?",
    answers: [
      { id: "a", text: "Оставить импорт в layout, чтобы bundle был единым." },
      { id: "b", text: "Добавить v-once к layout." },
      { id: "c", text: "Сохранить SDK в localStorage." },
      { id: "d", text: "Перенести SDK в lazy-loaded компонент или dynamic import на странице графика." },
    ],
    correctAnswer: "d",
    explanation: "Импорт в layout попадает в общий путь загрузки. Dynamic import и lazy компонент позволяют вынести редкий тяжёлый код в отдельный chunk.",
    knowledgeId: "performance-1228",
  },
  {
    id: 1229,
    moduleId: "performance",
    type: "Architecture",
    difficulty: "Senior",
    tags: [
      "bottleneck",
      "architecture",
    ],
    question: "Какой принцип лучше всего описывает поиск bottleneck?",
    answers: [
      { id: "a", text: "Сначала измерить, где теряется время: network, server, JavaScript, render, layout или hydration." },
      { id: "b", text: "Сначала переписать все компоненты на v-memo." },
      { id: "c", text: "Сначала удалить все props." },
      { id: "d", text: "Сначала отключить DevTools." },
    ],
    correctAnswer: "a",
    explanation: "Без измерений легко оптимизировать не то место: например, переписывать компоненты, когда проблема находится в network или main-thread задаче. Нужно найти реальную причину задержки, а затем выбирать точечное решение. Performance-аудит начинается с метрик, профайлера и воспроизводимого сценария.",
    knowledgeId: "performance-1229",
  },
  {
    id: 1230,
    moduleId: "performance",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "lazy-hydration",
      "nuxt",
    ],
    question: "Зачем в Nuxt может понадобиться lazy hydration?",
    answers: [
      { id: "a", text: "Чтобы удалить HTML из ответа сервера." },
      { id: "b", text: "Чтобы отложить интерактивность второстепенных блоков и снизить initial JS/CPU cost." },
      { id: "c", text: "Чтобы запретить tree shaking." },
      { id: "d", text: "Чтобы сделать все компоненты синхронными." },
    ],
    correctAnswer: "b",
    explanation: "SSR может быстро показать HTML, но hydration стоит CPU. Lazy hydration помогает не оживлять всё сразу, особенно блоки ниже первого экрана.",
    knowledgeId: "performance-1230",
  },
  {
    id: 1231,
    moduleId: "performance",
    type: "Scenario",
    difficulty: "Senior",
    tags: [
      "inp",
      "main-thread",
      "performance",
    ],
    question: "INP плохой из-за тяжёлой обработки input на каждый символ. Что сделать?",
    answers: [
      { id: "a", text: "Добавить больше watchers без ограничений." },
      { id: "b", text: "Сделать input readonly для всех пользователей." },
      { id: "c", text: "Уменьшить работу в обработчике: debounce/throttle, computed caching, web worker или перенос тяжёлой логики." },
      { id: "d", text: "Увеличить payload." },
    ],
    correctAnswer: "c",
    explanation: "INP связан с отзывчивостью взаимодействий пользователя. Если обработчик клика запускает тяжёлую синхронную работу, браузер не может быстро отрисовать следующий кадр. Нужно сокращать main-thread работу, дробить тяжёлые задачи и избегать лишних реактивных пересчётов в критический момент.",
    knowledgeId: "performance-1231",
  },
  {
    id: 1232,
    moduleId: "performance",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "cls",
      "images",
      "review",
    ],
    question: "Lighthouse показывает высокий CLS из-за изображений без размеров. Что исправить?",
    answers: [
      { id: "a", text: "Добавить v-memo на img." },
      { id: "b", text: "Отключить alt." },
      { id: "c", text: "Заменить все изображения на watchers." },
      { id: "d", text: "Задать width/height или aspect-ratio, чтобы браузер зарезервировал место до загрузки." },
    ],
    correctAnswer: "d",
    explanation: "CLS возникает от неожиданных сдвигов layout после первичной отрисовки. Размеры или aspect-ratio позволяют зарезервировать пространство и избежать скачков при загрузке изображения. Это простой, но важный production-паттерн для карточек, баннеров, галерей и media-heavy страниц.",
    knowledgeId: "performance-1232",
  },
  {
    id: 1233,
    moduleId: "performance",
    type: "CodeOutput",
    difficulty: "Senior",
    tags: [
      "dynamic-import",
      "code-splitting",
    ],
    question: "Что обычно делает dynamic import компонента?",
    answers: [
      { id: "a", text: "Позволяет вынести код в отдельный chunk и загрузить его позже." },
      { id: "b", text: "Делает компонент полностью статичным HTML." },
      { id: "c", text: "Отключает реактивность внутри компонента." },
      { id: "d", text: "Запрещает tree shaking." },
    ],
    correctAnswer: "a",
    explanation: "Dynamic import создаёт асинхронную границу загрузки. Bundler может вынести код в отдельный chunk, который загружается по необходимости, например при открытии маршрута или тяжёлого виджета. Это уменьшает initial bundle, но требует думать о loading state и возможной задержке первого открытия.",
    knowledgeId: "performance-1233",
  },
  {
    id: 1234,
    moduleId: "performance",
    type: "FindBug",
    difficulty: "Senior",
    tags: [
      "prefetch",
      "network",
      "nuxt",
    ],
    question: "Страница агрессивно prefetch-ит десятки тяжёлых маршрутов на слабой сети. В чём риск?",
    answers: [
      { id: "a", text: "Prefetch всегда бесплатный." },
      { id: "b", text: "Prefetch может конкурировать с критичными ресурсами и ухудшить стартовую загрузку." },
      { id: "c", text: "Prefetch влияет только на CSS color." },
      { id: "d", text: "Nuxt не умеет prefetch." },
    ],
    correctAnswer: "b",
    explanation: "Prefetch полезен, потому что может заранее подготовить ресурсы для вероятного перехода. Но он потребляет network и cache budget, а на слабых устройствах чрезмерный prefetch может мешать важным ресурсам. Хорошая стратегия учитывает вероятность перехода, размер chunk и условия сети.",
    knowledgeId: "performance-1234",
  },
  {
    id: 1235,
    moduleId: "performance",
    type: "BestPractice",
    difficulty: "Senior",
    tags: [
      "tree-shaking",
      "bundle",
    ],
    question: "Что помогает tree shaking?",
    answers: [
      { id: "a", text: "Импорт всей библиотеки через wildcard в общий layout." },
      { id: "b", text: "Глобальная регистрация всех компонентов заранее." },
      { id: "c", text: "ES module imports, отсутствие лишних side effects и точечные импорты библиотек." },
      { id: "d", text: "Хранение bundle в cookie." },
    ],
    correctAnswer: "c",
    explanation: "Tree shaking удаляет неиспользуемый код, если bundler может безопасно понять зависимости. Side effects, wildcard imports и большие общие entrypoints мешают этому, потому что код может быть нужен ради побочного эффекта. Для production важно импортировать конкретные функции и следить за sideEffects.",
    knowledgeId: "performance-1235",
  },
  {
    id: 1236,
    moduleId: "performance",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "keepalive",
      "cache",
      "components",
    ],
    question: "Какой trade-off есть у KeepAlive?",
    answers: [
      { id: "a", text: "Он всегда уменьшает память." },
      { id: "b", text: "Он работает только с CSS." },
      { id: "c", text: "Он заменяет HTTP cache." },
      { id: "d", text: "Он сохраняет состояние и ускоряет повторное открытие, но увеличивает память и может держать устаревшие данные." },
    ],
    correctAnswer: "d",
    explanation: "KeepAlive кеширует экземпляры компонентов и сохраняет их локальное состояние между переключениями. Это ускоряет возврат, но живые экземпляры занимают память и требует стратегии обновления данных. Поэтому KeepAlive полезен для форм, вкладок и дорогих экранов, но не должен применяться без ограничений.",
    knowledgeId: "performance-1236",
  },
  {
    id: 1237,
    moduleId: "performance",
    type: "Scenario",
    difficulty: "Senior",
    tags: [
      "suspense",
      "async-components",
    ],
    question: "Несколько async components должны показывать согласованный fallback во время загрузки. Что рассмотреть?",
    answers: [
      { id: "a", text: "Suspense, если нужна координация async dependencies и fallback UI." },
      { id: "b", text: "Teleport в head." },
      { id: "c", text: "readonly для всех props." },
      { id: "d", text: "Глубокий watch всего route object." },
    ],
    correctAnswer: "a",
    explanation: "Suspense помогает управлять асинхронными зависимостями и fallback в дереве компонентов. Он не является универсальным ускорителем, но улучшает orchestration async UI и делает состояние загрузки предсказуемее. Производительность улучшается косвенно, когда пользователь видит стабильный fallback вместо хаотичных частичных состояний.",
    knowledgeId: "performance-1237",
  },
  {
    id: 1238,
    moduleId: "performance",
    type: "CodeReview",
    difficulty: "Senior",
    tags: [
      "teleport",
      "rendering",
      "review",
    ],
    question: "Tooltip рендерится глубоко в таблице с overflow и вызывает сложные layout-проблемы. Что может помочь?",
    answers: [
      { id: "a", text: "Сделать tooltip reactive глубже." },
      { id: "b", text: "Teleport tooltip в body или специальный overlay root, чтобы избежать лишних ограничений контейнера." },
      { id: "c", text: "Добавить 10 000 пустых строк." },
      { id: "d", text: "Заменить tooltip на deep watch." },
    ],
    correctAnswer: "b",
    explanation: "Teleport не ускоряет всё автоматически, но помогает вынести overlay из сложной DOM-иерархии. Это может снизить проблемы layout, stacking context и z-index, особенно для модалок, popover и toast. Performance-выигрыш вторичен: главная ценность в более надёжной структуре DOM.",
    knowledgeId: "performance-1238",
  },
  {
    id: 1239,
    moduleId: "performance",
    type: "Architecture",
    difficulty: "Senior",
    tags: [
      "optimization",
      "architecture",
    ],
    question: "Когда оптимизация может быть вредной?",
    answers: [
      { id: "a", text: "Когда она основана на измерениях." },
      { id: "b", text: "Когда она уменьшает bundle без побочных эффектов." },
      { id: "c", text: "Когда она усложняет архитектуру, ухудшает UX или решает несуществующий bottleneck." },
      { id: "d", text: "Когда она исправляет LCP-проблему." },
    ],
    correctAnswer: "c",
    explanation: "Оптимизация имеет стоимость поддержки и риски: код может стать сложнее, хрупче и менее понятным. Если bottleneck не доказан или решение ухудшает UX, такая оптимизация вредна. На senior-уровне важно уметь отказаться от оптимизации, которая не подтверждена метриками.",
    knowledgeId: "performance-1239",
  },
  {
    id: 1240,
    moduleId: "performance",
    type: "Interview",
    difficulty: "Senior",
    tags: [
      "performance-strategy",
      "senior",
    ],
    question: "Как выглядит зрелый подход к performance в Vue/Nuxt?",
    answers: [
      { id: "a", text: "Добавлять v-memo и lazy loading везде без анализа." },
      { id: "b", text: "Оптимизировать только количество строк кода." },
      { id: "c", text: "Полностью игнорировать Web Vitals." },
      { id: "d", text: "Измерять, находить bottleneck, выбирать точечную оптимизацию и проверять результат метриками." },
    ],
    correctAnswer: "d",
    explanation: "Зрелая performance-работа начинается с метрик и профилирования. После оптимизации нужно повторно измерить эффект, иначе невозможно понять, стала ли система лучше.",
    knowledgeId: "performance-1240",
  },
]
